### ISSUE TITLE
Investigate the use of DNS-like lookup of contacts

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#172]
[MultiBit Classic #599](https://github.com/jim618/multibit/issues/599) proposes a feature where contact information can be looked up through a DNS-like user name service such as OneName or similar. This gives a better user experience than manual entry of a contact, but comes at the cost of a potential loss of privacy or exposure to name spoofing/MITM etc. 

This issue is here to act as a discussion board for the introduction of this kind of feature.

**Comment by jim618** [comment]
Out of scope hence graveyard
