### ISSUE TITLE
If user sets a cloud backup dir backup should be performed immediately

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#280]
At the moment if a user skips setting a cloud backup dir when they create a wallet and then set one later a cloud backup is not performed immediately.

It would make sense to do a cloud backup driven by the user setting the cloud backup dir.

**Comment by bitcoin-solutions** [comment]
I've changed the EditWalletPanelView so that if the user sets a cloud backup manager using the file chooser a cloud backup is set at the next 'tick' of the BackupService.
(BackupService ticks at 120 seconds after first start up and then every 12 seconds after that).

To test it you might have to fiddle with the cloud backup directory set in your YAML as we tend to set it at wallet creation wherever possible.

Awaiting review and closing

**Comment by gary-rowe** [comment]
No way to force an immediate backup?

**Comment by bitcoin-solutions** [comment]
No point in messing with the threadedness of the backup creation.
At the moment the only thing making backups is the backup service so we don't get any write contention.
Cleaner if we just tell it to make a cloud backup at the next tick.

**Comment by bitcoin-solutions** [comment]
Just checked the code - the first tick of backup service is 60 seconds after startup (not 120) and then every 12 seconds after that.

**Comment by gary-rowe** [comment]
Verified working. Might be a little eager since it appears to trigger even before the Apply button is clicked. Not a big enough issue to prevent closing.
