### ISSUE TITLE
On a send you cannot paste in the amount without a recipient

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#290]
On the send screen you cannot paste in a bitcoin amount from your paste buffer until you select a recipient. The recipient field goes red and grabs focus if it is blank.
It's a bit annoying as you should be able to enter either an amount or recipient first.

**Comment by bitcoin-solutions** [comment]
Altered verifier so that user can move focus from recipient is fails validation

**Comment by gary-rowe** [comment]
OK. There may be other fields where this behaviour should be copied to ensure consistent behaviour. It may also affect the FEST tests.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
