### ISSUE TITLE
Implement MultiBit Commons library

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#295]
Introducing a "MultiBit Common" library will allow some low-level utilities to be shared across projects and modules. This will help unlock some TODOs in BRIT and Core. 

Here is a suggested phased approach.

### Phase 1 - MultiBit HD module (Public Beta 1)

1. Introduce `multibit-common` (not `mbhd-common`) to MultiBit HD project as a module
1. Refactor Move as many low level utilities from BRIT and Core as possible including (`SecureFiles`, `ZipFiles`,`SafeExecutors`, `Dates`, `Numbers`, `OSUtils`, `DocumentMaxLengthFilter`)

The criteria for inclusion in the MultiBit Common library will be that no dependencies beyond JVM, Guava and SLF4J/Logback supplied classes will be permitted. 

### Phase 2 - Bitcoin Solutions library (sometime after Release 0.1)

1. Move `multibit-common` out of MultiBit HD into its own repo under MIT licence
1. Add as dependency to MultiBit Hardware (only `SafeExecutors`)

**Comment by gary-rowe** [comment]
This has been bumped up the queue of work due to the refactoring work taking place for 0.1.2.

**Comment by jim618** [comment]
Does it mean we'll have to delay 0.1.2 at all ?

**Comment by gary-rowe** [comment]
No - it should all slot into place quite easily. I've nearly finished the BritService integration so you can review it later today all being well.

**Comment by gary-rowe** [comment]
I've pushed the initial draft into our staging repo under `develop-SNAPSHOT` and the `brit-refactor` branch of BritService builds on Travis.

Ready for initial review (cannot close until MultiBit HD has integrated it later today)

**Comment by gary-rowe** [comment]
I'll integrate it into ErrorReportingService shortly, then MultiBit HD - both in their respective develop branches.

**Comment by gary-rowe** [comment]
This is now present in ErrorReportingService and MultiBit HD.

**Comment by jim618** [comment]
Builds and tests fine.
Just needs merging to master and issuing as a versioned artefact now.

**Comment by gary-rowe** [comment]
OK. I'll start doing that now. I'll release it as 1.0.0 since that code has been well tested out in the field and has just been repackaged into a JAR.

**Comment by jim618** [comment]
This is now versioned so closing
