### ISSUE TITLE
Empty wallet can say there is a BRIT fee when it actually gets elided

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#296]
Just tried a Tools | Empty wallet.

With this tx:
https://blockchain.info/tx-index/7e2d5b89073ae4ce2abfb134256e33cc2b15a95bcf0854b08b14302bec62761a

In the send summary it stated that the BRIT fee was 0.02 mBTC, payable now.
In fact the BRIT fee was elided form the tx as dust (which is correct behaviour).
The summary shouldn't say there is a BRIT fee to pay if that transaction output is elided.

**Comment by bitcoin-solutions** [comment]
There was a new SendRequestSummary being generated instead of reusing the same one, causng a bug. Fixed.
Worth reviewing BitcoinNetworkService changes in detail.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Went to empty wallet with a client fee of 0.01mB and saw this:
![screen shot 2015-02-18 at 21 34 49](https://cloud.githubusercontent.com/assets/342133/6257176/073aa506-b7b6-11e4-8dd8-a1a42c6b866c.png)

I don't think it's working.

**Comment by bitcoin-solutions** [comment]
I presume you had a milli in that wallet and emptied it to the MultiBit donaiton address.

In which case it is EXACTLY what I would expect.
Total amount of transaction = 1 milli, of which there is a mining fee of 10 mikes and a client fee of 10 mikes.

**Comment by bitcoin-solutions** [comment]
Note that the amount of the transaction we are showing in the payments table and the transaction details is the amount INCUDING fees.

**Comment by bitcoin-solutions** [comment]
Ah no that is a bit inconsistent. On a regular send we specify the net amount and then the mining fee and client fee are added.
This is probably better as it shows the net amount that is being paid to whoever.

I'll change it so that in an Empty Wallet the net amount is shown

**Comment by jim618** [comment]
I have updated the Empty wallet code so that it shows the NET amount that will be recovered from the wallet. Screenshot:

![screen shot 2015-02-19 at 10 27 09](https://cloud.githubusercontent.com/assets/919427/6265194/56dd032a-b823-11e4-86ec-757529b81139.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
