### ISSUE TITLE
Semantics of Trezor Restore screen off Credentials isn't quite right

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#303]
When the user has a Trezor plugged in and clicks 'Restore' they currently have the options:
1) Create new Trezor wallet
2) Use an existing wallet
3) Restore password from seed
4) Restore wallet

1) and 2) are fine.
for 3) we don't have a password for Trezor wallets so the user cannot do password recovery. I think we should remove this option. (We don't know the actual Trezor PIN in MBHD so cannot offer PIN recovery).

Also, currently option 4) just shows the PIN matrix for the existing Trezor wallet
The user doesn't have the opportunity to restore a Trezor wallet backup so it's pretty confusing.

I think it should feed into the 'find wallet backups and show to user' so that the user can restore the contacts/ wallet etc for a Trezor wallet if it is damaged on disk (or needs recovering from a cloud backup).

**Comment by bitcoin-solutions** [comment]
Also we need to give te user the ability to recover from a forgotten PIN (say with a Trezor wipe)

**Comment by bitcoin-solutions** [comment]
Updated use case:

#### Use case: Wiped Trezor attached at cold start

1) User starts fresh MBHD with a wiped Trezor attached
2) MBHD responds with licence -> language -> create Trezor wallet preparation (we skip the select because of "Trezor mode")
3) User provides a cloud backup location, sets the PIN and creates the wallet as usual. MBHD writes the wallet.
4) MBHD does no checking for existing backups (it can't without Unlock) and simply presents the credentials screen (they need practice in using this screen under the principle of least surprise)
5) User is viewing the credential screen showing a PIN matrix, an Exit button and a Next button (initially grayed out). User performs PIN + Unlock (first time with Unlock at this point)
5a) An incorrect PIN repeats PIN request via Unlock request (user can Exit)
5b) A cancelled Unlock (on the Trezor) switches to password mode (user doesn't want to use this Trezor after all and wants to work with soft wallets in some way) - or they can Exit
5c) A detached Trezor switches to password mode
5d) A re-attached Trezor switches to Trezor mode (PIN + Unlock = step 4)
6) After the PIN + Unlock MBHD works out the wallet id and entropy/ password and attempts to load the wallet. If the wallet loads successfully it shows the wallet load report screen showing success. If the wallet load fails it automatically attempts to load any available rolling backups. If one of these load successfully it shows the report screen indicating that the primary wallet did not load and it is using a backup. If no rolling backup is available or none load successfully it shows the report screen indicating the nature of the failure.

7) MBHD shows the wallet load report screen with a message as to whether the wallet loaded ok or not and the following options:
7a) Exit - MBHD terminates
7b) Restore - proceed to Restore use case
7c) Finish - MBHD shows Send/Request with the empty wallet. Finish is enabled only if the wallet (or rolling backup) loaded ok. On Finish MBHD will take them straight into their wallet (user has already unlocked it and will be aware of this)

### Use case: restore
Invoked from 7b) above.

1) MBHD looks to see if it has any zip backups in the wallet "zip-backup" directory. If there are any it shows the dates of the available zip backups in a combo box (most recent first). The user chooses a zip backup and MBHD restores it. The user is shown a restore report page (step 3).  If there are no zip backups in the wallet directory proceed to 2).
2) (No zip backups in wallet directory) The user is asked for the cloud backup directory. If there are any zip backups in this directory the user is shown a combo box with the zip backups available (most recent first). The user selects a zip backup and MBHD restores it. The user sees a restore report screen (step 3).
3) (Wallet restore report screen). This screen has a Finish button only. The user is told whether the the zip backup previously selected restored ok. If no zip backup was available or it failed to restore the user is told that they can also restore a Trezor as a Trezor soft wallet (mentioned here as it not obvious). After Finish the user is sent to the credentials screen which, as it is in Trezor mode, will show a PIN matrix.

#### Use case: Wiped Trezor attached at warm start

1) Same as "wiped Trezor attached at cold start" but licence -> language are skipped and user is straight into create Trezor wallet preparation

#### Use case: Initialised Trezor attached at cold start

1) User starts fresh MBHD with an initialised Trezor attached
2) MBHD responds with licence -> language -> and automatically selects "use existing wallet" because of "Trezor mode"
3) Follow from step 4 in "wiped Trezor attached at cold start"

#### Use case: Initialised Trezor attached at warm start

1) User starts licensed MBHD with an initialised Trezor attached
2) Follow from step 4 in "wiped Trezor attached at cold start"

**Comment by bitcoin-solutions** [comment]
The functionality to do a restore of the zip backups for a Trezor hard wallet is now pushed.
The ability to create a new Trezor wallet is temporarily not accessible as it used to be on the restore wallet select option page which has disappeared.
That will be worked on next.

As this is a whopper issue I will probably split it out into smaller bite sized chunks as it will be easier to work on.

**Comment by bitcoin-solutions** [comment]
Oh -  and you'll have to pull and build multibit-hardware

**Comment by gary-rowe** [comment]
I've split this epic into smaller issues that are more manageable and highlight the need for FEST tests to drive their implementation.

Ready to close if you agree.

**Comment by bitcoin-solutions** [comment]
agreed
