### ISSUE TITLE
Create 0.0.5 Public Beta 5 installer

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#306]
Once all Public Beta 5 issues are out of the way the installer can be created and pushed to the main website.

This needs to be done as follows:

1. Ensure all issues are completed for milestone
1. Update checkpoints file
1. Merge from develop into master, tag code
1. Ensure comprehensive functional tests (FEST, stress and emulator) run correctly
1. Create and sign installer using Windows and Apple developer keys
1. Smoke test installers on each operating system
1. Create release note with SHA256 hashs of the binaries, bitcoin signed by the MultiBit donation address
1. Push to website following the directory naming conventions
1. Update the beta website code to reflect the new version
1. Push the beta website code
1. Issue a Private Beta Group notification
1. Wait 24 hours for feedback (if any)
1. Update upgrade XML so that auto updates start
1. Issue general notification on social media (if appropriate)

**Comment by gary-rowe** [comment]
No more outstanding issues at the MultiBit HD level. I think we can use the develop-SNAPSHOT release of MultiBit Hardware for the first batch of installers ("early bird"). I should be able to clear out the remaining issues and create a release (0.1.0) tomorrow all being well.

**Comment by bitcoin-solutions** [comment]
Binaries, PGP signatures and release.txt (wth SHA256 hashes) uploaded to:
https://beta.multibit.org/releases/multibit-hd/multibit-hd-0.0.5beta/

**Comment by gary-rowe** [comment]
OK, verified the installers are working and signature is correct. 

We've seen a few glitches on Windows but nothing severe enough to act as a showstopper for a beta edition.

Given that any issues arising from this will be addressed in Release 0.1 I'm going to close this issue and the accompanying milestone.
