### ISSUE TITLE
Include Trezor emulator in FEST tests

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#308]
In order to have a higher level of confidence in the operation of the code we need to have comprehensive FEST test coverage of the Trezor operations which is currently a manual process and subject to regression. 

Within MultiBit Hardware we have a scripted emulator that simply replays events with payloads on a given timeline. This could be modified to match known use cases and then integrated into the FEST test environment. In this way we can fully explore test cases quickly and efficiently.

**Comment by bitcoin-solutions** [comment]
The emulator is now in the MBHD code base so am closing this issue.
