### ISSUE TITLE
Trezor wallet label incorrect on first synch

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#315]
The following sequence yields incorrect behaviour:

1. Unlock a fresh hard wallet (e.g. multibit.org 123) and perform a switch after synch.
1. Cancel out from the unlock and click Restore
1. Create a fresh hard wallet (e.g. multibit.org 456) finishing up with a synch after unlock.
1. Observe the title bar indicating "multibit.org 123" not "multibit.org 456" as expected.

**Comment by gary-rowe** [comment]
I've pushed a bunch of changes to MultiBit Hardware to cover the Features refresh and it appears to have worked. The label is correctly placed after the user creates a Trezor wallet and clicks Finish.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
This is not possible to verify at the moment because you cannot create a new Trezor wallet after loading an existing one without restarting MBHD. This loses any previous Features setting so you cannot tell if it is being cleared correctly.

**Comment by bitcoin-solutions** [comment]
As #317 is done I have rechecked this.
Closing
