### ISSUE TITLE
FEST test for initialise Trezor use case

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#318]
Require a FEST test to cover the Trezor initialisation use case:

* cold start with Trezor attached
* select backup, PIN and work through seed phrase
* verify report

See #303 for more details about the use cases

**Comment by gary-rowe** [comment]
Can you provide more details? I would like to configure Travis to perform Windows and OSX builds so these issues can be trapped earlier.

**Comment by innodonni** [comment]
The root issue is that NTFS doesn't like file handles to be left open before rename/delete. I could open a separate issue to that effect.
`mvn clean install` resulted in 1 test failure to be listed:
`BasicMatcherTest.testPayerRequestAndMatcherResponse1:105 » PayerRequest Could ...`
After changing BasicPayer to not use a temp file in `PGPUtils`, the following failures were listed:
`EncryptedFileReaderWriterTest.testEncryptDecryptSuccess:74 » EncryptedFileReaderWriter
PersistentContactServiceTest.testLoadAndStore:132 » ContactsSave Could not sav...
PersistentHistoryServiceTest.testLoadAndStore:119 » HistorySave Could not save...
WalletServiceTest.testChangePassword:153 » IllegalState Not encrypted
WalletServiceTest.testCreatePaymentRequest:119 » PaymentsSave Could not write ...
TrezorWalletTest.testChangePasswordTrezorSoftWallet:420 » IllegalState Not enc...
TrezorWalletTest.testCreateTrezorHardWalletFromRootNode:197 » IO Failed to del...
TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed:312 » IO Failed to de...`
After I modified `SecureFiles.writeFile` to close file handles before rename, only the Trezor tests threw in saveWalletFile:
`TrezorWalletTest.testCreateTrezorHardWalletFromRootNode:197 » IO Failed to del...
TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed:312 » IO Failed to de...`
After modifying `SecureFiles.fastSecureDelete` to force the mmap buffer to close the file handle (not supported by the `java.nio` API!), all tests passed.

Looks like [Windows builds](https://github.com/travis-ci/travis-ci/issues/216) is still an open issue.

**Comment by gary-rowe** [comment]
@innodonni I've been away from the keyboard so I'll raise a separate issue for your earlier comments now that I'm back. If you could follow up in that issue it'll help me to keep track of everything.

**Comment by gary-rowe** [comment]
This FEST test will run through the wallet creation process for a cold start with wiped Trezor attached. It finishes at the Finish button.

To verify simply run the `MultiBitHDFestTest.verifyHardwareWalletCreateWallet()` method. Ensure you have the latest MultiBit Hardware downloaded from the staging repo/installed from git.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Runs through fine.
Closing
