### ISSUE TITLE
Confusing Verify Network between peers discovered and sync starts

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#319]
Once peers have been discovered but before sync starts (which can be several seconds) Verify netowrk shows:

x Peers 0
x Blocks 0

Both of these are wrong. Peers can be 6 in the indicator in the footer.

I think the VerifyNetwork panel isn't processing the BitcoinNetworkChangedEvents that propagate out the PeerCounts.
I noticed this on a trezor wallet but doubt it is trezor specific

**Comment by bitcoin-solutions** [comment]
After discussion: we're overloading the BitcoinNetworkChangeEvent for both peer counts and block info so separate them out - create a PeerCountChangeEvent

**Comment by bitcoin-solutions** [comment]
This has been fixed with greater precision in the construction of BitcoinNetworkSummary events.
Now if MBHD takes a while to connect the Verify network screen shows this:
![screen shot 2015-01-03 at 14 23 21](https://cloud.githubusercontent.com/assets/5002074/5602636/5cb3afb8-9354-11e4-9144-94091f686cb1.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified that the peer count is now correct.

Closing.
