### ISSUE TITLE
When no exchange double clicking a transaction and closing gives quirky display

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#321]
When there is no exchange (due to a firewall or whatever) and you do the following:

1) Send payment.
2) Double click a payment to see the details
3) Dismiss the transaction details wizard 

you see the following:
![screen shot 2015-01-04 at 14 08 02](https://cloud.githubusercontent.com/assets/5002074/5606206/4c05f1ae-941b-11e4-8043-8cd0fb244e8c.png)

The highlighting is wrong and the amount should not be present (as there is no fiat equivalent)

**Comment by jim618** [comment]
Bumped to 0.1.3

**Comment by gary-rowe** [comment]
The highlighting is likely to have been fixed in 0.1.1 but the amount field needs attention.

**Comment by jim618** [comment]
The highlighting is fixed as per previous comment.
Screenshot:

![screen shot 2015-07-28 at 13 42 44](https://cloud.githubusercontent.com/assets/919427/8931525/db268c18-352e-11e5-9e82-6b6c77803d65.png)


Back fill of the fiat amount is covered by #679 so nothing to do remaining on this issue.

Closing
