### ISSUE TITLE
Add Findbugs to Maven build process

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#323]
As part of the overall code hardening process we should include this standard plugin. There will be pain at first but the final result will be much better code.

It's also worth Installing the Findbugs Intellij plugin  which is arguably better than the QAPlug wrapper version.

**Comment by gary-rowe** [comment]
Cleared the Core module.

Jim, can you go through these changes in case anything sticks up as being excessive? If you find something just revert the change and mark it as supressed with a justification.

**Comment by gary-rowe** [comment]
Cleared the Swing module.

Jim, as before can you go through these changes in case anything sticks up as being excessive? If you find something just revert the change and mark it as supressed with a justification.

If you're all good with everything then I'll activate the Findbugs on the Maven build so we fail the build if one sneaks in. We must be stringent about running `mvn clean verify` before every commit going forward.

**Comment by gary-rowe** [comment]
And another thing, Jim, make sure you activate the fb-contrib plugin on Findbugs-IDEA (see its settings) to get a whole bunch of extra bugs.

**Comment by gary-rowe** [comment]
I'm pretty happy that we've nailed all the bugs at Medium level. I'll add a new issue under a different milestone to cover moving from Medium to Low threshold to get the rest.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Solid work there Gary !
I've just run the build with findbugs at medium and it runs clear.
Also installed findbugs into my Intellij.

Closing
