### ISSUE TITLE
Header not showing on wallet unlock

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#324]
There are several problems with the choice of thread to execute the credentials wizard hide and handover operations. It is now running on the EDT which is different to before and will require some investigation to determine what has caused the change.

As a workaround to get the DetailView populating correctly, `MainController.hideCredentialsWizard` can be edited to remove the EDT wrapper for `mainView.reset()` around line 1248.

**Comment by bitcoin-solutions** [comment]
I've put in the fix Gary mentioned into MainController and the DetailView is being shown correctly now when a Trezor wallet is loaded. I'll leave this issue open as it's only a proximal fix.

**Comment by bitcoin-solutions** [comment]
I've been creating some Trezor wallets from scratch today and have seen this a couple of times.

**Comment by bitcoin-solutions** [comment]
Fixed. There are some diagnostic debugs that I will leave in the logs for a while until we are sure this is squashed.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified this is working.

Closing.
