### ISSUE TITLE
FEST test for wiped Trezor at warm start

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#325]
Require a FEST test to cover the "Wiped Trezor at warm start" use case defined in #303.

This issue also covers the work required to implement the use case.

**Comment by gary-rowe** [comment]
This seemingly simple new FEST test opened up an enormous rabbit hole of improperly handled event subscriptions. 

To verify run `MultiBitHDFestTest.verifyCreateTrezorHardwareWallet_WarmStart()`.

As part of this work all FEST tests are now passing with an overall run time of about 9 mins.

Ready for review and close.

**Comment by gary-rowe** [comment]
This seemingly simple new FEST test opened up an enormous rabbit hole of improperly handled event subscriptions. 

To verify run `MultiBitHDFestTest.verifyCreateTrezorHardwareWallet_WarmStart()`.

As part of this work all FEST tests are now passing with an overall run time of about 9 mins.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
I ran the MultiBitHDFestTest.verifyCreateTrezorHardwareWallet_WarmStart(). FEST test successfully so closing.
