### ISSUE TITLE
FEST test for initialised Trezor at warm start

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#326]
Require a FEST test to cover the "InitialisedTrezor at warm start" use case defined in #303.

This issue also covers the work required to implement the use case.

**Comment by gary-rowe** [comment]
After extensive modifications of the `HardwareWalletEventFixtures` and `HardwareWalletFixtures` we now have a pretty comprehensive mock Trezor with realistic events in place. This should form the basis of a solid testing framework for a multitude of use cases in the future.

I had to add a flag in `WalletManager` to prevent synchronisation occurring prematurely during the FEST tests. If you see wallet sync events during FEST tests with an empty wallet fixture you'll need to verify this flag is `false`.

To verify, simply run `MultiBitHDFestTest.verifyUnlockTrezorHardwareWallet`. It should run to a complete wallet report then click Finish and end.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Yup - runs through cleanly so that is another one done - good work Gary!
Closing.
