### ISSUE TITLE
FEST test for initialised Trezor at cold start

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#327]
Require a FEST test to cover the "initialised Trezor at cold start" use case defined in #303.

This issue also covers the work required to implement the use case.

**Comment by gary-rowe** [comment]
I've done the FEST test for this functionality now. 

Verify with running `MultiBitHDFestTest.verifyUnlockTrezorHardwareWallet_ColdStart`

To verify with a real setup you'll need to remove the `multibit-hd.yaml` file (or go the whole way and move all content from the application directory elsewhere) and start with an initialised Trezor plugged in.
Expect to see the licence, language then credentials screens.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
I have tested this in real life successfully and run the FEST test successfuly.
Closing.
