### ISSUE TITLE
On password screen plugin and pull out Trezor should show PIN matrix

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#329]
In #303 it is stated that plugging in a Trezor traverses password -> PIN matrix and pulling out a Trezor traverses PIN matrix -> password.

**Comment by gary-rowe** [comment]
This partially works but we should produce a FEST test for full confidence.

**Comment by bitcoin-solutions** [comment]
I see trezor attached states in the log when I plug in a trezor on the password screen but nothing happens.

**Comment by bitcoin-solutions** [comment]
Also, related, if you pull out one trezor and plug in ANOTHER, you don't get an alert asking you whether you want to use it.

**Comment by bitcoin-solutions** [comment]
The original post (remove trezor = traverse to password screen, plug in = traverse to PIN matrix) is working. I'll raise a separate issue for an alert when you swop between two trezors.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
