### ISSUE TITLE
Add 'Wallet start up' screen for soft wallets

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#330]
I quite like the Trezor Wallet start up screen and think we should put it into the soft wallet load too.
It is primarily event driven.
Will break all the FEST tests when it goes in.

Also, there is a BackupWalletLoadedEvent which needs to be shown on this screen (it creates an alert att the moment). I suggest we use a different icon, say a "!" rather than a tick or cross.

**Comment by gary-rowe** [comment]
Agreed. 

The FEST tests should only require a modification to both the `QuickUnlockEmptyWalletFixtureRequirements` and `SlowUnlockEmptyWalletFixtureRequirements` to add a new use case covering the report.

Regarding the multi-icon status perhaps it's time to move from `Optional<Boolean>` to `StatusType` in `Labels`. One approach could be:
```
NONE,
SUCCESS,
FAILURE,
WARNING
```
This is a fairly hefty Refactor Change Signature but low impact in terms of side effects and would make the code a lot clearer.

**Comment by bitcoin-solutions** [comment]
There is now 'sunny day' code showing the Wallet load report for soft wallets.
It doesn't handle incorrect passwords cleanly yet as you traverse instantly to the wallet report form - I'll look at that next.

**Comment by bitcoin-solutions** [comment]
I've pushed more code to deal with users entering wrong passwords. This is code complete now other than fixing the FEST tests (which I will do tomorrow - Thurs).

**Comment by bitcoin-solutions** [comment]
@gary-rowe Did you update the FEST tests ? I just ran the SendRequest one and it ran ok even with the new Wallet load report.

Anyhow, assuming that is done, this is now ready for review and closing.

**Comment by gary-rowe** [comment]
Yes, you may have missed it in my recent emails. It was under #330 and just adds a click against the Finish button during the unlock processes (Quick and Slow).

**Comment by gary-rowe** [comment]
Verified working so closing.

**Comment by bitcoin-solutions** [comment]
Good stuff. I thought Santa's elves had done it
