### ISSUE TITLE
Remove Vault of Satoshi from exchange list

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#332]
Vault of Satoshi has announced that they are closing so they should no longer be listed.

From [their website](https://www.vaultofsatoshi.com/) today:

Vault of Satoshi will be closing on February 5th, 2015. Although new deposits will no longer be accepted, rest assured, you will have plenty of time to finalize any trades and withdraw any outstanding funds with all of the convenience and expeditiousness that you’re used to. Please ensure that all of your withdrawal requests are submitted by February 5th.

**Comment by gary-rowe** [comment]
Commented out the `ExchangeKey` and the XChange JAR so if it is taken over we'll be able to reinstate it quickly.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Confirmed Vault of Satoshi is not shown on the UI.
Closing
