### ISSUE TITLE
Remove printStackTrace and System.out.println references

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#333]
These should be removed or replaced with `log.error(e.getMessage(), e);` structures.

**Comment by gary-rowe** [comment]
Just needs a quick code review.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Looks good - a couple of System.out.printlns in the FontAwesome Tools but they are there for a reason.
Closing.
