### ISSUE TITLE
No user feedback if PIN is entered incorrectly

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#335]
If the user enters an incorrect PIN they are shown the PIN matrix screen again but there is no feedback that their last PIN entered was incorrect. This is confusing

**Comment by bitcoin-solutions** [comment]
An incorrect PIN now does a requestCancel on the Trezor and starts again.
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
