### ISSUE TITLE
Internal help should prevent external or non-help articles

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#339]
We need to add a regex to the link parser to remove these. The intention is to keep the help as simple as possible.

**Comment by gary-rowe** [comment]
The issue list is looking a bit biased against you, Jim, so I'll take this one on.

**Comment by gary-rowe** [comment]
Added "non-help" link detection as follows. The user hovers on a link and if it is not a MultiBit help link then the "Show in external browser" button highlights and if the user clicks the link then the external browser is activated with a new tab showing the contents. If there is no desktop browser access the button is disabled and a beep sound occurs if attempting to leave the safety of the internal browser.

The internal help and images have been updated to the latest from the beta site (HEAD of `release-4.0.0` branch).

A FEST test is available to verify page transitions against the internal help: `MultiBitHDFestTest.verifyHelpScreen`

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
That is very nice the way the 'View in external browser' highlights when you have an external link.
Closing
