### ISSUE TITLE
FEST test for plug in and pull out of trezor

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#341]
Required FEST test for insertion and removal of a trezor with the PIN matrix appearing and disappearing

**Comment by bitcoin-solutions** [comment]
Short FEST test to verify pull out and plug in of Trezor:
MultiBitHDFestTest#verifyPlugInAndPullOutTrezorHardwareWallet.

Awaiting review and closing

**Comment by gary-rowe** [comment]
FEST test verified working.

Closing.
