### ISSUE TITLE
Swopping between two trezors does NOT give an alert

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#342]
Mentioned in #329 
If you have a trezor wallet showing in MBHD and then:
1) remove the trezor
2) insert a DIFFERENT trezor

you should see an alert asking if you want to use the new trezor but you don't.

**Comment by bitcoin-solutions** [comment]
Now if you swop between two trezors you also see an alert (as long as their device names are different).
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working (very smooth) :-)

Closing.
