### ISSUE TITLE
Trezor not being recognised

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#345]
After the weekend's refactor the trezor plug in event seems to have got lost.
If you have a trezor plugged in at start up , or plug it in, nothing happens.
Of course this kills all trezor usage so I'll look at it next

**Comment by gary-rowe** [comment]
I'd suggest trying out the examples in MultiBit Hardware as a quick smoke test.

**Comment by bitcoin-solutions** [comment]
It turns out this was a faulty USB cable. Closing.
