### ISSUE TITLE
Repair wallet Finish not enabled on sync finish

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#347]
Screenshot:

![screen shot 2015-01-12 at 14 47 49](https://cloud.githubusercontent.com/assets/5002074/5704517/143e3920-9a6a-11e4-9bc8-26952c0ac61f.png)

**Comment by bitcoin-solutions** [comment]
Pushed some changes - SwingUtilities.invokeLater mainly.
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. 

Closing.
