### ISSUE TITLE
On create new wallet Unlock not enabled on PIN entry after create

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#348]
See screenshot - this is after the wallet create has completed:
![screen shot 2015-01-12 at 15 32 48](https://cloud.githubusercontent.com/assets/5002074/5705322/60e456c8-9a70-11e4-840c-ebd1b8f9f7b6.png)

**Comment by bitcoin-solutions** [comment]
This is a little messy.
It turns out there are TWO CredentialsWizard in existence, both registered to receive events and one says there is a pin and one says there isn't

You see it when you first use a password entry screen then plug in a trezor. This then creates a trezor credentials wizard but the other one is never destroyed.

This will no doubt cause other problems which we haven't noticed yet.

**Comment by gary-rowe** [comment]
Most likely the wizard hide event is not getting processed correctly during handover.

**Comment by bitcoin-solutions** [comment]
I've fixed this by keeping a reference to the CredentialsWizard in Wizards.
When a new one is created the old one is unsubscribed, together with the model and all the internal views. (It might be worth also doing this for the WelcomeWizard but I will leave that for now).

Note that you have to plug in the trezor AFTER start up to get an alert to test this.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Not sure I can let this one through code review. There must be a better way of trapping and co-ordinating the wizard handover process. 

I'll take this one on and move it out of awaiting review for now.

**Comment by bitcoin-solutions** [comment]
What's the problem exactly with not letting two CredentialsWizard exist at the same time ?
Do we ever want there to be two of these simultaneously ?
Sounds like a recipe for bad things to happen if there are.

I'd be happiest if the wizard handover is improved AND we don't allow two CredentialsWizards to exist by construction. Then we'll have belt and braces.

**Comment by gary-rowe** [comment]
Yes, that's what we're after. Sorry wasn't clear with my comments. It's the implementation of the singleton for `CredentialsWizard` that's bugging me. However it can wait and there is a TODO in the code to track it for later.

Closing.

**Comment by bitcoin-solutions** [comment]
Agreed it's not ideal. It isn't even a proper singleton as it is coded now. I tried that first but there is lots of state in a wizard and it didn't work too well.
