### ISSUE TITLE
After incorrect PIN entry PIN matrix should be cleared

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#350]
Currently if the user enters an incorrect PIN they traverse to the wallet load report form and can click 'Previous' to go back to the PIN matrix.

Whatever they previously entered is still there in the PIN matrix as "***" but it is useless as the trezor is displaying a DIFFERENT PIN layout. The previous value should be cleared when the previous is called

**Comment by bitcoin-solutions** [comment]
I've updated the PINMaV so that on failure the old PIN is cleared.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
