### ISSUE TITLE
Soft wallet possibly getting encrypted with Trezor entropy instead of password

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#352]
By plugging in and out a trezor whilst a soft wallet was in the process of loading I managed (I think) to get a copy of the soft wallet written out using the Trezor entropy as the password.
You then cannot load it with the password you entered (for the soft wallet).

Looks like the trezor and soft wallet password are mingling somehow.
I managed to recover the wallet by manually using one of the rolling backups.

**Comment by bitcoin-solutions** [comment]
As this is not easily recoverable for the user it needs a multipronged approach (belt and braces).
I suggest:
+ We don't allow the CredentialsWizard to switch between PIN mode and password word once you get past the initial screen (i.e. NOT when the Wallet load report is being shown).
+ Separate the model data for 'trezor password' and 'soft wallet password'

Anything else we can thing of.

**Comment by gary-rowe** [comment]
Agreed. This is one of those "cloudy day" situations we're aiming to cater for.

**Comment by bitcoin-solutions** [comment]
I've put in code so that when the Wallet report form is shown and the wallet is loading/ synchronising etc plugging in and pulling out the Trezor does not switch the CredentialsWizard.

Pushed and worth checking but I'll leave this issue open in case I can think of anything else to protect against this.

**Comment by gary-rowe** [comment]
After our discussions on this last night and reviewing the code here it's a robust solution.

Closing.
