### ISSUE TITLE
When fully synced, if you change a preference you see the green 100% progress bar

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#353]
When you are fully synced and make a change to one of the preferences you see the green 100% progress bar for a little while.

This is a bit confusing as it normally appears when a sync finishes (or a block appears).

It is probably caused by a replay of events when the main view refreshes but I think we should get rid of it.

**Comment by gary-rowe** [comment]
I'm undecided on this. I see your point, but I've found that my eye travels to the bottom left corner after a refresh, sees the synch at 100% and I feel a bit reassured that all is well. 

Purely from a psychological point of view, I'd prefer to push this issue into Release 0.1.

**Comment by bitcoin-solutions** [comment]
Sure no problem - let's leave this for now.

**Comment by gary-rowe** [comment]
I'll close it, but there's no problem with reopening it later if users give feedback.
