### ISSUE TITLE
Main view refresh removing 'Do you want to use trezor ?' alert on Wallet load report Finish

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#355]
On the wallet load form (for a soft wallet) I plugged in a trezor. It now does not switch to trezor PIN entry (bug fix for #352). You see a 'Do you want to use this trezor?' alert in the background (which is fine) but when you dismiss the Wallet load report with a finish the alert disappears.

Most probably something to do with the MainView#refresh not caching/ replaying the alert

**Comment by bitcoin-solutions** [comment]
I  have tweaked it so that when the MainController#hiseCredentials is called (only) the last hardwareWalletEvent is repeated. This is NOT in the mainView#refresh so won't get called after languges changes etc to minimise false positives.

Awaiting review and closing

**Comment by gary-rowe** [comment]
The existing code didn't include the message body so caused an empty alert. I've fixed this now and it's all working as required.

Closing.
