### ISSUE TITLE
Help load is on event thread - no network can (temporarily) freeze MBHD

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#356]
The loading of the help seems to be on the event thread.
I had a crappy network connection today and clicking help freezes MBHD for about 10 seconds before the HTTP load times out. You cannot navigate anywhere on the sidebar for instance.

It would be better to show the panel and load the HTTP in the background.

This will also make the UI more responsive.

**Comment by bitcoin-solutions** [comment]
Also need to check that if multibit.org is unavailable the internal help is used gracefully

**Comment by gary-rowe** [comment]
From memory, I think the `JEditorPane` requires the EDT and forces loading of the document on that thread. However there may be a workaround.

At present all HD help is served from `https://beta.multibit.org`. This will be changed once the site goes live (there's a TODO to indicate it but I'll add it to #306 to be certain).

**Comment by bitcoin-solutions** [comment]
I'm pretty sure in Classic the HTTP get was loaded in the background so that code might be worth recycling.

**Comment by gary-rowe** [comment]
OK, I'll take it on this evening.

**Comment by gary-rowe** [comment]
While working in this area I looked at the possibility of detecting a failure to load from the URL but this is rather hard to detect reliably in the JEditorPane. I've put in a little scaffolding code to support a future effort to solve this potential UX problem.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Tested by switching off WiFi and selecting Help. The 'stuckiness' of the UI has gone.
Closing
