### ISSUE TITLE
Look into bundling Carlito as the body font for modern look and feel

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#358]
User feedback from the beta testing group has indicated that using the default system font for the body gives a less pleasing choice of font for body text. This could be replaced with Calibri or the more open licenced Carlito (see http://blogs.gnome.org/uraeus/2013/10/10/a-thank-you-to-google/) instead.

Tests for compatibility with multiple languages will need to be conducted, but otherwise could be added to a `BodyFontDecorator` class and added to the `Themes` Nimbus configuration.

**Comment by bitcoin-solutions** [comment]
I don't think this is essential for PB 5 and should be bumped later.

**Comment by gary-rowe** [comment]
OK, bumped.

**Comment by gary-rowe** [comment]
Unfortunately this change of font is a no-go for the following reasons:

* differing font sizes (too small in some places, too large in others)
* does not support hard space character (required for currency display)
* adds 600Kb to download
* OS X didn't render it too well so likely Windows would be much worse based on #384 findings

![screen shot 2015-02-17 at 21 30 30](https://cloud.githubusercontent.com/assets/342133/6237613/435a91f6-b6ec-11e4-9ede-d4280ce8005b.png)

That said, it's a lovely web font and a shame we can't go with it.
