### ISSUE TITLE
Help refers to 'seed phrase' rather than 'wallet words'

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#360]
The MBHD help refers to 'seed phrase' rather than 'wallet words'.
This is in both the text - for example in the 'create new wallet wizard' and in some of the screen shots.

**Comment by gary-rowe** [comment]
See MultiBit Site issue [#159](https://github.com/bitcoin-solutions/multibit-website/issues/159).

**Comment by bitcoin-solutions** [comment]
Closed as dupe.
