### ISSUE TITLE
Compatibility testing with other wallets

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#362]
Need to test compatibility with the following HD wallets as a first pass "smoke test":

* myTREZOR.com - verified
* Mycelium - verified
* Blockchain.info xpub API - verified

**Comment by gary-rowe** [comment]
Mycelium (BIP44) verifies as follows:

1. Perform Mycelium backup to reveal seed phrase, copy to paper add today's timestamp to speed synch
1. Sign message using first address in Mycelium and email to self

MultiBit HD verifies as follows:

1. Use MultiBit HD Restore wallet, select BIP44 option and type in the seedphrase etc
1. After successful synch, unlock and verify first address - seen to be different (see later)
1. Verify the message from Mycelium - all correct
1. Attempt to sign message using the first address from Mycelium (will fail if private key is not known) - all correct
1. Send funds to first address in Mycelium from independent wallet - both Mycelium and MultiBit HD show alert simultaneously for the same amount

I think it is safe to say that MultiBit HD is compatible with Mycelium at this stage.

**Comment by gary-rowe** [comment]
myTREZOR.com (BIP44) verifies as follows:

1. Load seed phrase into device using MultiBit Hardware
1. With device connected visit myTREZOR.com
1. Verify balance
1. Generate fresh seed phrase from MultiBit HD and repeat

MultiBit HD is compatible with myTREZOR.com.

As a side note, throughout the development of MultiBit HD the myTREZOR.com site has been used as a verification mechanism.

**Comment by gary-rowe** [comment]
Blockchain.info (BIP32) verifies as follows:

1. Create a standard MultiBit HD soft wallet (BIP32 account 0 only)
1. Hack into Bitcoinj to get M/0H xpub:
```
walletSummary.getWallet().getActiveKeychain().getKeyByPath(Lists.newArrayList(ChildNumber.ZERO_HARDENED)).serializePubB58(MainNetParams.get())
```
1. Provide the resulting `xpub...` into the Blockchain.info API: `https://blockchain.info/xpub/xpub...`
1. Verify balance

MultiBit HD soft wallets (BIP 32 M/0H) are compatible with Blockchain.info.

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by bitcoin-solutions** [comment]
That is a successful check on all of the 3 types of wallet we have:
+ MBHD soft wallet
+ Trezor hard wallet
+ Trezor soft wallet

against one other BIP32/44 implementation.

Closing.
