### ISSUE TITLE
Change licence to refer to 'Bitcoin Solutions Ltd' rather than 'MultiBit Developers'

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#363]
The licence the user accepts, and on the website, refers to the client fee going to 'MultiBit developers'.
I think we should change it to 'Bitcoin Solutions Ltd' as that is where we were planning for the feestream to go to.

**Comment by gary-rowe** [comment]
Agreed.

**Comment by gary-rowe** [comment]
Made this change and added it to the site as well.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Checked licence appearing in MBHD refers to Bitcoin Solutions Ltd.
Closing.
