### ISSUE TITLE
Wallet dashboard not showing capabilities in all cases

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#364]
In some cases when `WalletManager` loads the wallet the `WalletSummary` does not have `WalletType` set.

**Comment by bitcoin-solutions** [comment]
The wallet type is currently stored as a name value pair in the wallet YAML

It might be better to either:
+ store it as a wallet extension IN the wallet file
+ work it out 'on the fly' when the wallet is loaded from:
   + key structure
   + are private keys present
Or both, in a belt and braces approach

**Comment by bitcoin-solutions** [comment]
I've programmd this up but it still needs a bit more checking yet as it's stateful on the wallet.
It has the side effect though that you cannot determine the wallet type until a user enters a password.

Hence at the moment we cannot filter out the trezor wallets from the list of wallets in the 'Enter Password' screen which is a bit annoying.

It might be worth adding the WalletType back into the wallet yaml (which isn't encrypted) as a hint purely for this purpose. I guess if it is only ever written out from the wallet stored value it is safe enough but it's not terribly clean.

**Comment by gary-rowe** [comment]
Since this is a wallet extension it is probably worth updating the test wallet fixture to provide a representative example for FEST tests. You'll find it stored as a zip in the test resources. 

To update just expose it as a real wallet in the application directory, do the upgrade to add the extension, then re-zip and push.

No problem having the wallet extension as a first check, fallback to YAML, fallback to guess/ask user for wallet words?

**Comment by bitcoin-solutions** [comment]
BACKUP YOUR MBHD USER DIRECTORY BEFORE PULLING THIS
(just in case)

I have made a change so that the walletType is put back into the wallet yaml to enable filtering of the Trezor wallets out of the password credentials screen.

Ready for review and closing

**Comment by bitcoin-solutions** [comment]
Oh - I've still got the FEST wallet to do

**Comment by gary-rowe** [comment]
I'll take on the FEST work.

**Comment by gary-rowe** [comment]
All FEST tests pass.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Tests running clean. Closing.
