### ISSUE TITLE
Cloud backup location not being saved on create new wallet

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#365]
I just created a brand new wallet in a brand new installation of MBHD.
The cloud backup directory was not saved.
Debugging it, in the CreateWalletReportPanelView#handleCreateWallet there is no cloud backup location in the model

Edit: And it is not present in the wallet details cloud backup location (as you would expect)

**Comment by gary-rowe** [comment]
We should extend the FEST tests for "create wallet" scenarios to unlock the wallet and then select Wallet Dashboard and go looking for these gaps. Should be straightforward.

**Comment by bitcoin-solutions** [comment]
You can also see it on the Create wallet report as the 'Backup location created' has a X by it

**Comment by bitcoin-solutions** [comment]
I've put in a fix for both hard and soft wallets to ensure that the cloud backup locations are saved for new wallets.

FEST test is still outstanding but you can review if it works or not. There are different paths for both Trezor hard wallets and soft wallets so you want to check both.

**Comment by gary-rowe** [comment]
I'm thinking the FEST test could just use an extension to the temp directory `cloud-backup` and enter it during the create process. I'm able to knock it up now if you like...

**Comment by gary-rowe** [comment]
Found and fixed a few other bits and bobs from the `ViewEvents` refactoring. Not all FEST tests passing yet.

**Comment by gary-rowe** [comment]
More FEST work for me.

**Comment by bitcoin-solutions** [comment]
I have just updated the zipped wallet test fixture so that it contains a wallet type in the wallet

**Comment by gary-rowe** [comment]
I wrapped up all the `ViewEvents` in the "detect EDT and warn if not" code. All FEST tests passing including a check for the cloud backup during wallet creation.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Just ran all the FEST tests and got these 2 failures:
```

java.lang.AssertionError: <'<html>
  <head>
 SNIP
'> should contain the String:<'Step 1 - Download and install'>
	at org.fest.assertions.Fail.failure(Fail.java:206)
	at org.fest.assertions.Assert.failure(Assert.java:141)
	at org.fest.assertions.StringAssert.contains(StringAssert.java:237)
	at org.multibit.hd.ui.fest.use_cases.sidebar.help.SelectGettingStartedUseCase.execute(SelectGettingStartedUseCase.java:63)
	at org.multibit.hd.ui.fest.requirements.HelpScreenRequirements.verifyUsing(HelpScreenRequirements.java:28)
	at org.multibit.hd.ui.fest.MultiBitHDFestTest.verifyHelpScreen(MultiBitHDFestTest.java:307)
```
and
```

org.fest.swing.exception.ComponentLookupException: Unable to find component using matcher org.fest.swing.core.NameMatcher[name='TREZOR_CREATE_WALLET_CONFIRM_WORD.trezor_display', type=javax.swing.text.JTextComponent, requireShowing=true].
SNIP
org.multibit.hd.ui.fest.use_cases.hardware_wallet.TrezorEnterNextWordUseCase.execute(TrezorEnterNextWordUseCase.java:45)
	at org.multibit.hd.ui.fest.requirements.CreateTrezorHardwareWalletColdStartRequirements.verifyUsing(CreateTrezorHardwareWalletColdStartRequirements.java:65)
	at org.multibit.hd.ui.fest.MultiBitHDFestTest.verifyCreateTrezorHardwareWallet_ColdStart(MultiBitHDFestTest.java:397)
```

**Comment by bitcoin-solutions** [comment]
I'll create a new issue as this is nothing to do with the original post now
