### ISSUE TITLE
MBHD gets confused if you change a password and then enter the old one

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#366]
If you change the password and then enter the OLD password in the password screen MBHD gets confused.
It tries to load the most recent wallet and fails and then tries the rolling backups. If one of these is encrypted with the old password it loads ok.

But then it tries to load the contacts and history and gets confused.

Also, if the contacts db does not load the ScreenViewMap does not get populated and none of the DetailViews appear.

Put into Public beta 1 as it will only occur whilst there is a rolling backup with the old password and the old pasword is entered instead of the new one.

**Comment by bitcoin-solutions** [comment]
It might work better if the contacts/payment/history are loaded before the wallet because that would fail fast if the wrong password was used (and hence not load a previous rolling backup)

**Comment by bitcoin-solutions** [comment]
I've moved this into beta 5 as it's quite annoying when it happens

**Comment by bitcoin-solutions** [comment]
The CredentialsWizard Model now loads the History before the wallet. If the user has entered an incorrect password (even a previous one) it now fails fast and the user is told on the display. Earlier rolling backups are not looked at.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working (checked logs to see attempt at History load).

Closing.
