### ISSUE TITLE
Align HD account nomenclature in line with myTrezor.com, Mycelium

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#367]
This morning I created a Mycelium HD wallet and then loaded the seed onto MBHD.
It works fine as long as the seed is loaded with 'What created these wallet words?' as Trezor BIP44

To make things a bit clearer I think we should change the answers of

What created these wallet words ?
to:

MultiBit HD (BIP32)
Trezor device, Mycelium (BIP44)

Of course we won't be able to list ALL compatible wallets but Mycelium is a biggie.

Also, in our Wallet capabilities we describe our compatibility as being:

BIP 44 m/44h/0h/0h (account 0 only) 
to:
BIP 44 m/44h/0h/0h (Account 1 only)

Note the case change
It is a seemingly minor change but that will mean that all of myTrezor.com, Mycelium and MBHD are describing their compatibility identically. 
i.e. "oh they all use 'Account 1' HD wallets'

**Comment by gary-rowe** [comment]
Agreed. We can get this into Beta 5 easily enough.

**Comment by bitcoin-solutions** [comment]
I've done the changes to the languages.properties locally but haven't pushed them yet.
(Still checking the WalletType wallet changes I have locally)

**Comment by bitcoin-solutions** [comment]
As #364 is now pushed this is:
Awaiting review and closing

**Comment by gary-rowe** [comment]
![screen shot 2015-01-20 at 19 56 55](https://cloud.githubusercontent.com/assets/342133/5824792/8db31440-a0de-11e4-9bae-33f2e64dd2b8.png)

All good. Closing.
