### ISSUE TITLE
Trezor soft wallet loaded from seed not roundtripping ok

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#368]
With a Trezor soft wallet that I created from seed I am seeing the error:
```
2015-01-20 13:20:37,042] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - Loaded the encrypted wallet bytes with length: 62048 
[2015-01-20 13:20:37,579] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - Successfully decrypted wallet bytes, length is now: 62042 
KeyChainGroup#fromProtobufEncrypted There are 603 keys.
[2015-01-20 13:20:38,119] ERROR [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - WalletManager error: java.lang.IllegalArgumentException No key found for absolute path M/44H/0H/0/0. ! java.lang.IllegalArgumentException: No key found for absolute path M/44H/0H/0/0.
! at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:94) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:761) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:756) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.KeyChainGroup.createCurrentKeysMap(KeyChainGroup.java:828) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.KeyChainGroup.fromProtobufEncrypted(KeyChainGroup.java:723) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:418) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.multibit.hd.core.managers.WalletManager.loadWalletFromFile(WalletManager.java:790) [classes/:na]
! at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:832) [classes/:na]
! at org.multibit.hd.core.managers.WalletManager.openWalletFromWalletId(WalletManager.java:239) [classes/:na]
! at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.checkPasswordAndLoadWallet(CredentialsWizardModel.java:744) [classes/:na]
! 
```

**Comment by bitcoin-solutions** [comment]
Also seen the error (slightly different path):
KeyChainGroup#fromProtobufEncrypted There are 603 keys.
[2015-01-21 12:23:16,872] ERROR [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - WalletManager error: java.lang.IllegalArgumentException No key found for absolute path M/44H/0H/1/0. ! java.lang.IllegalArgumentException: No key found for absolute path M/44H/0H/1/0.

The path for trezors should start with :+1:  M/44h/0h/0h

**Comment by bitcoin-solutions** [comment]
I have pushed some changes (to both multi bit-hd and bitcoinj-alice) to tighten up on the HD key structures for Trezor soft wallets.

If you replicate with a restore a Mycelium (BIP44) wallet and then try:
+ requesting bitcoin
+ sending wallet
+ roundtripping
it should all now work.
Also improved the unit tests to include creation of new keys and extra round tripping

Awaiting review and closing

**Comment by gary-rowe** [comment]
The wallet restore worked fine. I saw the correct initial balance as shown on Mycelium.

I requested bitcoin through MBHD and that worked no problem, except that the address did not correspond to any Mycelium address. While waiting for the confirm, I sent bitcoin to Mycelium and that appeared on both wallets immediately. However, I still can see no sign of the MBHD receive on Mycelium. 

I think this needs more attention.

**Comment by bitcoin-solutions** [comment]
A bit more Mycelium testing.
Test environment:
+ Mycelium generated wallet. 
+ Restore wallet words in MBHD, using BIP44 restore format.

Test 1: Create request in MBHD. Send to bitcoin address using another wallet.
Result: Address was 1FmoSx3SmhAQDK2AAzsgc4XhfE9LhqVvgP. Seen in both MBHD and Mycelium ok. Success.

Test 2: Copy current Mycelium receive address. Pay using Schildbach wallet on phone. See payment in Mycelium. See payment in MBHD. Success. 

Test 3. Send from Mycelium clone in MBHD. Change address : 1LefMibSz5kWBxb3GhgUMGcYx4PjKdNZZt . Saw the send in MBHD ok. Did not see send payment or change in Mycelium. Fail.

Test 4. Send from Mycelium. See transaction in Mycelium and MBHD. Success.

I then waited until all the tx confirmed to compare the wallet balances (to see if the change in 3 was being seen in both wallets).

After everything confirmed there was a balance of 0.5 mBTC lower in Mycelium rather than the MBHD clone. It's the change output which appears in MBHD but not Mycelium.

https://blockchain.info/address/1LefMibSz5kWBxb3GhgUMGcYx4PjKdNZZt

**Comment by bitcoin-solutions** [comment]
Wallet structure in MBHD:
`
  addr:1Feroo9ci3p5XfAK1mk6ZFyX8UgHvb23ZK  hash160:a0baba6b5323aab4accb609c7bf846cbf3acf517  (M/44H/0H/0H/0/0)
  addr:13whzyfrBBNjzFndUdSeUSkUWRKZHryJf2  hash160:2048f0312fc92dfe716c1944deef9d3a8df6305a  (M/44H/0H/0H/0/1)
  addr:1H6FYbKDKP7WHYWEjFdMNHh1nCwSXBqPAt  hash160:b0803bcfcb128ff76b12932a48afbce3794c6f80  (M/44H/0H/0H/0/2)
  addr:1MCVPq22b2aAmBc6fz6UJ87hodnFmg8zx5  hash160:dd8ecb03bd977903c198e9a2758a79def8b60db4  (M/44H/0H/0H/0/3)
  addr:1Gsnv8ZgAYhFSmLM1QZ1zH47y4hVyF7ZyN  hash160:ae25037d13f6ee3c0753544e893eeed169e585e5  (M/44H/0H/0H/0/4)
  addr:1FmoSx3SmhAQDK2AAzsgc4XhfE9LhqVvgP  hash160:a20ad5eb915ff2b813918be883c9ea697e3f47d9  (M/44H/0H/0H/0/5)
  addr:14bJmz8QP1F5YRKd53xA5LD93gED1LCHuJ  hash160:27655bbeaa97a144aa93d8bb03a583a11416ca6d  (M/44H/0H/0H/0/6)
  addr:1A4i1CDdaBrtK5zbLyUtt1L5tnT6KLvhFY  hash160:636c9b98be55262b6f272daad534545a42b7de3a  (M/44H/0H/0H/0/7)
  addr:1Q8gcu7KGkCYsJuR3PvpLJyAxpRCzEV58K  hash160:fdbee08201117fed7f38974d1f45b64e637b9b70  (M/44H/0H/0H/1/0)
  addr:14WE17nNzuwqvwy8dEza6k7uvRjLLrgXAX  hash160:266f4b35262df9b699f8babf50ac16eb315841de  (M/44H/0H/0H/1/1)
  addr:19AeRn7KN5eBbp1V9sgeSD3vRB7MVgCb1m  hash160:5993fe19d2ada0632a4223412bd8650c52340a5c  (M/44H/0H/0H/1/2)
  addr:1L1zSgxXyxpKA4tZXxMD65PDZUek2QCKoE  hash160:d09a573fffbe37a346410043e3554e832bd0dc10  (M/44H/0H/0H/1/3)
  addr:1HEqdq7P7vdeabFWs4jaiuRziPfJnxnN2X  hash160:b22004bbbe5d4412742bb17e285fb03422914bdc  (M/44H/0H/0H/1/4)
  addr:17Q6TM9EuBbSBgjZRhCDtcajBdWMbgKnFQ  hash160:462edff3c8f8ee077927132bc123df27618cfc53  (M/44H/0H/0H/1/5)
  addr:18Nr3mehW17FB9XEfDYsyFekd92VGYY6ae  hash160:50ea8f06367c695557d9fb3002721b87468efbb8  (M/44H/0H/0H/1/6)
  addr:1Lhxx1sAa6Lc8NNzqnRzoU4js7kxGJ3QXf  hash160:d829bb5a4e2483faf20bee6f7891338e6218d6b3  (M/44H/0H/0H/1/7)
  addr:1M6wwE6Vs9v7KwiE8qBZpk3QRDSNb3H2ru  hash160:dc8273ee20a1254679f2109ad19cfa6fee50c2d8  (M/44H/0H/0H/1/8)
  addr:1LefMibSz5kWBxb3GhgUMGcYx4PjKdNZZt  hash160:d789cca8b75d42c3c89ae9e84da5fcdda49e93c7  (M/44H/0H/0H/1/9)

Note that it is the last change address missing in Mycelium. Also in Mycelium it (on the accounts page) stated there were 16 private keys. These will be up to M/44H/0H/0H/x/8

To force the creation of M/44H/0H/0H/x/9 I created a new receive address in mycelium and sent some bitcoin to it. It now states there are 17 private keys

**Comment by gary-rowe** [comment]
Good work, Jim.

So we need to add a note to the site help to ensure that people know that if their balances aren't matched that they should ensure the Mycelium key count display matches... what in MBHD? We don't should how many keys have been used on the dashboard.

**Comment by bitcoin-solutions** [comment]
I don't think users can really be expected to work this out.
It needs us and the Mycelium devs to ensure our look ahead strategies work harmoniously.
(And any other HD compatible wallets).

We don't really want to put geeky 'number of private keys' on our UI.

Getting all the HD wallets to work harmoniously is the interoperability testing which we were expecting.

**Comment by gary-rowe** [comment]
OK, can you drop them a line and refer them to this issue please?

**Comment by bitcoin-solutions** [comment]
ok

**Comment by bitcoin-solutions** [comment]
Sent Jan an email describing this issue.

As we won't resolve the wallet interop before the Beta 5 trezor release I think we should push it into the Public beta 1 release

**Comment by gary-rowe** [comment]
Agreed. Moved into Release 0.1.

**Comment by gary-rowe** [comment]
Release 0.1 seems too far out and this is too large a change for the transition so I'm moving this to Beta 8 for now.

**Comment by jim618** [comment]
I just restored a Mycelium wallet from my wallet words and cross checked the transactions/ addresses between:
1) The MBHD wallet
2) Mycelium
3) https://dcpos.github.io/bip39/

All the Mycelium addresses/ transactions appear in the MBHD wallet. All the receive addresses match between MBHD and the dcpos site for the wallet words used.

I don't think there is anything for us to do on this issue so propose we close it.

@gary-rowe Suggest you do the same for a Mycelium wallet from your phone. If you can reproduce the same result then we should close it.

**Comment by gary-rowe** [comment]
Verified Mycelium can be restored and that funds can be transferred to it.

Closing.
