### ISSUE TITLE
Ensure position of change (and client fee) outputs are randomised in transactions

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#370]
I don't think we are randomising the position of the client fee when it is added.
Also check the regular change output is always randomised.

(There is a boolean in SendRequest to do this)

This is for general privacy concerns

**Comment by gary-rowe** [comment]
This could be part of the larger "verify what comes back from Trezor was what was asked for" test as well to act as an extra check for tampering on the wire of messages to the Trezor.

**Comment by bitcoin-solutions** [comment]
Separate issues I think.
This is more to do with the tx construction in MBHD and is for all wallets, hard and soft.

**Comment by gary-rowe** [comment]
Agreed. I'll raise the "verify" as a separate issue.

**Comment by bitcoin-solutions** [comment]
Added in a tx.shuffleOutputs just before the sign is performed for both regular and Trezor tx.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Code reviewed and verified working.

Closing.
