### ISSUE TITLE
Verify signed transaction from Trezor is the same as original

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#371]
We have an opportunity to verify the returned signed transaction from the Trezor to ensure that it contains the same information that we sent. 

This should detect any tampering on the wire during the send process that the user may miss on the Trezor screen. For example, an opportunistic shifted decimal place for a low value: 0.005432 vs 0.0005432 BTC and/or an additional output to an unknown address.

Of course this is no defence against a rooted machine but it closes off a potential attack vector for malware.

**Comment by bitcoin-solutions** [comment]
It's also a check that the Trezor itself has been tampered with / is malicious

**Comment by bitcoin-solutions** [comment]
I've added code and a test into multibit-hardware (TransactionUtils#checkEssentiallyEqual) to check for when two tx are 'essentially the same'. Then this code is used in the SendBitcoinWizardModel as an extra check.

I've checked it does not break things but you should code review SendBitcoinWizardModel as there is no automated test for a malicious Trezor changing the signed tx.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Code reviewed in MultiBit HD and Hardware and the code looks thorough. I made a small formatting change to improve clarity but otherwise it's all good.

Closing.
