### ISSUE TITLE
Help isn't legible in dark theme

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#372]
The CSS for the help is not legible in dark theme.
The font colour is still black on a dark grey background.

**Comment by bitcoin-solutions** [comment]
Help colors now match sidebar colors. Also made links bold as they were a bit wishy washy in boostrap theme.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Colour scheme works well in dark conditions.

Closing.
