### ISSUE TITLE
Show an alert if Trezor firmware is not on a known list

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#373]
Up for discussion. Should we maintain a list of known Trezor firmware and show an alert if an altered or unknown firmware is presented?

Pros:
* we can alert users to potential tampering/replacement
* it reinforces SatoshiLabs firmware
* it strongly encourages clones not to mess with the firmware
* we can encourage updates

Cons:
* we are locked into the Trezor release cycle (they update firmware, we update MultiBit HD)
* combinatorial explosion as clones arrive and need their firmware signatures updated

**Comment by bitcoin-solutions** [comment]
I think this is out of scope of MBHD
Trezor / clone manufacturers should own this.

**Comment by gary-rowe** [comment]
Agreed. We're opening up a maintenance nightmare for ourselves trying to support this.
