### ISSUE TITLE
Did a send, saw BitcoinSendEvent in log, tx not seen on UI

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#375]
I just saw the following (twice in close succession):
1) Send a transaction
2) See on the send report panel that it is sent, but no 'sent by 2+ peers.
3) There is a BitcoinSendEvent in the log indicating it was sent correctly
4) Tx is not shown in payments panel, nor on the Send/Request screen

I had to do a Repair Wallet to see the tx.

**Comment by gary-rowe** [comment]
Very likely to be a `SwingUtilities` wrapping `ViewEvents` scenario.

**Comment by gary-rowe** [comment]
The panel view components were not updating on the EDT so there is a chance that the UI would not reflect the change. Got a screen shot during the send:

![screen shot 2015-01-25 at 21 36 57](https://cloud.githubusercontent.com/assets/342133/5893410/b953bb36-a4da-11e4-88f4-6a46cd55921a.png)

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
I have also put in a handler for onTransactionCreated so that there is extra, earlier update that I'll push after checking the FEST tests.
Closing
