### ISSUE TITLE
Java icon is showing on Windows version

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#376]
The Java coffe cup is being shown as the application icon on Windows.
Change to MBHD icon

**Comment by bitcoin-solutions** [comment]
Added code into Images and MainView to setIconImage directly for Windows.
The icon is similar to the trademarked 32x32 logo but with the HD in the icon removed.
It's only small anyhow.

I will review this by creating an installer for Windows directly.

**Comment by gary-rowe** [comment]
Hmm, was the 128px version used anywhere else? For example, Windows uses a variety of icon sizes in different contexts (taskbar switcher, tray icon, start menu etc) we need to ensure that the "HD" icon is the one used everywhere on our products.

**Comment by bitcoin-solutions** [comment]
The trade marked icons aren't in the multibit-hd resources
Also the different, trademarked, ones are in an ico file which Java cannot easily read.
For a 16x16 icon it seemed easier just to use a generic version of our trademarked one.

**Comment by bitcoin-solutions** [comment]
Now seeing MBHD icon rather than Java coffee cup on Windows.
Closing
