### ISSUE TITLE
Wallet tmp files being left on Windows

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#377]
In the wallet directory there are wallet tmp files being left behind on Windows.
theses should be secure deleted

**Comment by gary-rowe** [comment]
This may be caused by not using the solution suggested in this closed JVM bug: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4171239. We may need to use the NIO approach rather than Guava's `createTempDir`. Alternatively we could add a `ShutdownHook` (which is pretty much what `deleteOnExit` does anyway) and review any change in behaviour.

**Comment by bitcoin-solutions** [comment]
There are also zip backups and rolling backups present so it looks like the SecureDelete isn't clearing out the files correctly

**Comment by bitcoin-solutions** [comment]
I've checked with a hex editor that the file contents have been overwritten, it is just the file itself has not been deleted by the OS

**Comment by gary-rowe** [comment]
Consider using NIO approach (you'll need to change the import I expect):
Line 84:
```
      // Ensure we push this out to the file system
      buffer.force();

      // Use JDK7 NIO Files to delete the file since it offers the following benefits:
      // * best chance at an atomic operation
      // * relies on native code
      // * works on Windows
      boolean deleteSuccess = Files.deleteIfExists(file.toPath());
```

It might be worth going the whole way here and updating `createTemporaryDirectory` to use the NIO approach as well:
Line 187 (after mods):
```
    // Use JDK7 NIO Files for a more secure operation than Guava
    File temporaryDirectory = Files.createTempDirectory("mbhd").toFile();

```

**Comment by bitcoin-solutions** [comment]
Reinstated slowSecureDelete from MB Classic for Windows operation.
multibit-hd.jar built, copied to Windows machine and checked.

Closing.
