### ISSUE TITLE
No logs on Windows

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#378]
There are no log files on Windows MBHD (possibly other platforms as well)

**Comment by gary-rowe** [comment]
I've added logging configuration that recognises the user's application directory and places all logs in a `logs` directory as follows:

* all logs are in UTC timezone
* all `org.multibit.*` packages are logged at `DEBUG` the rest at `WARN`
* `/logs/multibit-hd.log` is always today's log
* `/logs/multibit-hd-2000-01-01.1.log.gz` is the first archive of logs for Jan 1st 2000

There's a bit more to add so it's not ready yet.

**Comment by gary-rowe** [comment]
Logging is now configured. Note that `logback.xml` is only used during testing to reduce the logging output volume. At runtime logging is configured through the `LoggingFactory` and allows for external adjustment if required as well as ensuring that the application directory is supported across platforms.

Verify correct operation by running as normal and observing the creation of the new log file. Run a unit test and observe console output but no file logging.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Seeing logs/multibit-hd.log in user data directory (on Windows)
Looks good.
Closing

**Comment by bitcoin-solutions** [comment]
Also seeing logs on Mac as expected

**Comment by gary-rowe** [comment]
Just keep an eye on them to make sure they roll over at midnight. If not just re-open this issue.
