### ISSUE TITLE
Update POM to use MultiBit Hardware 0.1.0

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#381]
I've just released MultiBit Hardware 0.1.0 into the [staging repository](https://github.com/bitcoin-solutions/mbhd-maven/tree/master/releases/org/multibit/hd/hardware). 

We should update MultiBit HD to use the release version in preparation for the 0.0.5 release and run the complete FEST tests.

**Comment by gary-rowe** [comment]
Added the new 0.1.0 JAR and ran all FEST tests successfully.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Checked POM, built and ran tests.
Closing
