### ISSUE TITLE
Minimise time taken to show UI at startup

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#382]
The current startup time for Beta 5 has room for improvement. In order to provide a pleasing UX we should aim to present the user with a UI response as soon as possible after startup. 

It's OK if the user cannot interact with the application during the startup phase, e.g. splash screen with progress bar. This issue just covers providing reassurance that something is happening in the dead time between clicking a Bitcoin URI/icon and seeing a response.

**Comment by gary-rowe** [comment]
(From Jim) Areas to look at are 

* lazy loading stuff at startup.
* connecting to Bitcoin network.
* making some of the wizard transitions/ handovers snappier

**Comment by bitcoin-solutions** [comment]
Other things to look at are:
+ starting the exchange lookup early. If there is no exchange rate on a send or receive the user never gets a fiat equivalent in the payments db (there is no backfilling).

**Comment by jim618** [comment]
@gary-rowe 
I think it might be better to bump this to Beta 8.
Rearranging the order things start, lazy loading etc could easily subtlely break things so it would be better to do it early in an iteration rather than right at the end.

**Comment by gary-rowe** [comment]
Agreed. It's annoying waiting so long for it to start up so it needs to be fixed.

**Comment by jim618** [comment]
Lazy loading code tip from Gary:
Actually, on the subject of lazy loading, it might be worth looking at the Guava cache builder: https://code.google.com/p/guava-libraries/wiki/CachesExplained - I've used it many times for in-memory lazy loading and it works very well. The wizard hide code could evict the entry from the cache.

**Comment by jim618** [comment]
Some early results of profiling the start up of MBHD.(just starting it up and logging in):

![screen shot 2015-03-03 at 16 01 11](https://cloud.githubusercontent.com/assets/919427/6466357/e26b1b26-c1be-11e4-9adc-7dc47772bbce.png)

![screen shot 2015-03-03 at 16 01 20](https://cloud.githubusercontent.com/assets/919427/6466364/e9660c60-c1be-11e4-8028-5fcab7885f74.png)

File IO, byte copying and SCrypt all appear.
The Uniterruptiby waiting (there's one in the MBHD) if they are blocking would be good candidates to look at.

Creation of Swing panels etc don't seem to appear (which surprises me a little).

**Comment by gary-rowe** [comment]
I did a quick check on the `bip70` branch to see how long the JVM takes to start up and present a splash screen. That appeared in under 2s on a slow machine so as a stop gap we could present one with a progress bar while we work towards a fully lazily loaded UI.

**Comment by jim618** [comment]
Any "get the Install4J to display a" splash screen will also appear when a bitcoin URI gets clicked and a second MBHD starts up, momentarily, in order to pass the Bitcoin URI over our private port.

This may or may not look ok but I would expect it would be a bit surprising

**Comment by gary-rowe** [comment]
Ah, no. The bip70 code waits until after the `ExternalDataListeningService` has decided to startup or handover so no Install4j interference. This is purely inside `MultiBitHD` - I've marked it with a TODO.

**Comment by jim618** [comment]
I have tweaked the MultiBitHD start up so that the two seconds initialisation for the HardwareWalletService is 'folded into' useful operations where possible.

Interim review required but leave the issue open - bump it back to 'no label' if acceptable.

**Comment by jim618** [comment]
On my 2008ish Mac Book Pro if I substitute the multibit-hd.jar into the multibit app (installed from the installer) it opens now in 8 seconds. This is after opening it a couple of times so that the Mac can do all of its optimisation etc. The quickest I saw before was 9 seconds so it is a tad quicker.

**Comment by gary-rowe** [comment]
If we use Microsoft Word as a comparison then we should expect a splash screen after 2s and full operation in 8s. Looks like we're very close to that expectation.

If you [look at this example](http://docs.oracle.com/javase/tutorial/uiswing/misc/splashscreen.html) then JDK6+ comes with a built in splash screen. 

It should be straightforward to grab the trademark logo (or just use MultiBit HD in Corben); center it in a 100x100 white PNG with black border and adjust `MultiBitHD` to show it after socket negotiation. We'd need to ensure the `MANIFEST.MF` file contained a suitable entry (detailed on that example page).

**Comment by jim618** [comment]
Yeah, let's put in a small, static splash screen (after socket negotiation). 
The MBHD icon will be fine, as that is localisation independent.

We can tweak things later on but that will give users feedback as to what is happening.

**Comment by gary-rowe** [comment]
This does mean that we'll be adding the "trademark logo" into the JAR resources. Still, it's available via the website with a mere click so it's hardly a concern.

**Comment by gary-rowe** [comment]
If you're OK with that I'll knock something up tonight to cover it.

**Comment by gary-rowe** [comment]
Added a splash screen image with same aspect ratio as initial UI. 

After testing with the built-in SplashScreen function the rendering occurred speedily but at an uncontrolled position in the startup sequence. It was not possible to delay the rendering until after the server socket was established when the UI was guaranteed to be shown. Consequently this would have lead to a "glitchy" UX whenever a Bitcoin URI or payment request file was clicked.

A Swing-based splash screen fared little better giving poor rendering during the initial image load. In the end an AWT implementation gave the fastest and cleanest rendering. Overall it is not possible for us to know in advance of the JVM compiling the JAR whether we will need a splash screen so this is the best we can reasonably do.

Ready for review and close.

**Comment by jim618** [comment]
On my Mac, on battery power, it is taking 10 seconds for MBHD to start and I see the splash screen at 7 seconds. It is a nice splash screen and helps keep the user busy but it would be nicer if it was earlier.
(This is inserting a multibit-hd.jar into a previously installed MultiBit HD.app so it will be pretty close to what the user sees).

**Comment by jim618** [comment]
Note that because the splashscreen does not use Swing, it can be presented before the look-and-feel loading and tweaks. Also, you could do a quick and dirty check to see if 'bitcoin:' appears in any of the args - if there were then it's a Bitcoin URI invocation so no splash screen is necessary.
That might pull it forward in time a bit.

**Comment by gary-rowe** [comment]
OK, I've done some more optimisation based on the AWT advantage. The `ExternalDataListeningService` now starts at the earliest possible time and the splash screen only shows if it successfully obtains the server socket. 

If a BitcoinURI is present on the command line and another instance is running the startup to shutdown time is 1500ms with most time being spent in the BitcoinURI parsing process. Without a BitcoinURI on the command line and another instance running startup to shutdown takes about 60ms.

Standard startup, in the IDE, is 1s to splash and 7s to credentials on a slow Mac.

**Comment by jim618** [comment]
Splash screen appearing earlier and usefully 'fills the space' whilst MBHD starts up.
Closing.

**Comment by gary-rowe** [comment]
Thanks, Jim. One useful observation is that a scheduled executor service takes about 600ms to initialise and so should be deferred whenever possible. However, this can have unwanted side effects due to lazy initialisation code so there is a balance to be drawn.

A normal executor service is extremely quick at just a couple of milliseconds so should be the favoured choice if one can be made.

**Comment by jim618** [comment]
Good to know.
I think the threshold for speed optimisation is about 100ms. Anything over that is worth looking at, anything else is not worth looking at at the moment.
