### ISSUE TITLE
Corben font on Windows is not rendering smoothly

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#384]
The Corben font on Windows looks a little jagged and needs some attention. 

A related issue is #358 dealing with body fonts.

**Comment by gary-rowe** [comment]
This appears to be a known anti-aliasing issue. See http://stackoverflow.com/questions/16304254/differences-in-jlabel-when-loading-ttf-font-between-windows-and-linux for details.

**Comment by gary-rowe** [comment]
As always this is trickier than it first appears. Using
```java
System.setProperty("awt.useSystemAAFontSettings","gasp");
System.setProperty("swing.aatext", "true");
```
Provides a good combination of anti-aliasing of the main title whilst retaining OK rendering of the smaller body font. 

Before:
![before](https://cloud.githubusercontent.com/assets/342133/6256661/c410e85c-b7b1-11e4-816f-decd04f00054.png)

After
![after](https://cloud.githubusercontent.com/assets/342133/6256659/b73993e0-b7b1-11e4-9afe-d142fae546ca.png)

However, the overall effect is worse than just leaving it out. An ideal fix would replace the title `JLabel` with a custom label with its `paint()` method overridden to use. See http://www.java2s.com/Code/Java/Swing-Components/LabelwithlargefontandANTIALIASpaint.htm for an example.

Closing.

**Comment by gary-rowe** [comment]
This needs to be re-opened and addressed now that we have more time to look at it.

**Comment by jim618** [comment]
The code on the page:
. See http://www.java2s.com/Code/Java/Swing-Components/LabelwithlargefontandANTIALIASpaint.htm for an example.

does not take into account line wrapping so probably wouldn't work with our titles

**Comment by gary-rowe** [comment]
Here's the outcome using the SwingUtilities2 approach:
![aa-on-swing2](https://cloud.githubusercontent.com/assets/342133/8635300/3cfb6ec6-2815-11e5-925f-749961e50f44.png)

Reasonable antialiasing on a standard LCD screen, without interfering with the body text as before. Also looks fine on OS X.

Ready for review and close.

**Comment by jim618** [comment]
Did this go on the brit-refactor branch ?
I don't see anything new on develop

**Comment by jim618** [comment]
I see it did

**Comment by gary-rowe** [comment]
Yeah, as per earlier email all my edits and updates are against the
brit-refactor branch now since it is very likely to be merged today
(assuming you're good with it).

I've just pushed some changes to the BritServer that revert the live URL
back to the correct https://multibit.org/brit value. These are on its
brit-refactor branch too. There is a section in the README there that
details the steps to verify the BRIT exchange against MultiBit HD.

I'll push the latest develop-SNAPSHOT to the staging repo to assist your
testing efforts, but you might find you want to build things locally just
to be sure.

I'm out and about this afternoon, but if you encounter problems give me a
ring and I'll do what I can to guide you through it.
I have an hour or so now if it's convenient for you.

**Comment by jim618** [comment]
This looks a lot better (on my Mac).
Closing.

**Comment by gary-rowe** [comment]
Can you verify it's working OK on your Windows test machine before closing this off?

**Comment by jim618** [comment]
ok

**Comment by jim618** [comment]
The antialiasing works fine on the little Windows test machine.
Closing
