### ISSUE TITLE
Paste All in Verify Message tool doesn't work on Windows

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#387]
When verifying a Bitcoin signed message, the expected behaviour is to copy the entire ASCII armor and use Paste All to automatically fill in all 3 fields. This works correctly on Mac and Linux but isn't working on Windows 8.1, and possibly other variants.

**Comment by gary-rowe** [comment]
Earlier detection was platform dependent leading to `\n` being treated as `\r\n` and incomplete parsing.

To verify, on Windows and Mac copy a [sample Bitcoin signed message](https://multibit.org/releases/multibit-hd/multibit-hd-0.0.5beta/release.txt) to the clipboard and use Tools | Verify Message | Paste All to enter the data. Click Verify Message for confirmation. 

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Checked that Copy All of a signed message, and then a subsequent Paste all into "Tools | Verify message' works as expected.

Closing.
