### ISSUE TITLE
Clicking bitcoin link in browser on Windows does not launch MultiBit HD

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#388]
The installer needs to set some registry values to configure the Bitcoin protocol handler. In general this requires the following registry script to be run post-install:

See http://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx for more details

As a workaround do the following:

1) Create a new file `bitcoin.reg` and copy-paste the following:
```
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\bitcoin]
@="URL:Bitcoin Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\bitcoin\DefaultIcon]
@="multibit-hd.exe,1"
[HKEY_CLASSES_ROOT\bitcoin\shell]
[HKEY_CLASSES_ROOT\bitcoin\shell\open]
[HKEY_CLASSES_ROOT\bitcoin\shell\open\command]
@="\"C:\\Program Files\\multibit-hd\\multibit-hd.exe\" \"%1\""
```
2) Double-click it in Windows to execute the contents and go through the security checks
3) On completion, visit a Bitcoin link and click it. The browser should prompt for an application
4) Locate the `multibit-hd.exe` file (usually under `C:\Program Files\multibit-hd\multibit-hd.exe`)
5) Click OK and wait while MultiBit HD starts
6) Open the wallet you want to use for dealing with the payment from the link
7) After unlocking an alert will appear with the link details, follow the instructions from there.

**Comment by bitcoin-solutions** [comment]
Updated the 0.0.6beta installer to cover this. Verified correct operation in Windows 8.1 using Chrome and IE but Firefox requires special file manipulation [currently described in the Linux install guide](https://beta.multibit.org/en/help/hd0.1/how-to-install-linux.html). This can't really be automated and is best treated as a limitation of Firefox at present.

To verify, perform an install on Windows then:
* use `regedit.exe` and examine the `HKEY_CLASSES_ROOT` values are in line with the example given above
* observe desktop and start menu shortcuts point to `C:Program Files\MultiBit HD\multibit-hd.exe`

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Navigated to multibit.org in Chrome. Clicked on the donation link. MBHD started up ok, prompted for credentials ok. saw alert with request for payment ok.

Tried same with Internet Exploer 10. Same result.

Closing.
