### ISSUE TITLE
Trezor unlock screen requires more info about its purpose

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#391]
The Trezor unlock screen is a little bare and doesn't tell the user why it needs to do this (encrypting your local wallet).

**Comment by gary-rowe** [comment]
![screen shot 2015-02-06 at 20 55 50](https://cloud.githubusercontent.com/assets/342133/6087381/913a1f84-ae42-11e4-8536-59703df96ff3.png)

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Confirmed works fine.
Closing.
