### ISSUE TITLE
Remove the PIN buttons pressed from logs

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#392]
Whilst not showing the PIN (which is not known on the desktop) the logging for:
o.m.h.u.v.w.c.CredentialsEnterPinPanelView

indicates the PIN length and repeats so should be removed.

**Comment by gary-rowe** [comment]
Quick fix so I thought I'd save you some time.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Checked PIN length does not appear in logs.
Closing
