### ISSUE TITLE
Selecting 24 word seed phrase on Trezor results in 12 words

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#393]
User feedback:
> I used a blank Trezor, got the set up going and selected I wanted a 24 word seed from the menu but it ended up only giving me a 12 word seed.
> OS X 10.9.5, Trezor firmware 1.3.0

Looks like the entropy size isn't getting sent to the Trezor properly. The FEST tests should have picked this up.

**Comment by bitcoin-solutions** [comment]
Could be a fault in the Trezor emulator we use in the FEST tests

**Comment by gary-rowe** [comment]
Turned out to be some duplicated code. Simple fix.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Wiped a trezor and created a wallet with 24 words successfully.
Closing
