### ISSUE TITLE
Startup of MBHD is a bit slow compared to MB Classic

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#395]
The start up sequence for MBHD is slower than MB Classic. It should be comparable in speed as it is basically doing the same.

Areas to look at for improvements:
+ lazy loading stuff at startup.
+ connecting to Bitcoin network.
+ making some of the wizard transitions/ handovers snappier

**Comment by gary-rowe** [comment]
This is a duplicate of #382 so closing.
