### ISSUE TITLE
Add support for Trezor GetAddress display when requesting bitcoin in a "hard" wallet

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#398]
The Trezor 1.3.0 firmware provides an on-screen copy of an address along with a scannable QR code as part of the generated address for a given path. 

To avoid MITM attacks when requesting bitcoin, a GetAddress message could be sent to an attached Trezor device that would show the same address as on the desktop. When the user clicks the Trezor "confirm" button the subsequent ADDRESS message could be used to click Finish giving a slightly enhanced UX.

**Comment by bitcoin-solutions** [comment]
I think this might be more confusing than useful as the address shown on the Trezor will just be the Bitcoin address without the encoded amount and label.
If the user scans the QR code from the Trezor they will see one behaviour, but if they scan from the Request screen, they'll get another.

**Comment by gary-rowe** [comment]
Agreed. It looks pretty, but consistency is more important.

Closing.
