### ISSUE TITLE
Need to trap PIN message from Trezor after long period of inactivity

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#399]
The Empty Wallet and Send Bitcoin wizards do not respond correctly to PIN requests from the Trezor after an extended period of inactivity - such as recovery from hibernate/sleep.

**Comment by gary-rowe** [comment]
First draft of the PIN support in the Send Bitcoin wizard is ready for interim review. To verify do the following:

1. Load a hard wallet with funds and unlock it
1. Detach and reattach the Trezor to reset the session (ignore the alert)
1. Go through the usual Send process and observe the PIN entry screen
1. Try various options of cancelling and observe correct reset on device and MBHD
1. Progress to an actual send to prove signing still works

Ready for interim review.

**Comment by jim618** [comment]
Yes that all works smoothly. Tested on Send Bitcoin ok.

**Comment by gary-rowe** [comment]
Added the same support into Empty Wallet wizard. Use the same process as before to verify.

Ready for review and close.

**Comment by jim618** [comment]
Yup that all works smoothly. Empty wallet tx sent (with Trezor 1.3.3 firmware). Cancels on the Trezor all do what you expect (Go to report page - show cancelled signing).

closing.
