### ISSUE TITLE
Provide an "infinite scroll" approach when tables become too lengthy

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#401]
Some users have a great many transactions in a single wallet, others have large contact databases or flood the history over time. In each case we need to limit the amount of information held in memory and bring it in in progressive batches.

**Comment by bitcoin-solutions** [comment]
suggest we bump this to Release 0.2

**Comment by bitcoin-solutions** [comment]
Thinking about it a bit I don't think we can 'batch' the wallet as it has to be in memory so that it can be updated as tx come in from the Bitcoin network.
This is going to be the largest object in memory so I don't think it is worth spending time on this.

**Comment by jim618** [comment]
I don't think we should do this at this stage.
Closing
