### ISSUE TITLE
Show "Trezor firmware not supported" popover if DEVICE_FAILED is fired

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#402]
MultiBit Hardware will fire `DEVICE_FAILED` containing a valid `Features` if the firmware is not supported. The `MainController` should detect this and react accordingly - typically with a delayed popover similar to the security alerts.

**Comment by gary-rowe** [comment]
This change requires the latest MultiBit Hardware develop-SNAPSHOT.

![screen shot 2015-02-09 at 23 02 03](https://cloud.githubusercontent.com/assets/342133/6117859/b5b9a766-b0af-11e4-9c6a-1bf5121b0147.png)

Added support for security popovers and alert bars for unsupported firmware throughout. The rules are:

* either an alert bar or a popover will be shown once for each `DEVICE_FAILED`
* popovers will be displayed if a wizard is showing on a secure screen (password, PIN etc)
* alert bars will be displayed if no wizard is showing (unlocked wallet)
* alert bars will remain (and stack) until dismissed
* switching between a good and bad device on credentials should be painless

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
It's almost perfect but I managed to confuse it by doing the following:
1) Start up a soft wallet
2) Plug in a 1.2.0 firmware Trezor. Saw alert correctly. Dismissed alert.
3) Unplugged trezor
4) Did a Switch wallet. I then saw a Security alert saying the attached wallet firmware was out of date. But I had just unplugged the trezor.

Other than that it all workes exactly as expected.

**Comment by gary-rowe** [comment]
Ah yes, it's a race condition. Edit `MainController.onSecurityEvent()` to have `Uninterruptibles.sleep...` be 250ms.

**Comment by gary-rowe** [comment]
Ok, pushed the change. Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Nope sorry, it is still the same.
I've checked the MainController has the sleep at line 469 so I am definitely working with your change

**Comment by gary-rowe** [comment]
I'm AFK for significant changes so I'll need you to take this one on. 

Could you remove the Uninterruptibles completely, then in `MainController.onHardwareWalletEvent` look for `SHOW_DEVICE_DETACHED` and add a check for `CoreServices.getApplicationEventService.getLatestsecurityEvent()`, verify it is an `UNSUPPORTED_FIRMWARE` event and if so to remove it through `onSecurityEvent(null)`. 

This will ensure that if the user detaches the device that the security alert will be cleared. If they don't then each secure operation (e.g. enter PIN, password etc) will nag them.

**Comment by bitcoin-solutions** [comment]
Push changes as per your suggestion above. Works fine on my machine.

Awaiting review and closing by @gary-rowe

**Comment by gary-rowe** [comment]
Thanks, Jim. I'll check it tonight.

**Comment by gary-rowe** [comment]
Minor adjustment and verified working.

Closing.
