### ISSUE TITLE
Add Preference for choosing a block explorer 

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#403]
Require a preference setting to allow a choice of block explorers to be made:

* Blockchain.info (default)
* Blockr.io
* Blockexplorer.com
* Blocktrail.com
* Biteasy.com

Clicking the "view in external browser" button will fill in the URL with the given TxID/Address as appropriate.

**Comment by jim618** [comment]
blockexplorer.com does not seem to working when I just tried it so I am dropping it from the list

**Comment by gary-rowe** [comment]
It seems to be working for me, but you're deeper into this issue than me so I'll concede to your judgement. We can always add extras later on.

**Comment by jim618** [comment]
I've coded this up and pushed it.
There is a unit test for the class BlockExplorers but I still need to do a FEST test for the UI changes.

New combo box on Preferences | Appearance to look at !

**Comment by jim618** [comment]
Added FEST test that cycles through the block explorers in the combo box and checks the configuration is updated ok.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Interesting that a tx with 1000sat fee was considered too low by blocktrail and biteasy did not recognise the tx for quite a while. If their policy is to ignore 0-confirmation tx (this had 2 conf) then perhaps we should drop them.

Closing.
