### ISSUE TITLE
On Windows (at least) clicking on a Bitcoin URI does not pass it to a running version of MBHD

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#404]
If you have MBHD running and click on a bitcoin URI link it does not produce an alert.
This is a distinct use case to when MBHD has to start up and indicates the message passing of the Bitcoin URI is not working.

**Comment by gary-rowe** [comment]
This may be a hold over from the Beta 5 installer. I noticed when putting the Beta 6 installer together that the "Allow single instance" check box was selected. The latest Beta 6 has it removed.

**Comment by bitcoin-solutions** [comment]
So perhaps if I uninstall other versions it will fire up an extra instance ok ?
I'll try it

**Comment by bitcoin-solutions** [comment]
I tried uninstalling all copies of MBHD and installing via an installer created yesterday (based on 0.06beta). Clicking on a bitcoin URI in Chrome did NOT propagate into MBHD.

There is nothing in the logs to indicate a bitcoin URI message being passed in

**Comment by gary-rowe** [comment]
If nothing is getting passed in that looks suspiciously like the installer wrapper is preventing multiple instances. 

Looking at the install4j project XML reveals the following in the Launcher section: `singleInstance=true` so should be fixed with a rebuild of the installer.

**Comment by bitcoin-solutions** [comment]
I have updated the installer beta 6 to switch OFF the "Allow only a single running instance o fthe application' and will try rebuilding it.

**Comment by bitcoin-solutions** [comment]
Tested with a rebuilt 0.06beta installer with multiple instances allowed on Win 8 test machine.
Bitcoin URIs create alerts both when MBHD has to start up and when it is already started.
Closing.
