### ISSUE TITLE
Beta 6 FEST tests are not passing

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#405]
Placeholder issue to ensure the FEST tests pass (currently the wallet fixtures are mismatched due to the 1.3.0 firmware).

**Comment by gary-rowe** [comment]
All FEST tests seen to pass on my machine. 

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
Just ran them and saw 1 failure:

```

org.fest.swing.exception.ComponentLookupException: Unable to find component using matcher org.fest.swing.core.NameMatcher[name='TREZOR_CREATE_WALLET_CONFIRM_WORD.trezor_display', type=javax.swing.text.JTextComponent, requireShowing=true].
SNIP
org.multibit.hd.ui.fest.use_cases.hardware_wallet.TrezorEnterNextWordUseCase.execute(TrezorEnterNextWordUseCase.java:45)
	at org.multibit.hd.ui.fest.requirements.CreateTrezorHardwareWalletColdStartRequirements.verifyUsing(CreateTrezorHardwareWalletColdStartRequirements.java:65)
	at org.multibit.hd.ui.fest.MultiBitHDFestTest.verifyCreateTrezorHardwareWallet_ColdStart(MultiBitHDFestTest.java:397)

```

**Comment by bitcoin-solutions** [comment]
I just reran verifyCreateTrezorHardwareWallet_ColdStart() twice and once it ran ok and once it failed.
When it fails it does not run through the Trezor generated words (1st word, 2nd word etc)

**Comment by gary-rowe** [comment]
Can you provide a log showing the message sequence just before it goes wrong? I can't replicate the failure here.

**Comment by bitcoin-solutions** [comment]
I think we can live with this for the 0.0.6beta release

**Comment by gary-rowe** [comment]
Agreed. Beta 6 is go.

Closing.
