### ISSUE TITLE
The gap in time from when a send goes to first peer and when it comes back from others needs filling

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#409]
I think the Send UX needs improving for the time between:

1) Tx is sent to first peer
2) Tx is seen by other nodes.

at the moment there can be a gap of 10 seconds where the user does not know if the tx sent ok or not.

Ideas:
+ Once tx is sent to first peer, show in send confirm, 3rd row, "Waiting for feedback from the Bitcoin network..."
+ Once tx is sent to first peer, show in Send/ Request, send column with status "Waiting" 

Note that we don't update the balance until we see the tx on other peers so that the balance does not normally 'drop precipitously' due to change non-availability. We are filling this 10 second ish gap.

**Comment by jim618** [comment]
I've introduced into the Send Report screen the 'state' of 'Broadcasting your transaction to the Bitcoin network ...'

Once the send tx is constructed and a ping check is performed the user is told that their tx is being broadcasted. Then when the future of the broadcast completed the user is told that their tx is sent.

The tx is added as a pending tx into the wallet when the future completes (this is bitcoinj functionality) so if the tx is not broadcast it isn't added to the wallet (where it would probably cause more trouble than it is worth).

The Empty wallet report form has also been changed.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Looks good since there can be quite a pause while the broadcast is occurring.

Closing.

**Comment by jim618** [comment]
I have reopened this and tweaked the UX slightly.
See what you think.
Now just before I broadcast the tx (after the ping check) I add it to the wallet as pending.
This gives the user the feedback that:
+ the tx is being broadcast and that MBHD is waiting for feedback
+ you see it seen by 1 peer, then 2 peer (at which it is deemed to be actually sent).

This is in both the Send screen and empty wallet.
Try it out and see if you think the feedback is clearer.

**Comment by jim618** [comment]
I've tweaked the Send Report and Empty Wallet pages so that the 'broadcasting' icon is shown until a tx is seen by 2 peers. This is the same algorithm we use for when change is spendable so matches changes in the header.

The header is visible for when the change is NOT spendable so 'dips' we could improve this but it is in the background so I suggest we leave it be for now.

From the users point of view, once the broadcast icon (a megaphone) is replaced by a tick then the tx should be good to go.

**Comment by gary-rowe** [comment]
Verified working and looks good. The megaphone works well as the broadcast icon.

Closing.
