### ISSUE TITLE
Remove extended public key from contacts if we are not yet supporting it

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#410]
If the xpub in the Contacts doesn't do anything we should remove it as it is confusing

**Comment by gary-rowe** [comment]
Agreed. When we're able to support it it'll be trivial to reinstate it on the UI. No need to change the protobufs.

**Comment by bitcoin-solutions** [comment]
I've removed the xpub from the UI (but not the protobuf nor the i18n).

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified absence of xpub field.
