### ISSUE TITLE
Order list of wallets alphabetically

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#411]
If there are more than one wallets available in the password credentials screen, list them alphabetically.

**Comment by gary-rowe** [comment]
Didn't Owen request a most recent first ordering?

**Comment by bitcoin-solutions** [comment]
He might have done, but when you have more than a few it's laborious to read through them all.

**Comment by bitcoin-solutions** [comment]
The list of wallets is now sorted (using the default String comparator). 
It won't be a good (lexical) sort for languages like Chinese but it should be good enough.

Awaiting review and closing

**Comment by gary-rowe** [comment]
This might be relevant: http://docs.oracle.com/javase/tutorial/i18n/text/collationintro.html

**Comment by bitcoin-solutions** [comment]
I'll rework it with a language based Collator

**Comment by bitcoin-solutions** [comment]
Added Language based collator to sorting.
You can check with the peche example in your link above and swapping between French and English

Awaiting review and closing.

**Comment by bitcoin-solutions** [comment]
Added unit test CollatorsTest that tests the ordering of:
péché
pêche

In French and English

**Comment by gary-rowe** [comment]
Verified correct ordering using mixed language (English, Russian). The Russian came after the English and was correctly ordered:

![screen shot 2015-02-17 at 20 02 10](https://cloud.githubusercontent.com/assets/342133/6236169/fdb21720-b6df-11e4-9057-25d979ef97c0.png)
