### ISSUE TITLE
Tighten up on syncing

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#412]
The current syncing algorithm errs on the safe side and hence tends to sync back to the last check point more than it has to. See if this can be improved.

**Comment by jim618** [comment]
Whilst working on #440 I have put in a fix for this so I have marked it as awaiting issue. When #440 is done this should be improved.

**Comment by jim618** [comment]
You should now normally see a sync from the last block seen by the wallet and only a sync back to the last checkpoint in 'unusual' circumstances.
This is for both soft and hard wallets.

Awaiting review and closing

**Comment by gary-rowe** [comment]
I'll keep an eye out for unusual sync operations and re-open if any glitches are seen. Sync is fine at present.

Closing.
