### ISSUE TITLE
Mockito is in multibit-hd.jar - required ?

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#413]
There are 3.2 MB of mockito classes in the multibit-hd.jar.
These probably don't need to be in the released jar.

**Comment by gary-rowe** [comment]
Agreed. We should clear out any test scope JARs.

**Comment by bitcoin-solutions** [comment]
I tweaked the pom to make the mockito jar test scope. I think it was the only one that was missed.
The multibit-hd.jar has decreased from 23,833,494 to 22,405,150 bytes. (A 6% decrease). 

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified build of multibit-hd.jar is now about 19Mb. Shade plugin reports no unnecessary JARs being included so it's all good.

Closing.
