### ISSUE TITLE
When a wallet is emptied, prefix "Empty wallet - " to the wallet description

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#414]
When a wallet is emptied using Empty wallet, add as a prefix to the description that it is empty.
Then in the list of wallets in the password credentials screen the user can see which wallets have money in them.

**Comment by gary-rowe** [comment]
Might be confusing if user subsequently receives funds. Perhaps a check box during the emptying process to do this so it is optional. Default is unchecked.

**Comment by bitcoin-solutions** [comment]
Let's not go down the road of 'options for everything' if we can avoid it.
The fact that a wallet can be Emptied and then subsequentl receive funds means we shouldn't 'tag' it as empty.
Closing.
