### ISSUE TITLE
Remove screenshots from help and multibit-hd.jar

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#415]
(could be in the website db but I've put it in here in Beta 7 as it affects the multi bit-hd.jar)
After discussion with Gary:

Remove screenshots from help and multibit-hd.jar.
They are currently 2.5 MB so 11% of the multibit-hd.jar

**Comment by bitcoin-solutions** [comment]
Removed all the screenshots from the release-4.0.0 help and refreshed the MBHD internal help to reflect this change. Also removed the image cache logic from the internal browser as it is no longer required,
The help loads noticeably quicker now in MBHD.
Checked the internal help loads ok by switching off WiFi and starting MBHD.
The size of multibit-hd.jar has gone down from 22.4MB to 19.2MB (-14%)

Also updated the ant XML in multibit-installers to not copy over screenshots (the carousel on the landing page still uses a few of the screenshots).
Change to help has been pushed to beta.multibit.org

Awaiting review and  closing

**Comment by gary-rowe** [comment]
Verified working. Help loads and responds much quicker now.

Closing.
