### ISSUE TITLE
Empty wallet block confirmation status not being cleared

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#417]
It seems to be showing the confirmation status of the previous time the wizard was used which is wrong.
It's the third row in the transaction confirmation status

**Comment by bitcoin-solutions** [comment]
I have pushed a change so that the status labels are cleared in the beforeShow of the report page.
In theory it is racy with transaction events updating the screen before the beforeShow only but I haven't seen this in real life.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Couldn't replicate the problem, but the code looks fine.

Closing.
