### ISSUE TITLE
Help icon in sidebar becomes invisible

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#418]
Whilst viewing the help (whilst wallet was syncing) the help button in the sidebar became invisible.

Screenshot:
![screen shot 2015-02-18 at 17 04 00](https://cloud.githubusercontent.com/assets/5002074/6252179/57607180-b790-11e4-959a-c044ff1fa99b.png)

**Comment by gary-rowe** [comment]
That's very strange. Possibly an incomplete color change in the node tree. Did it come back on a refresh?

**Comment by bitcoin-solutions** [comment]
Yes - reappeared after a switch I think I did

**Comment by jim618** [comment]
I couldn't see anything in the code that would _particularly_ cause this and couldn't reproduce it so closing.
