### ISSUE TITLE
MBHD gets confused if there is a new block when syncing

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#419]
I think it gets confused and thinks it is 'Synchronised 100%' without ever actually finishing and turning the status to green

**Comment by jim618** [comment]
This is difficult to reproduce in real life but I have been reviewing the code that drives the 'synchronized' appearing. 

It is MultiBitPeerEventListener#doneDownload.

This code is a bit belt-and-braces and fires 3 events to indicate to everything listening that the download is finished.

I think it's ok and TBH I haven't seen this error occurring since I raised the OP.

Propose closing.

**Comment by gary-rowe** [comment]
Agreed. I've not seen it during many long sync operations. 

Closing.
