### ISSUE TITLE
Header isn't updating quite right.

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#420]
The header balance isn't updating quite right.
Has it changed recently ?

I am seeing:
+ a zero in the balance for a moment before the balance occurs.
+  on a send when the tx is seen by one peer I have seen a balance of '0.00' before the proper balance occurs.

**Comment by gary-rowe** [comment]
I've not made any direct changes to this. Perhaps it is related to slow UI updates that may arise from nested `SwingUtilities.invokeLater()`. 

Brings to mind #418.

**Comment by gary-rowe** [comment]
The fixes for #426 may assist with this, but I've noticed occasional glitches in Manage Wallet FEST tests where the header should show but it isn't.

**Comment by jim618** [comment]
I tried various things (sync, repair, switch soft->soft, soft->hard, hard->soft) and could not replicate this.
Closing.

**Comment by gary-rowe** [comment]
I agree that in normal use I've not seen this so I'm OK with closing it.

Have you tried it out with the FEST tests? The single `verifyManageWallet` and `verifySettings` were the main culprits so no need for the full suite. I suspect it is just a timing issue for them though.
