### ISSUE TITLE
Current wallet not being remembered on credentials screen

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#422]
Ever since the wallet were listed alphabetically the current wallet is not being remembered.
You can see this by:
1) select a wallet
2) type in the wrong password and press unlock
3) navigate back to the credentials screen - a different wallet is selected

**Comment by jim618** [comment]
I have fixed this so that the 'lastSoftWalletRoot' (stored in the WalletConfiguration) is used to select the current/ last wallet in the credentials wallet list.

Ready for review and closing

**Comment by gary-rowe** [comment]
Verified working. (Saw both before and after situations).

Closing.
