### ISSUE TITLE
Wizard title font is too big (in German)

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#424]
The title font is too big in wizards (in German).
Screenshot:
![screen shot 2015-02-23 at 17 34 04](https://cloud.githubusercontent.com/assets/919427/6333114/52192460-bb82-11e4-93f4-e9383aa58925.png)

**Comment by gary-rowe** [comment]
Might be just that the vertical spacing needs to be reduced.

**Comment by gary-rowe** [comment]
Well [MiGLayout is powerful](http://migcalendar.com/miglayout/cheatsheet.html) but I couldn't find a setting that influenced the gap on the font during a newline operation so I just limited the maximum vertical size of the title row. This works in English, German and Romanian spanning size and font so should be OK throughout.

![screen shot 2015-02-23 at 22 53 08](https://cloud.githubusercontent.com/assets/342133/6339593/49d9bf44-bbaf-11e4-9184-bec12d30733a.png)

Ready for review and close.

**Comment by jim618** [comment]
I've decreased the main font size from 36 to 34 and decreased the title height from 100 to 96.
Not noticable but more titles fits on one line and gives a bit more space to the panel content.

Closing
