### ISSUE TITLE
Pressing ESC on credentials view reveals underlying screen

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#425]
There is no wallet loaded, but the screen activates. Just needs the window close to be disabled.

**Comment by jim618** [comment]
I've added an extra constructor to the AbstractWizard (a boolean) so you can suppress the ESC keybinding to the close action.
Tested with hard and soft wallets

Awaiting review and closing

**Comment by gary-rowe** [comment]
Added similar support to the WelcomeWizard since it also operates outside of an unlocked wallet.

Verified working in both cases so closing.
