### ISSUE TITLE
Empty wallet not enabled after sync

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#426]
Screenshot:
The Send and Request buttons were enabled correctly.
![screen shot 2015-02-23 at 21 25 13](https://cloud.githubusercontent.com/assets/919427/6337612/abca67c4-bba2-11e4-9502-c700af6ab695.png)

**Comment by jim618** [comment]
I've tightened up the code to enable the Empty wallet button (and the Send/ Request buttons too).
Tried various permutations of sync, switch and repair and it all worked.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working against a long and short sync operation. We'll need to keep an eye on it but it's working.

Closing.
