### ISSUE TITLE
Move block explorer option to Manage wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#427]
Let's go with a "Payment options" in Manage Wallet - there will be a few options from bip70. Perhaps the button could be "Payments" with an FA icon from "inbox", "money", "certificate" (I had a good look through alternatives but couldn't find anything else suitable).

**Comment by gary-rowe** [comment]
I went for the "money" icon for this initial version. Appearance wizard has had the block explorer combo removed and it is now in a new PaymentSettingsWizard. The FEST tests have been created/updated as required. 

![screen shot 2015-02-24 at 22 48 57](https://cloud.githubusercontent.com/assets/342133/6361122/6c252dfe-bc77-11e4-9a41-08d711aba1cf.png)

Ready for review and close.

**Comment by jim618** [comment]
All looks good. Closing.
