### ISSUE TITLE
Add button on Languages preference wizard to translation site

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#429]
Adding an external link button (with wording similar to "Help translate MultiBit HD") referencing the [direct CrowdIn project page](https://crowdin.com/project/multibit-hd) would help gather more translations.

This may require a flag on the panel so that it only shows when opened via the Preferences screen.

**Comment by jim618** [comment]
Added button on Languages picker that opens a browser on https://crowdin.com/project/multibit-hd
Screenshot:

![screen shot 2015-02-25 at 14 25 06](https://cloud.githubusercontent.com/assets/919427/6372229/7d92c5b4-bcfa-11e4-8f86-963c61a03480.png)

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks good to me. I had a couple of initial concerns:

* button placement might be better in cell 0 (left) position but this may not work so well in RTL languages
* the text could be improved "Thanks -> We thank them for their efforts" but it becomes too formal that way
* "I would like to help -> Help translate MultiBit HD" but then we have app.name considerations

Overall then it's fine as it stands. Closing.
