### ISSUE TITLE
Findbugs failing on Travis (spanning several builds)

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#431]
Findbugs is failing the build due to a public non-final field in `Panels`.

**Comment by gary-rowe** [comment]
Various attempts to ignore it have failed so I've wrapped it in a getter/setter structure to appease it.

Ready for review and close (assuming Travis is OK).

**Comment by gary-rowe** [comment]
Travis has passed this build.

**Comment by jim618** [comment]
Checked Travis build is passing. Smoke tested MBHD ok.
Closing
