### ISSUE TITLE
Buttons partially obscured in key words page in German

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#432]
Screenshot
![screen shot 2015-02-25 at 16 48 43](https://cloud.githubusercontent.com/assets/919427/6375325/43a42672-bd0e-11e4-9631-dd8aa8b6df83.png)

**Comment by gary-rowe** [comment]
Hmm, try [fiddling with the padding](http://migcalendar.com/miglayout/cheatsheet.html) in `AbstractWizardPanelView` line 126.

**Comment by jim618** [comment]
Decreased size of title bar to 90pixel. Also reduced title font to 30pixel. When the title wraps MigLayout adds a whole font height as a gap so 30 is the largest that will fit into a bar of 90 pixel.

Checked in Russian as that's the longest language we have.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Got a screenshot of the Russian version handy?

**Comment by jim618** [comment]
![screen shot 2015-03-02 at 14 18 33](https://cloud.githubusercontent.com/assets/919427/6442350/11483f10-c0e7-11e4-9ec0-a33229a59da7.png)

Still a bit crowded

**Comment by gary-rowe** [comment]
The MiG layout padding/margin/insets for top could be lowered. See `PanelDecorator.applyWizardTheme` and adjust accordingly. Use `"debug,"+` to activate debugging outlines in any MiG panel layout.

**Comment by jim618** [comment]
I think this is the best I can do - inserts down from 15 to 10. Gets a bit too near the window edge lower than that. Screenshot:
![screen shot 2015-03-02 at 17 00 11](https://cloud.githubusercontent.com/assets/919427/6445801/61ccde0c-c0fe-11e4-9b8d-947cedf30578.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Just in case you weren't aware, you can set the insets to be 15 around the edges and 10 at the top and bottom. Lots of information in the [Mig cheat sheet](http://migcalendar.com/miglayout/cheatsheet.html).

**Comment by jim618** [comment]
This is a slightly wider wizard panel (by 10 pixels to 640) and insets left and right 15 each. Top 0 and bottom 15.
Screenshot:

![screen shot 2015-03-02 at 20 35 28](https://cloud.githubusercontent.com/assets/919427/6449851/c2caaaaa-c11b-11e4-983d-731c0de3fb57.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Yep, that looks fine (sure you don't have 14px insets there?)

Closing.

**Comment by jim618** [comment]
Hadn't pushed the change from 14 to 15. Done
