### ISSUE TITLE
Fee slider font color is wrong in Dark Theme

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#433]
Still dark, should be light.
Screenshot:

![screen shot 2015-02-25 at 20 35 43](https://cloud.githubusercontent.com/assets/919427/6379970/10e25e8c-bd2e-11e4-99c5-cf5c02126eaa.png)

**Comment by jim618** [comment]
Fixed color scheme. Screenshot:
![screen shot 2015-03-02 at 14 38 00](https://cloud.githubusercontent.com/assets/919427/6445285/d238404a-c0fa-11e4-98d9-1eae755d0be1.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Sure you don't want to make the button yellow? ;-) 

(That would involve Nimbus painters and other horribleness so don't even go there)

Closing.
