### ISSUE TITLE
Not enough space on slider for all of 'Lower', 'Default', 'Higher' in Russian

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#435]
The words for 'Lower' and 'Default' overlap in Russian as the words are longer.
Needs a bigger slider or some other arrangement

**Comment by jim618** [comment]
That's on the Preference | Fees screen.
Screenshot:

![screen shot 2015-03-01 at 15 40 58](https://cloud.githubusercontent.com/assets/919427/6431489/693d8e0a-c029-11e4-82d6-48091e1e5dad.png)

**Comment by jim618** [comment]
Added an up arrow on the default to push the Default text to a second row. Screenshot:

![screen shot 2015-03-02 at 14 38 00](https://cloud.githubusercontent.com/assets/919427/6445262/ac9a823a-c0fa-11e4-94e1-d871571d2290.png)
![screen shot 2015-03-02 at 16 35 18](https://cloud.githubusercontent.com/assets/919427/6445261/ac954b9e-c0fa-11e4-98ae-dbb028ad5187.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks good to me (code and screenshots)

Closing.
