### ISSUE TITLE
Button labels and titles don't always match in Translations

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#436]
In German there are two terms for 'Sounds'
In English 'Application' drills down to a screen titled 'Themes'

These need to be harmonised
Note it is acceptable for a button to be labelled slighty shorter e.g. 'Payments' and the title to be longer, say, 'Payment Settings'.

**Comment by jim618** [comment]
For the short button names (Units, Appearance, Sounds) I have used the same MessageKey for both the button and title so they will be the same by construction.

For the others this will be locale dependent - I have checked the German and Spanish (and English). It will be up to the localisers to ensure consistency for these.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
