### ISSUE TITLE
Add https://insight.bitpay.com to list of block explorers

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#439]
This is the BitPay block explorer

Format of URL:
https://insight.bitpay.com/tx/28e15086d8b0e780bff69590bb1ded421392d95ae54652c949bf653ada4bf0c7

This block explorer is multilingual (must be something in the header) English Spanish Japanese

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Seems that the i18n on the block explorer doesn't use the `Accept-Language` header and relies instead on a user preference so we can't take advantage.

Closing.

**Comment by jim618** [comment]
Some more block explorers here:
http://pastebin.com/EzLnZNDh
