### ISSUE TITLE
Tx not being sent - requires update to bitcoinj-alice

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#440]
Seen a few times:
Tx does not appear to broadcast and no feedback from the Bitcoin network.
Tx not appearing in your block explorer.

In log:
```
[2015-03-02 09:34:44,932] DEBUG [safe-fixed-bitcoin-network-1] o.m.h.c.s.BitcoinNetworkService - Initiated broadcast of transaction: '01000000018fa292ffd949404c19bda80832c1e83bda16d7418f7176de320d872d0d02434d010000006b483045022100dcf831178cd00bfaac229ad906cebadf9e73c9ad2bd6cb14e47b300da6ccb7eb02200ac47305d79ee505b52077ec352898fc873bef3ce192d9dd93f51c618c30474d012102d701893ae39ff0ff43d24c65685f6b433f8f902f95f2c7dc1fb80e3361fef86dffffffff02f8a70300000000001976a9148dd0267f0b618732b83c4e7808b499f58cc72f9b88ac15f90100000000001976a9147d1065bbc56bfee5c4d882d48a0d4dd38bb0747388ac00000000' 
[2015-03-02 09:34:44,932] DEBUG [safe-fixed-bitcoin-network-1] o.m.h.c.s.BitcoinNetworkService - Forgetting last SendRequest and Wallet  
[2015-03-02 09:34:45,098] DEBUG [safe-fixed-core-events-5] o.m.h.c.s.WalletService - Writing payments completed 
[2015-03-02 09:35:00,576] DEBUG [bitcoinj user thread] o.m.h.c.n.MultiBitPeerEventListener - (disconnect) Number of peers = 6 
[2015-03-02 09:35:00,576] ERROR [NioClientManager] o.b.n.NioClientManager - Failed to connect with exception: java.nio.channels.ClosedChannelException: null 
```
If you 'bounce' the network by doing a switch back into the same wallet the tx gets sent/ resent (by a new peer).

**Comment by jim618** [comment]
Relevant google groups:
https://groups.google.com/forum/#!msg/bitcoinj/ze6qh622Y5s/DQFnF5hb_TQJ

We probably need to rebase bitcoinj-alice to 0.13-SNAPSHOT

**Comment by gary-rowe** [comment]
Yes, we should have a general tidy up of Bitcoinj-Alice and issue an upstream pull request to get BIP44 support into Bitcoinj. This would greatly simplify code moving forward.

**Comment by jim618** [comment]
The BIP44 support code in bitcoinj-alice is not very general - I don't think it would be accepted into bitcoinj as is. It would need refactoring out with a definition of what's in a wallet. I don't particularly want to do this before the Release 0.1

**Comment by gary-rowe** [comment]
OK. Created #441 to cover it. Currently scheduled for Release 0.2.

**Comment by jim618** [comment]
Integration work is being done with:
+ bitcoinj-alice devleop branch
+ MBHD issue-440 branch

**Comment by jim618** [comment]
I have updated the bitcoinj-alice branch and now use the TransactionBroadcast which improves the SendReport screen.

Awaiting review and closing

**Comment by jim618** [comment]
I have hooked up the 'broadcast progress' information that bitcoinj provides in a listener.
The 'bullhorn' icon partially fills up as the peers report seeing a transaction.

**Comment by jim618** [comment]
I have increased the max number of connections MBHD makes to 8.
Thus on a send it will broadcast to 4 peers and be 'officially' sent when it sees it on an inv from 2 of the others. This gives some headroom against slow/ broken peers.

**Comment by gary-rowe** [comment]
Not working for me. I did a Maven install of the latest `develop` of Bitcoinj Alice and used the latest code (`ded1d42160...`)

![screen shot 2015-03-08 at 12 43 44](https://cloud.githubusercontent.com/assets/342133/6545807/500b5648-c591-11e4-9c5c-907ab5594897.png)

Saw this exception:
```
[2015-03-08 12:50:04,668] DEBUG [AWT-EventQueue-0] o.m.h.c.s.BitcoinNetworkService - Not adding client fee output due to !sendRequest.emptyWallet = true or sendRequestSummary.isApplyClientFee() = false 
[2015-03-08 12:50:04,668] DEBUG [AWT-EventQueue-0] o.m.h.c.s.BitcoinNetworkService - Completing send request... 
[2015-03-08 12:50:04,677] ERROR [AWT-EventQueue-0] o.m.h.c.s.BitcoinNetworkService - Could not complete the transaction without signing ! java.lang.IllegalArgumentException: Given SendRequest has already been completed.
! at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[guava-16.0.1.jar:na]
! at org.bitcoinj.core.Wallet.completeTx(Wallet.java:3520) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
! at org.multibit.hd.core.services.BitcoinNetworkService.completeWithoutSigning(BitcoinNetworkService.java:844) [classes/:na]
! at org.multibit.hd.core.services.BitcoinNetworkService.prepareTransaction(BitcoinNetworkService.java:755) [classes/:na]
! at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.prepareTransaction(EmptyWalletWizardModel.java:262) [classes/:na]
! at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.showNext(EmptyWalletWizardModel.java:109) [classes/:na]
! at org.multibit.hd.ui.views.wizards.AbstractWizard$5.actionPerformed(AbstractWizard.java:349) [classes/:na]
! at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018) [na:1.7.0_51]
! at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341) [na:1.7.0_51]
! at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.7.0_51]
! at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.7.0_51]
! at javax.swing.plaf.basic.BasicButtonListener$Actions.actionPerformed(BasicButtonListener.java:303) [na:1.7.0_51]
...
```

**Comment by jim618** [comment]
You also need to build multibit-hardware as the bitcoinj-alice is now transitive

**Comment by gary-rowe** [comment]
Yep. Done that too (although simply building Bitcoinj Alice would install the required bitcoinj-alice-develop-SNAPSHOT into the shared Maven repo). Are you sure you've pushed everything?

**Comment by jim618** [comment]
I don't have anything local.
To make progress and see the new snazzy send report screen you might want to:
Go into bitcoinj-alice Wallet#completeTx and remove the check that throws the IllegalStateException 'Given SendRequest as already been completed'.

The MBHD code also has to make sure that it removes the txInputs on an Empty otherwise they get added twice but that's in MBHD code and you'll have that.

**Comment by jim618** [comment]
Just wanted to double check we are both using the same repo.
My alice remote is:
origin git@github.com:bitcoin-solutions/bitcoinj-alice.git (fetch)
origin git@github.com:bitcoin-solutions/bitcoinj-alice.git (push)

**Comment by gary-rowe** [comment]
Here's some progress. I was able to use the Send screen to create a transaction. Saw the bullhorn filling up (like it) so that's all good.

However, it's still failing on the Empty panel with the same exception:
```
[2015-03-10 21:24:41,610] ERROR [AWT-EventQueue-0] o.m.h.c.s.BitcoinNetworkService - Could not complete the transaction without signing ! java.lang.IllegalArgumentException: Given SendRequest has already been completed.
! at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[guava-16.0.1.jar:na]
! at org.bitcoinj.core.Wallet.completeTx(Wallet.java:3520) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
! at org.multibit.hd.core.services.BitcoinNetworkService.completeWithoutSigning(BitcoinNetworkService.java:844) [classes/:na]
! at org.multibit.hd.core.services.BitcoinNetworkService.prepareTransaction(BitcoinNetworkService.java:755) [classes/:na]
! at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.prepareTransaction(EmptyWalletWizardModel.java:262) [classes/:na]
! at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.showNext(EmptyWalletWizardModel.java:109) [classes/:na]
...
```
I'm using `Maven: org.bitcoinj:bitcoinj-core:0.13-alice-develop-SNAPSHOT` installed using the HEAD of `develop` branch. Fingerprint: `f93875a3f8640198e5783c75669876841fe22e80`. When doing the Maven install I manually deleted the original entries in the repository and verified that new ones had been created. 

I'm certain that there is an issue in the Empty wallet code that isn't present in Send Bitcoin.

**Comment by jim618** [comment]
As you've got a tx sending ok I'll close this one and put a comment on the 'Empty wallet not working issue'.

**Comment by jim618** [comment]
Your code and my code are not the same !

In my bitcoinj-alice Wallet line 3520 is:
// ALICE - allow a send request to be completed twice - used in Empty wallet

This is exactly the change I made to replace the precondition that is firing and is shown in your exception stack trace.

Here is my git status and log:
```
jims-macbook-91:bitcoinj-alice jim$ git status
On branch develop
nothing to commit, working directory clean
jims-macbook-91:bitcoinj-alice jim$ git remote -v
bitcoinj-canonical	https://github.com/bitcoinj/bitcoinj.git (fetch)
bitcoinj-canonical	https://github.com/bitcoinj/bitcoinj.git (push)
origin	git@github.com:bitcoin-solutions/bitcoinj-alice.git (fetch)
origin	git@github.com:bitcoin-solutions/bitcoinj-alice.git (push)
jims-macbook-91:bitcoinj-alice jim$ git log
commit 698c12d5fa861898cdce4f91586d2190d397cc87
Author: Jim Burton <jim618@fastmail.co.uk>
Date:   Sat Mar 7 16:16:21 2015 +0000

    relaced check on double complete (used in MBHD empty wallet)

commit f93875a3f8640198e5783c75669876841fe22e80
Author: Jim Burton <jim618@fastmail.co.uk>
Date:   Thu Mar 5 12:22:08 2015 +0000

    added 'develop' into artifact name to distinguish it from the one created by bitcoinj-alice master branch

commit 7757463d845972b8625cca916c0042b0c39a48d6
Author: Jim Burton <jim618@fastmail.co.uk>
Date:   Wed Mar 4 16:25:32 2015 +0000

    removed Java 8 modules

commit a020b2b9dd8cdb74a57a2f8e9a9e41024cfad352
Author: Jim Burton <jim618@fastmail.co.uk>
Date:   Wed Mar 4 15:49:05 2015 +0000

    removed examples as uses Java 8

commit 306ccba832ad12f14a88677187afe851b845bfcd
Author: Jim Burton <jim618@fastmail.co.uk>
Date:   Wed Mar 4 15:34:39 2015 +0000

    turned off date check has to be at root as not the case with trezor wallets

commit cb8473f98d7ad911f47ccb6fc7aadcfb4b5f6eb0
Merge: 4732aee 6c733b2
:
```

Can you just go into the Wallet class and see what you have on line 3520, that will be quickest.
Also, can you make sure that you are picking up the correct artifact in your MBHD pom.
It should be bitcoinj-alice-develop-SNAPSHOT

**Comment by jim618** [comment]
Also worth checking that the multibit-hardware POM is picking up bitcoinj-alice-develop-SNAPSHOT.

**Comment by jim618** [comment]
I've reopened this as we are still commenting on it

**Comment by jim618** [comment]
I just checking on:
```
https://github.com/bitcoin-solutions/bitcoinj-alice/blob/develop/core/src/main/java/org/bitcoinj/core/Wallet.java
```
And did not see my change on Wallet#3520.
I have touched the file and repushed and see it now.

Not sure what happened there.

**Comment by jim618** [comment]
Try updating your bitcoinj, building it and retrying.

**Comment by gary-rowe** [comment]
It works! After I did the pull and a diff it showed no difference between the files. I invalidated my local Intellij caches, deleted any trace of bitcoinj-alice from my local repo, rebuilt bitcoinj-alice on `develop`, verified the correct code was present in External Libraries and performed an Empty wallet. 

Verified working so closing.
