### ISSUE TITLE
Crashes after setup (Centos 7)

### ISSUE THREAD

**Issue by sipak** [bitcoin-solutions/multibit-hd#442]
Crashes after setup with / without TREZOR on Centos 7: see log and image at bottom:

```
[2015-03-02 14:40:34,400] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.u.v.w.c.CredentialsWizardModel - Features: Optional.of(org.multibit.hd.hardware.core.messages.Features@555896b3[
  vendor=bitcointrezor.com
  version=1.3.1
  bootloaderMode=false
  deviceId=FF15AF0FEB0B1DABCB58B49B
  pinProtection=true
  passphraseProtection=false
  language=english
  label=Bigga Multibita
  coins=[Bitcoin, Testnet, Namecoin, Litecoin, Dogecoin]
  initialized=true
  revision= f2 f5 0a a1 88 64 29 aa ea b5 aa 88 e8 c6 e1 06 ac 52 24 b1
  bootloaderHash= c4 c3 25 39 b4 a0 25 a8 e7 53 a4 c4 62 64 28 59 11 a4 5f cb 14 f4 71 81 79 e7 11 b1 ce 99 05 24
  imported=false
  supported=true
]) 
[2015-03-02 14:40:34,400] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.u.v.w.c.CredentialsWizardModel - Running decrypt of Trezor wallet with entropy of length 16 
[2015-03-02 14:40:34,514] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - getOrCreateTrezorHardWalletSummaryFromRootNode called 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fea4f410468, pid=4943, tid=140642825492224
#
# JRE version: OpenJDK Runtime Environment (7.0_75-b13) (build 1.7.0_75-mockbuild_2015_01_21_05_53-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.75-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.5.4
# Distribution: Built on CentOS Linux release 7.0.1406 (Core)  (Wed Jan 21 05:53:48 UTC 2015)
# Problematic frame:
# C  [libc.so.6+0x142468]  __memcpy_ssse3+0x2808
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/jvm-4943/hs_error.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

(https://cloud.githubusercontent.com/assets/4264782/6464611/b442c01c-c1bb-11e4-97f1-d6827c0616f5.png)

**Comment by jim618** [comment]
This looks like it is something in the JRE going bang when it is trying to decrypt/ process/ create a Trezor wallet.

Could you try another version os Java rather than IcedTea please ?
The (latest available to you) Oracle JRE would be a good one to try.

**Comment by jim618** [comment]
Also, the screenshot you attached indicated that it is a 'headless' error.
Headless here means "I cannot run a GUI" - it's often a smaller JRE that is run on servers.
That could be the problem.

Again, the advice to try a 'vanilla Oracle JRE' still stands.
Thanks.

**Comment by gary-rowe** [comment]
Did changing the JVM fix the issue here? If so, I can update the Linux installation instructions for Centos to reference the Oracle JDK.

**Comment by gary-rowe** [comment]
Actually it's worth [referencing the "How to install on Linux" guide](https://beta.multibit.org/en/help/hd0.1/how-to-install-linux.html) here since it does offer the suggestion of removing scrypt from `multibit-hd.jar`.

**Comment by sipak** [comment]
After installing Oracle JVM on Centos 7, the issue seems to be gone.

**Comment by gary-rowe** [comment]
Thanks for the feedback - much appreciated. I'll keep the Oracle JVM advice in place for the Linux installation instructions.

Closing.
