### ISSUE TITLE
Losing connection to Trezor after cancelling 'Change PIN' action

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#443]
User @lkamp initially raised this:

I just played around with Multibit and my Trezor (which by the way is the best combination for me right now!) and stumbled about the following behavior (a Trezor has to be connected):

1.) Go to "Manage Wallet", click "Change PIN".
2.) Select "Change an existing PIN or add a new PIN" and click "Next".
3.) A message appears on the Trezor asking if you want to change the PIN of the device.
4.) When you press the "Cancel" button on the Trezor, Multibit tells you it discovered a new Trezor.

Sometimes, after clicking "Yes" to use your Trezor, the Trezor gets re-initialized, sometimes it doesn't and you can use the wallet. I've tagged the issue with "Minor Bug" because the wallet continues to work with the Trezor, however I think it should not tell me about a new Trezor when I cancel an action on the device.

**Comment by gary-rowe** [comment]
Thanks for reporting this. It looks like an "operation failed" is not being handled correctly. Correct behaviour should be to show an "operation cancelled" message on the PIN wizard report screen.

**Comment by jim618** [comment]
I was comparing with the 'Empty wallet' code, which is similar.

If you do a 'cancel' on the Trezor when signing it correctly traverses to the report screen but you also see the 'there is a new trezor' alert in the background - same as 'Change PIN'

The 'change PIN' wizard model has the same showOperationSucceeded/ showOperationFailed code (ish) as Empty wallet.

**Comment by jim618** [comment]
If I do a cancel (on the Trezor) in either 'Change PIN' or 'Empty wallet' I see a 'Device Ready' event in MainController#916 and hence see alerts notifying of a new Trezor. Both of these seem semantically wrong.

**Comment by gary-rowe** [comment]
Adjusted the event threshold handling to ignore the `DEVICE_READY` fired from MBHW as a result of the re-initialisation. Also moved this threshold into `ApplicationEventService` which is a more appropriate location for it and simplifies the downstream logic into a simple method call.

In the event of a failure in Change PIN the user is taken to a report screen showing an appropriate message for the operation: change or add.

![screen shot 2015-04-03 at 19 23 52](https://cloud.githubusercontent.com/assets/342133/6986936/22de7390-da3a-11e4-8358-38774f0e47b9.png)

To verify, simply attempt to change a PIN and click Cancel on the device when given the opportunity. It should behave as normal.

Ready for review and close.

**Comment by jim618** [comment]
Checked 'Cancel' on Trezor navigate to report screen correctly.
Closing.

**Comment by jim618** [comment]
Also confirmed cancel on  'Empty wallet' works correctly
