### ISSUE TITLE
Empty wallet not working

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#447]
If you try to empty a wallet you get the error:

"Given SendRequest has already been completed"
and the tx is not sent

**Comment by jim618** [comment]
Fixed, including an update to bitcoinj-alice which has been pushing to the maven staging repo.
Tested on soft wallets and a Trezor hard wallet ok.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Seems to be dependent on the fix for #440 which has bounced back. I'll mark this as awaiting issue.

**Comment by jim618** [comment]
Have you updated your copy of bitcoinj-alice?
There's a check in there that has been switched off

**Comment by jim618** [comment]
I just retested this with one of my wallets successfully

**Comment by gary-rowe** [comment]
OK, I'll add it to the pile of things to test tonight.

**Comment by jim618** [comment]
Jim has this working but Gary does not.

**Comment by jim618** [comment]
Pushed change to Wallet (line 3520)
Try updating your bitcoinj, building it and retrying.

**Comment by gary-rowe** [comment]
Verified working so closing.
