### ISSUE TITLE
Using Trezor with MultiBit HD requires zapping existing wallet stored in the Trezor

### ISSUE THREAD

**Issue by tl121** [bitcoin-solutions/multibit-hd#449]
I have a Trezor that I have been using with MyTrezor and Electrum 2.0.  Both programs work with the same wallet with its private keys held by the Trezor.  Both programs found the contents of the wallet after initial installation by automatically querying the Trezor.  I can access the bitcoins in this Trezor on multiple computers, running MyTrezor or  Electrum 2.0.  I expected similar behavior from Multibit HD 0.0.7beta.  However, after connecting the Trezor to my computer and starting Multibit HD, the only Trezor option that I was offered involved zapping the wallet already in the Trezor and creating a new wallet.  

Is there some way to use Multibit HD to access an existing Trezor hardware wallet?  If so, then I suggest the startup dialog be revised to make it clear how to do this.  If not, then this capability needs to be added.  

( I downloaded the following installer: multibit-hd-windows-x64-0.0.7beta.exe)

**Comment by jim618** [comment]
Thanks for your feedback.

For a Trezor wallet WITHOUT a password the usage is starightforward:
1) Start up MultiBit HD and plug in your Trezor.
2) You get an alert saying 'Trezor "your trezor label' attached. Do you want to use it ?". Click 'Yes'.
3) You then get a PIN challenge from your Trezor where you type in our PIN in MBHD.
4) You then get a screen asking you to 'Press Next to unlock your Trezor (this generates a password used to decrypt your local wallet)
5) MBHD then syncs the wallet (take about 10 minutes first time) and then you are ready to go.

If your Trezor has a password protected wallet then we are not supporting that type of wallet in MBHD. We found with MultiBit Classic that a small proportion of people forget their password (it is about once incident in 30,000 user-months). These cause a lot of angst and ultimately loss of bitcoins. For this reason we have added into MBHD password recovery for the regular (non-Trezor) wallets worked out from the user's wallet words (aka seed phrase). We cannot offer this facility with the Trezor password so are not supporting this type of wallet..

**Comment by tl121** [comment]
I got it to work, by plugging in the Trezor before starting Multibit.  I also got it to work by starting Multibit first and then connecting Trezor.  However, the reaction of Multibit was a bit unexpected, which is why I probably got confused initially.  I did not expect the Enter Wallet Password dialog box to be blown away as soon as I connected the Trezor USB connector and replaced by the Trezor unlock dialog box.

The user interface for wallet selection between software wallets and hardware wallets might warrant additional thought.  I prefer the way Electrum 2.0 works, where the wallet type is set when the wallet is created or restored and where the normal program startup uses a default wallet.

**Comment by gary-rowe** [comment]
We did consider having a default "Trezor type" wallet that prompted for a Trezor to be plugged in if it was absent, but user feedback indicated that the act of plugging in the Trezor should automatically detect the appropriate wallet (or create it if it is the first time it has been presented). 

On balance we felt this was more intuitive for people with several Trezors and several "soft" wallets.

The reasoning behind the the "blowing away" of the password screen is that the credentials and wallet selection are now being provided entirely by the Trezor device. Consequently there is no need for a password or wallet selector or unlock button. Thus the screen adapts to reflect this simplification.

**Comment by tl121** [comment]
In my case, I am just using a single Trezor.  However, if later you want to implement a Trezor based "watch only" capability then I believe some wallet selection dialog will be needed. (I find it convenient to keep my Trezor locked away and have access to my wallet addresses and balance on my office computer. When testing Multibit HD, I found it inconvenient to have to unlock the storage, fetch the Trezor, connect it to my computer and then enter the PIN before I could check my balances.)

**Comment by gary-rowe** [comment]
Adding a "watch only" wallet is not on our roadmap at the moment. There are two principle reasons behind this decision:

* the wallet is encrypted using entropy that is only available from the Trezor device so the device must be physically present to unlock it - this greatly improves security (including an attacker gaining knowledge of a balance)
* user feedback indicated that the idea of a wallet without send capability was quite confusing to the less technically capable and they were unlikely to use it 

One workaround would be to use the Trezor to unlock the wallet at the start of the session and then detach it and place it in the secure box. So long as you don't attempt an operation involving the Trezor like a spend then you should be operating in a pseudo-watching mode.

**Comment by tl121** [comment]
I have two Trezors, one as yet unused in a sealed box.  I bought them so that I would not have to worry about my bitcoins being stolen if malware ended up on my computers.  Previously, I had been using off-line wallets, but this was a complex and tiresome procedure. I see the hardware wallet as an "ease of use" component as a security enhancement.  Others may have different feelings.  I would be much more likely to use Multibit HD if you were to implement a "watch only" capability. But this is a question of "features" not "bugs". 

I don't worry about my bitcoin balance becoming public as a result of my computers/ being compromised. If my computers are compromised, I will have worse problems. I also don't view any of the Multibit files stored on disk as having any real value, since they can easily be recreated from the block chain and my Trezor (or my Trezor seed file that is locked up in a vault). (It takes about 10 minutes.)

**Comment by gary-rowe** [comment]
Fair enough. One point to note about the MultiBit files stored on disk is that they contain more information than what is present on the block chain: exchange rates; contacts; private notes and so on. While the wallet words protect your bitcoins, you need your encrypted backups to protect that information.

**Comment by gary-rowe** [comment]
Closing due to inacitvity.
