### ISSUE TITLE
PaymentRequest alert needs to be truncated when showing a failure

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#453]
At present the PaymentRequest alert bar is showing a double error message which results in the bar exceeding the available width of the UI.

**Comment by gary-rowe** [comment]
Quite a bit done in this seemingly innocuous change. I've ensured that truncation only occurs in the HeaderView as part of the alert bar layout. 

To verify get an alert up with a fairly long message then resize. Truncation will appear as ellipsis as normal. The History will contain the full text for audit purposes.

Ready for review and close.

**Comment by jim618** [comment]
Tried it out with a long payment request (and temporarily changed min width in MultiBitUI) and saw ellipsis ok. Closing.
