### ISSUE TITLE
Activate main BRIT server 

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#456]
At present the BRIT system is using only the backup addresses. It is now time to activate the main BRIT server.

**Comment by jim618** [comment]
Progress on the BRIT server today:
+ Created 1 redeemer wallet (501 keys)
+ Created new matcher-key.asc with new password
+ Got the BRIT server on multibit.org able to run on localhost:7070

To do:
+ Integrate with apache httpd to expose dropwizard service
+ Test out IRL with MBHD using the new matcher key

Note that because we've changed the PGP key other people won't be able to talk to the matcher service until we put out beta 9. This is probably a good thing whilst we fiddle with it.

**Comment by jim618** [comment]
Sorry I mean beta 8, not 9.

**Comment by jim618** [comment]
The BRIT server on multi bit.org is now live.
It includes the redeemer2.txt addresses.

Log from MBHD on creation of a new wallet:
```
[2015-03-24 15:49:28,497] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Creating FeeService with matcherURL: https://multibit.org/brit 
[2015-03-24 15:49:28,498] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Performing exchange with matcher ... 
[2015-03-24 15:49:28,594] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Payer request:
1
55a6886f3cdc1a8bb2a73295479aaf6c9b61881e
e4bc46da69f9c8453f0fd98667c5f9c1
not-present
 
[2015-03-24 15:49:29,291] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Attempting to post 642 bytes to URL https://multibit.org/brit 
[2015-03-24 15:49:30,037] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Matcher response (encrypted):
SNIP
[2015-03-24 15:49:30,042] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Matcher response (decrypted):
1
1427212169857
1M8VDb7Pe81CEcmVbZf2AJQQx6Nushgcqq
14p28aTP5LzCnaSnbex1s2JtN79jC8Ddq7
1AWA3cDXkb1NsTYsAo3gZs66qTjNFDsMeZ
1ErCCTiHjrTFEwsEJrgLrXuidvASbjz1tq
```

The updated links.txt file on multibit.org:
```
[brit@hamburg142 store]$ cat links.txt
4bbd8a749179d65a5f1b0859684f53ba5b761714 1427211894223 1427211894222
55a6886f3cdc1a8bb2a73295479aaf6c9b61881e 1427212169857 1427212169857
```

The relevant snippet of the brit-server.log on multi bit.org:
```
DEBUG [2015-03-24 15:49:29,620] org.multibit.hd.brit_server.resources.PublicBritResource: Processing payer request payload of length 642 bytes
DEBUG [2015-03-24 15:49:29,620] org.multibit.hd.brit_server.resources.PublicBritResource: Creating Matcher response
DEBUG [2015-03-24 15:49:29,856] org.multibit.hd.brit.dto.PayerRequest: Parsed OK
DEBUG [2015-03-24 15:49:29,857] org.multibit.hd.brit_server.resources.PublicBritResource: Decrypted payer request BRIT walletId: 55a6886f3cdc1a8bb2a73295479aaf6c9b61881e
DEBUG [2015-03-24 15:49:29,857] org.multibit.hd.brit.dto.PayerRequest: Serialised walletToEncounterDateLink = 
55a6886f3cdc1a8bb2a73295479aaf6c9b61881e 1427212169857 1427212169857
DEBUG [2015-03-24 15:49:29,857] org.multibit.hd.brit_server.resources.PublicBritResource: Decrypted matcher response, number of addresses: 4
DEBUG [2015-03-24 15:49:29,859] org.multibit.hd.brit_server.resources.PublicBritResource: Encrypted matcher response, size: 160 bytes
DEBUG [2015-03-24 15:49:29,859] org.multibit.hd.brit_server.resources.PublicBritResource: Matcher response produced of length 160 bytes
```

I've added in a test in MBHD CoreServicesTest that creates a new wallet and does a BRIT exchange for real against multibit.org. This will insert BRIT wallet ids into the links.txt that are artifacts but I suggest we don't worry about them for the moment. It's a good test of the uptime of the BRIT server on multibit.org.

There are lots of refinements we can do but this gives us baseline functionality.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Hmm, not sure that using Travis to verify uptime of BRIT is a good idea. What about setting up an [IFTTT channel](https://ifttt.com) to conduct basic monitoring where we have a test wallet and verify the response?

**Comment by jim618** [comment]
It's just a unit test.
I just wanted a proper test that it actually works.

**Comment by gary-rowe** [comment]
If it reaches out to the wider network it's actually an IntegrationTest and should have `@Ignore` set for Maven builds.

I've set up the site monitoring so we can track the BRIT server uptime and I'll test this is working tonight.

**Comment by jim618** [comment]
Yeah that's all very well Gary but BRITs not much use if it doesn't actually perform a BRIT exchange IRL.

We didn't have any test that the client and server could talk to each other correctly and I spent all day today setting it up.

**Comment by gary-rowe** [comment]
I'm not objecting to the test - that's good work mate and needed. I'm only pointing out that you're introducing a dependency on an external server into the build process which makes it less reliable. What if Travis blocks access to multibit.org? 

Renaming it to an IntegrationTest makes it clear that it requires special treatment and marking it with @Ignore ensures that Maven isn't affected but the test remains viable within an IDE.

**Comment by jim618** [comment]
Ok no worries.

**Comment by jim618** [comment]
I've renamed the test to BRITExchangeIntegrationTest and created a new package for it:
org.multibit.hd.integration

It's marked as "Ignore"

**Comment by gary-rowe** [comment]
Verified working.

Closing.
