### ISSUE TITLE
Enter timestamp field needs a note about leaving it empty

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#457]
The "enter timestamp" field can be left empty and this will trigger a sync from the earliest possible HD date for the given wallet. A note to this effect should be present on the screen worded something like this:

"Leave this field empty if you do not know the timestamp. Synchronization will take longer."

**Comment by gary-rowe** [comment]
Rather than clutter the UI with explanatory notes, I've just added some text to the existing tooltip which should be shown if the user is searching for guidance: 

"The timestamp associated with the wallet words. Leave blank if not known."

Ready for review and close.

**Comment by jim618** [comment]
I've put the same tooltip change into EN_en and EN_us  (mainly just to see it).
Looks fine. Agreed there isn't enough space for a in-screen message so tooltip is the way to go.

closing
