### ISSUE TITLE
FEST tests for 'Enable restore of Beta7 wallets' to do

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#458]
That's a FEST test on the labs panel to exercise the combo box and similar ones on the restore panel to check the 'Beta7' wallet appears/ does not appear accordingly.

**Comment by jim618** [comment]
There are now FEST tests to exercise the 'Enable restore of Beta7 wallets' functionality as described in the OP.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
FEST test verified working.

Closing.
