### ISSUE TITLE
Check WalletManager#EARLIEST_HD_WALLET_DATE is used when no timestamp set on sync

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#459]
On a restore if there is no timestamp the WalletManager#EARLIEST_HD_WALLET_DATE should be used as the sync date.

In testing I saw some syncs of 8000 blocks (2 months) which I think is too short

**Comment by gary-rowe** [comment]
Agreed. This indirectly relates to #457 which handles the UI for this behaviour.

**Comment by jim618** [comment]
Pushed some changes so that a missing timestamp forces a sync back to WalletManager#EARLIEST_HD_WALLET_DATE (1 May 2014).

Also checked it hasn't broken regular syncs for existing wallets.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Code review looks good to me. Adjusted `Date` to `DateTime` for consistency.

Closing.
