### ISSUE TITLE
Changing password 'pad block corrupted'

### ISSUE THREAD

**Issue by hughht5** [bitcoin-solutions/multibit-hd#460]
Bug changing password: see image.
![screen shot 2015-03-12 at 11 16 23](https://cloud.githubusercontent.com/assets/629186/6616755/4c6f6522-c8a9-11e4-8e3b-bcee1ad612e3.png)

**Comment by jim618** [comment]
Proposed fix in #470 so marking as awaiting issue

**Comment by gary-rowe** [comment]
Change password verified working. Test included a new style paymentrequest.aes which was correctly updated.

@hughht5 needs to verify this on his machine using a 0.0.0 installer so marking as "installer" pending close.

**Comment by jim618** [comment]
I have uploaded a test installer for @hughht5 to test here:
https://beta.multibit.org/releases/multibit-hd/multibit-hd-0.0.0/

It won't fix the existing wallet but if you create a new wallet you should be able to change password etc ok.

Awaiting review and closing

**Comment by jim618** [comment]
I have tried the 'change password' on both MacOS and Windows 8 installs using this code successfully. I didn't actually see the OPs problem so it is not a 100% test but shows no regression.

**Comment by jim618** [comment]
I've closed this as neither @gary-rowe or I are seeing this problem.
@hughht5 if when you retest it it's still a problem open it again.
