### ISSUE TITLE
Clear tx hash in PaymentRequestData if tx is not in wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#463]
Reason: (after a failed send user may do a 'Repair wallet'. Needs to pay again.)

**Comment by jim618** [comment]
Just pushed code that clears stale tx hashes from BIP70 payment requests if the tx has disappeared from the wallet.

This is a bit of an edge case (removing a stale foreign key reference really) so best if you code review it.
It is in WalletService#readPayments lines 761 to 771.

I've tested that it does not produce any regressions.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Looks good to me. 

Closing.
