### ISSUE TITLE
Cannot delete / undo delete of BIP70 payment request

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#464]

**Comment by jim618** [comment]
Just pushed code so that you can now also delete and undo delete BIP70 payment requests.
You can delete MBHD and BIP70 payment requests and the undo works off a shared stack.

The bip70 payment request files (in payments/bip70) are also secure deleted / rewritten accordingly.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working (observed changes in the files and logs).

Closing.

**Comment by jim618** [comment]
I've renamed the test to BRITExchangeIntegrationTest and created a new package for it:
org.multibit.hd.integration

It's marked as "Ignore"
