### ISSUE TITLE
BIP70 payment requests not exported

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#465]

**Comment by jim618** [comment]
Just pushed code so that the BIP70 payment requests are also exported.
The export now produces 3 files: transactions, your payment requests, their payment requests.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. 

One observation: the export format will only wrap text in double quotes if the text field contains a comma. This seems odd, but the code is a standard CSV library so it's probably providing maximum compatibility.

Closing.
