### ISSUE TITLE
Don't show the 'Choose payment request' screen if there is just one payment request

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#467]
In normal use there is just one matching tx for an MBHD payment request.
(In theory a single tx can pay off multiple MBHD payment requests).

In the transaction details wizard:
To make the UI simpler and more consistent with how BIP70 payment requests are shown, remove the 'Choose matching payment request' screen if there is just one matching payment request.

**Comment by jim618** [comment]
Pushed some code that skips the 'Choose payment request' (MBHD payment requests) if there is just one payment request. 
Also updated FEST test.

To see the 'choose payment request' screen you now have to create two payment requests and then go to somewhere like BCI and send a tx that pays both (use the Custom option on the left hand side). I've tested this ok. It's quite good fun to do.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
