### ISSUE TITLE
Apostrophe removed from alert bar

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#468]
The system time drift message was incorrectly displayed without the apostrophe which is present in the `language.properties` file.

**Comment by gary-rowe** [comment]
The `MessageFormat` in Java defines a single `'` as a marker for special format insertion. This has been admitted by the Java developers as being confusing to localisers but is not fixable. Consequently it is better to detect if `''` or `'{` is present in the string to be formatted. This will indicate that localisers have already performed the escaping. If these sequence are not present, then auto-escape can be applied.

This approach removes the need for special training of localisers in the use of escapes, but we should avoid their use as quotes favouring the double quote instead: 'Cancel'=bad, "Cancel"=good.

To verify, set the system clock to be out by an hour then start MultiBit HD. The alert should appear with an apostrophe correctly placed:

![screen shot 2015-04-18 at 23 47 15](https://cloud.githubusercontent.com/assets/342133/7217234/8bf47f06-e614-11e4-8c18-83784c378945.png)

Ready for review and close.

**Comment by jim618** [comment]
Apostrophe appears correctly on 'time wrong' warning. 
Closing
