### ISSUE TITLE
Change password needs to re-encrypt BIP70 payment requests

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#470]
The stored BIP70 payment requests are stored encrypted with the wallet password.
A change of wallet password needs to re-encrypt them.

This would be a good opportunity to make the change password a bit more atomic and give it a rollback on failure. 

Something like:
+ Give EncryptedReaderWriter a list of files you want to change password on.
+ It reads them in, renames the existing files to, say, ".old".
+ Decrypt in memory with old password, encrypt with new, check encryption is reversible
+ Write out to file with suffix  ".new"
+ Check size of file matches expected
+ If everything on all files ok, rename all the ".new" to target file name, otherwise rollback using the ".old".

This will most likely prevent the issues Hugh had. See #460, #461, #437

**Comment by jim618** [comment]
I've changed how the change password works so that it now works on the files directly rather than at the object level. The code is WalletService#changeWalletPasswordInternal

It also includes changing the password on the BIP70 payment request files.

Awaiting review (by @gary-rowe and then subsequently by Hugh with a test installer)

**Comment by gary-rowe** [comment]
Appears to be working but need some clarification on the test requirements. Here is a summary of what was observed:

* `contacts`, `history`, `payments` - `*.aes` (all were updated)
* `rolling-backup`- `*.aes` (only today's was updated others were present)
* `zip-backup` - `*.zip.aes` (only today's was updated others were present)

Is this correct behaviour? I was expecting all the archives to be updated.

**Comment by jim618** [comment]
This is as expected yes. 
The contacts, history, payments are all updated directly.

The rolling backups are not, but a new one is created when the newly encrypted wallets is written. The old backups (with the old password) will 'roll off' as there are only 4 of them. But if Something Bad Happens with the passowrd change/ write they will still be available for recovery.

The zip backups are encrypted with the wallet words based AES key which does not change when the password changes. It is stored in the YAML, encrypted with the wallet password so the encrypted bytes change (new password) but the actual unencrypted value does not change.

I forgot to add the Payment and PaymentACK files to the list of files to encrypt/ decrypt - I'll do this today so it will need a re-review after this.

**Comment by gary-rowe** [comment]
OK. I'll add the above information to the MBHD help files in a technical section.

**Comment by jim618** [comment]
I've added in code so that the Payment and PaymentACK files are also re-encrypted

Awaiting review and closing

**Comment by gary-rowe** [comment]
Code review and unit test looks fine. Issue #483 will identify any problems in real world use.

Closing.
