### ISSUE TITLE
Unusual behaviour in logs regarding BIP70 during sync

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#473]
Seeing a lot of repeats of this message in the logs during sync:
```
Adding in 3 BIP70 payment data rows 
[2015-03-18 20:49:50,514] DEBUG [AWT-EventQueue-0] o.m.h.c.s.WalletService - Adding in 3 BIP70 payment data rows 
[2015-03-18 20:49:51,922] DEBUG [AWT-EventQueue-0] o.m.h.c.s.WalletService - Adding in 3 BIP70 payment data rows 
[2015-03-18 20:49:53,108] DEBUG [AWT-EventQueue-0] o.m.h.c.s.WalletService - Adding in 3 BIP70 payment data rows 
```
It's suspicious that the `WalletService` is performing non-UI work on the EDT.

This was with a standard wallet started with a BIP72 file URL referencing `localhost-signed.bitcoinpaymentrequest`.

**Comment by jim618** [comment]
This is the creation of the WalletDetailEvent, which has a 'total number of payments in'.
There is a cached version of the number of payments (cheaper to return) that most of the time is more appropriate. I'll track down where it is not being used and modify.

**Comment by jim618** [comment]
Just pushed some code that improves this:
+ In MainController there is a delayed check on the transaction status. This now checks the specific tx (it was checking all of them previously)
+ In Send/Request and Payments the update payments code (relatively expensive) is now in an executor service and off the EDT. It's triggered by the SlowTransactionSeenEvent (max 1 per second) so it's still running quite a lot but it's ok - keeps the screen current when syncing.

It's a fixed thread size (1) executor so if, for a big wallet, the refresh takes over a second, later submits will fail fast (bit noisy in the log mind) so the UI should stay responsive.

I've left some debug in the log but I'll take it out once I get bored looking at it.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
