### ISSUE TITLE
Trust status of payment request needs some finishing off

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#474]
The trust status of payment requests isn't quite right.

+ It's not being persisted. I think it needs to be stored as is (a trusted PR today may be untrusted in a month because a cert expires or whatever).
+ I've seen 'this payment request is trusted' but with no recipient. This is confusing to the user as you don't know what's happening or where your bitcoin is going. This could be a test artefact - probably indicates we need some more test vectors. (does bitcoinj have any ?)

**Comment by jim618** [comment]
I've added into the PaymentRequest data the trust status, trust error message and expiration date so these are now persisted 'as shown' to the user.

I've also added another test payment request - taken from bitcoinj

You should see the expiration date and trust status now roundtripping ok after a close/ restart of MBHD.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
