### ISSUE TITLE
Google code shutting down is causing 502 errors during Travis builds

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#475]
Several recent builds have failed as a result of Travis being unable to resolve artifacts delivered via Google Code repositories - in particular the version of ZXing for QR code creation.

As a related issue our GitHub based staging repo is unreliable in Intellij resulting in the need for manual builds from source to take place. Changing the URL resolver to https://rawgithub.com should fix these issues.

**Comment by gary-rowe** [comment]
Ready for review and close. To verify delete or rename the following in your local repo:
* `org/bitcoinj/bitcoinj-core/0.13-alice-develop-SNAPSHOT` - (rawgithub.com)
* `org/multibit/hd/hardware/` - (rawgithub.com)
* `com/google/zxing` - (Maven Central)

Attempt "Rebuild All" within Intellij (it might fail). A Maven build should restore them correctly.

Ready for review and close.

**Comment by jim618** [comment]
Delete the artifacts mentioned and rebuilt usng 'mvn clean install'. I could see it pulling in the artifacts and it built fine.

Closing.
