### ISSUE TITLE
Trezor hard wallet does not (always) have EarliestKeyDate set : Repair fails

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#476]
I saw yesterday a Trezor hard wallet not repairing correctly.
It looked like it was performing a fast catchup to, roughly, today so wasn't picking up its transactions.

It might be that it is having it's 'earliest key date' set to NOW (correct for a new wallet, not an extant one). but it needs investigation.

**Comment by gary-rowe** [comment]
Agreed. I've seen a couple of suspicious "reset to earliest key date" occuring from wallets that were doing a long catch up.

**Comment by jim618** [comment]
Changes required to fix this:
+ Ensure Trezor hard wallet seed has creation date set to 'earliest possible HD wallet' when it is first created.
+ Fix roundtripping of Trezor hard wallets (seed creation date was being lost)
+ Ensure Trezor wallet repair switches off fast catch up. (Extant Trezor wallets will have incorrect seed birthdays so fast catchup is unreliable)
+ On completion of Trezor sync, set seed birthday to be date of earliest tx (minus 1 day for good measure) so future repair wallets choose a later replayDate.

**Comment by jim618** [comment]
Pushed code to both bitcoinj-alice and multibit-hd to implement all 4 points above.

You can test it by renaming the wallet dir for a Trezor hard wallet. It should then do a sync (slow - 30 mins approx). Once complete a repair wallet will then only go back to the day of the earliest tx (minus a day) so will be much quicker.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified this is working.

Closing.
