### ISSUE TITLE
Require cacerts file from Java 8 Windows edition to act as baseline

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#477]
This provides most recent list of trusted certificates to assist with verification of trust chain in the Payment Protocol, and acts as a good baseline for the `SSLManager` to use.

(We should also rename `SSLManager` to `TLSManager` given our protocol support).

**Comment by gary-rowe** [comment]
Added the Windows `cacerts` file giving a comprehensive set of trusted entities to act as a baseline for verifying PKI on PaymentRequests from common sites. Improved detection of untrusted CAs.

To verify do the following:
* start MBHD with a command line reference to `mbhd-core/src/test/resources/fixtures/payments/pki_test.bitcoinpaymentrequest` 
* observe that the payment request is trusted

Ready for review and close.

**Comment by jim618** [comment]
Tested with pki_test - works fine. Closing
