### ISSUE TITLE
Edit history requires copy facility of read only data

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#479]
Currently the Edit History screen shows a label that does not support copy to clipboard. This would probably be better shown as a read only text field like other UI elements elsewhere.

This feature would be useful to assist users in quoting alert messages.

It would also be handy to show the event time stamp in local time.

**Comment by jim618** [comment]
Bumped to Release 0.2 as not critical for initial release

**Comment by jim618** [comment]
As history has now been removed no longer relevant.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
History is gone. Closing.
