### ISSUE TITLE
Bump bitcoinj-alice to latest bitcoinj - evaluate sync speed ups

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#480]
There are some sync speed ups (discussed on the bitcoinj mailing list) that are definitely worth evaluating

**Comment by jim618** [comment]
Pushed code to bitcoinj-alice and mbhd - updated from bitcoinj as of earlier this week.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Code review of Alice changes looks good to me.

Closing.
