### ISSUE TITLE
BIP70: Why can't we see the owner of the certificate in the Payment Request Details view?

### ISSUE THREAD

**Issue by ollekullberg** [bitcoin-solutions/multibit-hd#481]
Isn't one of the ideas behind BIP70 that the user should be certain that he gets the info from the correct domain? For this URL I get the screen below: bitcoin:1AhN6rPdrMuKBGFDKR1k9A8SCLYaNgXhty?r=http://dblsha.com/payreq/NjhiYz&amp;amount=0.01

![bip_70](https://cloud.githubusercontent.com/assets/201249/6824338/a80c10c2-d2f1-11e4-9403-1d166bea2957.png)

Can't see dblsha.com anywhere?

**Comment by gary-rowe** [comment]
In this instance dblsha is only acting as an online repository for the payment request. The PKI verification data is held in the payment request and, if trusted and validated, then it will be shown the to the user in the Name field.

Try deleting the `mbhd-cacerts` file in the Application directory (e.g. ~/.MultiBitHD/mbhd-cacerts) and trying again with a properly signed payment request. Here is a [good example](https://github.com/bitcoin-solutions/multibit-hd/blob/develop/mbhd-swing/src/test/resources/fixtures/payments/pki_test.bitcoinpaymentrequest?raw=true). 

If you've used the installer you should be able to simply double click the file to open MultiBit HD.

**Comment by gary-rowe** [comment]
I think this issue can be closed now.
