### ISSUE TITLE
Store Payment and PaymentACK locally

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#482]
The `Payment` contains a note from the user to the merchant in addition to outputs belonging to the wallet that can be used for refunds. The `PaymentACK` serves as proof of receipt from the recipient and needs to be stored.

**Comment by jim618** [comment]
The BIP70 Payment and PaymentACK objects stored in the PaymentRequestData are now being stored as protobuf files.
I am storing everything BIP70 related in 
/payments/bip70
as files:
<uuid>.paymentrequest.aes
<uuid>.payment.aes
<uuid>.paymentack.aes

Note that this is a BREAKING CHANGE as prviously the payment requests just had the extension '.aes'. I think this is worth doing now as it's basically just the two of us with extant payment requests and it is clearer and more extensible if 'other stuff' comes along.

The test to look at/ run is:
WalletManagerTest#testCreateBIP70PaymentRequest

Awaiting review and closing

**Comment by gary-rowe** [comment]
Made a few adjustments after code review. The unit test looks fine and persists the files. Next step is to hook it up to the UI.

Closing.
