### ISSUE TITLE
Link Payment and PaymentACK to Payment on the UI

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#483]
When reviewing a Payment the transaction details should show the contents of both the BIP70 `Payment` and the `PaymentACK` to give the user a complete picture. 

BIP70 indicates that the refund option remains open for 2 months so it might be worth putting a "countdown to expiry" in a friendly form (2 days -> 16 hours -> 3 seconds -> expired).

**Comment by gary-rowe** [comment]
This requires an interim code review to verify that it is going in the right direction. There are still plenty of TODOs outstanding.

**Comment by jim618** [comment]
Looks fine so far. 
Still plenty to do to hook everything up but it's a good start.
Moved back to 'In progress'.

**Comment by gary-rowe** [comment]
Here is the use case covering the UX of paying a PaymentRequest.

1. User acknowledges the alert and sees the PaymentRequest display in Send Bitcoin wizard
1. After reviewing user can click "Cancel" but decides to click "Next" to proceed (no special button in the view any more)
1. User is taken direct to confirmation screen
1. User optionally enters private notes and then their password
1. User clicks "Send" and sees the standard report view with "Cancel" (enabled) and "Next" (disabled) buttons. Clicking "Cancel" closes the wizard but does not stop an ongoing broadcast. See failure handling section for details on this.
1. The send is successful. "Next" enables and "Cancel" disables to force a single path.
1. User clicks "Next" and sees the memo view with text area and enabled "Next" button
1. User optionally enters a memo, clicks "Next" and sees a final report view with enabled "Finish" button
1. The Payment is persisted immediately (failure count of 0)
1. Background operation with on-screen updates to report view (Payment sent OK, PaymentACK received OK with optional memo from merchant shown in read-only field with copy support)
1. If a PaymentACK is received it is persisted along with the others
1. If the Payment or PaymentACK fails then the Payment failure count is incremented by 1
1. User clicks "Finish" and wizard closes.

Handling failures

If the user experiences a failed Tx broadcast they can click "Cancel" to escape. This is treated internally as "did not try to pay" to keep handling simple. No Payment or PaymentACK is stored.

If Payment or PaymentACK fails then further attempts to re-send Payment are made at wallet unlock. Each failure causes the failure count to increment by 1 up to a maximum of 3. If the PaymentRequest has an expiry time then it is respected in this process. To allow for manual re-send of the Payment, a "Fix this" button is available next to the status of "Not acknowledged by merchant" on the PaymentDetails view.

**Comment by jim618** [comment]
I've put in new screens to support the Payment memo and Payment ACK memo.

A few changes from the notes above:
+ The initial 'show payment request screen' is in the Payments wizard - I've left it in there and so it still has the  'in panel' button that fires up the Send wizard.
+ On the Send Report I haven't put in a 'Cancel' but a 'Finish'. 'Cancel' suggests you can cancel the send of the tx but it is too late baby - the bitcoin is out in the network.

The hook up to events/ PaymentProtocolService / persistence isn't started yet - this is all GUI work.

Screenshots:
![Uploading Screen Shot 2015-04-03 at 13.49.16.png . . .]()

![Uploading Screen Shot 2015-04-03 at 13.49.23.png . . .]()

![Uploading Screen Shot 2015-04-03 at 13.49.34.png . . .]()

![Uploading Screen Shot 2015-04-03 at 13.49.42.png . . .]()

For the non-bip70 sends the screens are unchanged.

**Comment by jim618** [comment]
Screenshots aren't uploading. Oh well.
Try out the 'pay to MultiBit donations payment request' and try it out for real.

**Comment by jim618** [comment]
![screen shot 2015-04-03 at 13 49 16](https://cloud.githubusercontent.com/assets/919427/6987123/0b5d473a-da3c-11e4-9480-52f06689702c.png)

![screen shot 2015-04-03 at 13 49 23](https://cloud.githubusercontent.com/assets/919427/6987131/199984a8-da3c-11e4-8672-4d47d652c3b8.png)

![screen shot 2015-04-03 at 13 49 34](https://cloud.githubusercontent.com/assets/919427/6987137/235efa18-da3c-11e4-8636-b901f33ece31.png)

![screen shot 2015-04-03 at 13 49 42](https://cloud.githubusercontent.com/assets/919427/6987150/34e0ceec-da3c-11e4-843c-f73522ff2102.png)

**Comment by gary-rowe** [comment]
Just a quick note on the use of "Cancel" in the Send Progress report. It should only be present for BIP70 and initially disabled along with "Next". If the broadcast fails then it enables and "Next" remains disabled, if the broadcast succeeds it remains disabled but "Next" enables.

**Comment by jim618** [comment]
The Cancel cannot be initially disabled and then enabled on a fail as a send does not necessarily fail - it can just 'take forever'. If the Cancel is thus enabled it gives the impression you can cancel the tx send, which you cannot.

That's why I put in a finish, as you can Finish at any time and it is the same as the non BIP70

**Comment by jim618** [comment]
Also, you don't really need both Cancel and Finish on the display of the Payment Request - they both do the same think. Suggest we remove the cancel

**Comment by jim618** [comment]
I've put the cancel back onto the Send Confirm screen as per your notes for BIP70. You need something to escape if things don't work right (e.g. not enough money).

There are probably some exception paths to sort out but the sunny and rainy day paths should all be working now.
Awaiting interim review

I'll have a play with the test Payment Protocol Service to harden it but it's worth looking at now.

**Comment by jim618** [comment]
I have added some fixtures to PaymentProtocolHttpsServer so that MBHD can consume them but haven't got the certs to work.
I add the same fixture twice in the PaymentProtocolhttpsServer#main twice. If I consume it in main method in PaymentProtocolHttpsServer it works fine but if I consume it in MBHD I get:

![screen shot 2015-04-05 at 13 15 49](https://cloud.githubusercontent.com/assets/919427/6996794/4e8a072c-db96-11e4-9671-538afc1c679d.png)

I've tried putting the 'mbhd-cacerts" with the localhost from the test fixtures into the wallet data dir but that does not work. Same error.
It is definitely talking to the PaymentProtocolHttpsServer as I see a stack trace on the server. as well as MBHD. The error is:

```
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1959)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
```
Any ideas ?

**Comment by gary-rowe** [comment]
Yeah. Look at the payment protocol test to see mbhd - cacerts - with -
localhost in action.

**Comment by jim618** [comment]
Yeah I have it working in PaymentProtocolHttpsServer#main just not in MBHD
Must be the cert store.

**Comment by gary-rowe** [comment]
Verified the screens. Still need a real test against an endpoint (see #491).

**Comment by jim618** [comment]
Screenshots for the completed usecase:

![screen shot 2015-04-09 at 15 09 21](https://cloud.githubusercontent.com/assets/919427/7068556/12a7a952-decb-11e4-921d-35cda630c603.png)

![screen shot 2015-04-09 at 15 09 29](https://cloud.githubusercontent.com/assets/919427/7068559/17a552ba-decb-11e4-8a68-68cd0a422444.png)

![screen shot 2015-04-09 at 15 09 40](https://cloud.githubusercontent.com/assets/919427/7068560/1cd475b8-decb-11e4-8aaf-56f7e2a3b8f6.png)

![screen shot 2015-04-09 at 15 09 56](https://cloud.githubusercontent.com/assets/919427/7068562/20ef0000-decb-11e4-8c61-c8ab430e32c9.png)

![screen shot 2015-04-09 at 15 10 09](https://cloud.githubusercontent.com/assets/919427/7068564/245704cc-decb-11e4-9ac1-bf657b946839.png)

![screen shot 2015-04-09 at 15 10 17](https://cloud.githubusercontent.com/assets/919427/7068568/27f39276-decb-11e4-85cd-d8dc0a201c44.png)

**Comment by jim618** [comment]
The easiest way to test this is:
1) Start up the PaymentProtocolHTTPSServer. This runs on localhost:8443
2) Fire up MBHD with the command line parameter: file:///<project dir>/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/localhost-signed.bitcoinpaymentrequest
3) Run through the use case from the alert

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working (after some fiddling around to get a localhost PKIX working).

Closing.
