### ISSUE TITLE
Enable bitcoinj to find a local Bitcoin Core node

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#484]
As suggested by this thread:
https://bitcointalk.org/index.php?topic=999745.0

change peerGroup.setUseLocalhostPeerWhenPossible(false) in PeerGroup creation to be true.

**Comment by jim618** [comment]
Changed PeerGroup creation flag to useLocalHostWhenPossible.

Checked that it doesn't regress when no Core node is available locally but I don't have a Bitcoin Core locally to cannot check it actually does anything.

Awaiting review (BitcoinNetworkService create new peer method) and closing

**Comment by gary-rowe** [comment]
Code review looks fine. See a2ae8f68c9fe6b5898dfc4182805dd431f5f0fdd for commit.

Closing.
