### ISSUE TITLE
Provide fallback link when purchasing a Trezor

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#485]
In the client the Buy Trezor function should contain a hard coded direct link as a fallback just in case MultiBit.org is down for some reason. This is in addition to the MultiBit.org lookup.

**Comment by jim618** [comment]
We'd only have a direct affiliate link at the moment (when it' set up) so this doesn't need to be in beta 8.

**Comment by jim618** [comment]
Moved to Release 0.1

**Comment by gary-rowe** [comment]
This has been in place for some time now.

Closing.
