### ISSUE TITLE
Alert does not clear when X is clicked

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#486]
I just saw this alert which did not clear (disappear) when the X was clicked.
Nothing in the log
![screen shot 2015-03-31 at 11 57 13](https://cloud.githubusercontent.com/assets/919427/6917525/2f18116a-d79d-11e4-8447-4797f1172fbc.png)

**Comment by gary-rowe** [comment]
Anything in the History?

**Comment by jim618** [comment]
Nothing.

**Comment by gary-rowe** [comment]
Looks like it should be using `ControllerEvents` but is actually going direct to `ViewEvents` thus bypassing the history and other logs. See `MainController#1489` and `TransactionDetailPanelView#188` which will both need to be modified to use `ControllerEvents`.

**Comment by jim618** [comment]
I have updated MainController and TransactionDetailPanelVie accordingly.
Tested by temporarily jamming in a 'true' in MainController#1501.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. 

Closing.
