### ISSUE TITLE
Ensure MBHD works with latest Trezor firmware

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#487]
There i a new version of firmware to be release week beginning 30 Mar - need testing.

**Comment by jim618** [comment]
GetPublicKey will be PIN protected in Trezor 1.3.3 so this will need an update to multibit-hardware and MBHD

**Comment by jim618** [comment]
Note that as of Sunday 5th April mytrezor.com is still dishing out firmware 1.3.1 i.e. 1.3.3 is not released yet. (1.3.2 was skipped).

**Comment by jim618** [comment]
Trezor 1.3.3 was released today.
I upgraded one Trezor to 1.3.3 and successfully sent and received some bitcoin.
Also tried it out with a Trezor on 1.3.1 and that still sends ok.

Closing.

**Comment by gary-rowe** [comment]
Verified with my upgraded Trezor for following use cases:

* send with and without PIN
* empty with and without PIN
* unlock with and without PIN on master public key

Issue #499 covers some minor nits but we're good for the critical path.
