### ISSUE TITLE
Paste (in new Contact, bitcoin address) uses ctrl-V on a Mac

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#488]
Whilst creating a contact on a Mac I noticed that the paste for (at least) the bitcoin address is using ctrl-V and not command-V.

**Comment by gary-rowe** [comment]
Looks like the `focusInputMap` has been moved during our startup optimisations. It needs to be immediately after the setting of the Nimbus LaF and before any components are created. 

Ready for review and close.

**Comment by jim618** [comment]
Confirmed COMMAND-V now pastes (ctrl-V is still working which is fine

Also checked COMMAND-C works.

Closing.
