### ISSUE TITLE
Cannot adjust 'Notes' column in History

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#489]
You cannot shrink the 'Notes' column in History to see more of the Descriptionn

**Comment by jim618** [comment]
All the columns in the History table (actually all tables) are now adjustable.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Settings are preserved between wallet switches in the same session, but not through a restart which is OK at this stage.

Closing.
