### ISSUE TITLE
Inform user when a passphrase-enabled Trezor is detected

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#490]
At present when a passphrase-enabled Trezor is detected MultiBit HD locks up. The user should be given a message indicating that a device with passphrase is not currently supported, possibly with a link to the help detailing why this is currently the case.

This is related to [MultiBit Hardware #4](https://github.com/bitcoin-solutions/multibit-hardware/issues/4)

**Comment by jim618** [comment]
We could bump this to Beta 9 in order to expedite Beta 8 (and get the Trezor firmware changes out earlier)

**Comment by gary-rowe** [comment]
I'll have more time to work on these over Easter and I think it'll be quick to implement (essentially an error path to the report screen). If it looks like more than 2hrs effort I'll bump it.

**Comment by jim618** [comment]
Ok. Always nice to clear stuff earlier where possible.

**Comment by gary-rowe** [comment]
Fairly hefty changes needed to meet this requirement. The decision to not support passphrase is essentially an "unsupported configuration" failure. At the time there was no good way to present this (it wasn't a security issue) so I've renamed security event and service handling throughout as "environment". This allows more flexibility when creating popovers so that the title can be changed between a "security alert" and simply "information".

Here are some screen shots of the new behaviour:

![screen shot 2015-04-02 at 21 15 30](https://cloud.githubusercontent.com/assets/342133/6973510/44943bd0-d983-11e4-8eda-1543d93f7e6c.png)

![screen shot 2015-04-02 at 21 16 20](https://cloud.githubusercontent.com/assets/342133/6973541/701d2230-d983-11e4-85c7-a02eecec5072.png)

I've added a FEST test with supported firmware but unsupported configuration using our Trezor fixtures.

Ready for review and close.

**Comment by jim618** [comment]
It is almost there but not quite 100%.
I tried plugging in a Trezor (with password) on the Credentials screen and I just see the 'Communicating with Trezor screen forever'. The Trezor is asking me to enter the password on the computer.

I see an error in the log:
```
[2015-04-04 11:23:21,074] DEBUG [safe-fixed-hardware-wallet-events-0] o.m.h.h.c.e.HardwareWalletEvents - Completed 'hardware wallet' event: SHOW_OPERATION_FAILED 
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47)
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.showOperationFailed(CredentialsWizardModel.java:306)
	at org.multibit.hd.ui.views.wizards.AbstractHardwareWalletWizard$8.run(AbstractHardwareWalletWizard.java:292)
```

If I plug in the Trezor AFTER I have gone through the credentials wizard I see a yellow alert telling me that the hardware is unsupported correctly.

If I do a switch wallet with the trezor still plugged in I see the yellow popup warning saying the same.

If the Trezor is plugged in BEFORE MBHD starts I see the popup warning correctly.

It is just if the Trezor is plugged in at the very first showing of the 'Enter Password' screen that seems problematic.

**Comment by jim618** [comment]
I did an update from github today to retest if a password protected Trezor is detected on the first showing of the credentials now. It's not. You still get a 'communicating with Trezor' forever.

**Comment by gary-rowe** [comment]
Added supporting to code to MBHW for passphrase request event. This makes it easier to handle rejection in MBHD.

To verify ensure you have the latest MBHW (pushed to staging repo). Start MBHD and proceed to password entry screen. Attach passphrase enabled Trezor and observe popover with unsupported message. Dismiss message and proceed to unlock device. Observe no further Trezor messages.

Ready for review and close.

**Comment by jim618** [comment]
Successfully tried inserting a passphrase protected Trezor at the following times:
+ Before start of MBHD
+ On first appearance of credentials wizard
+ After password entered and wallet unlocked.

In all cases the 'Unsupported blah blah' message came up.

Closing
