### ISSUE TITLE
The Payments wizard (transaction drill down) needs to show Payment memo and Payment ACK memo

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#494]
Probably just combine them onto one panel, not two as in the Send wizard which is done because there is a server round trip in between

**Comment by jim618** [comment]
I've added a panel onto the Payments wizard to show the memos from the Payment Protocol, if available.
It looks like this:

I cannot show you it populated as I haven't got a payment server working yet with a successful exchange.

**Comment by jim618** [comment]
Needs reviewing to check memos actually appear once #483 is proven with a running payment protocol server.

**Comment by jim618** [comment]
![screen shot 2015-04-06 at 13 10 31](https://cloud.githubusercontent.com/assets/919427/7004218/c0532d6a-dc5f-11e4-98d3-58037dbfc12f.png)

**Comment by gary-rowe** [comment]
The correct plural of memo is "memos" but perhaps "notes" is better visually and consistent with regular users expectations.

**Comment by jim618** [comment]
I've changed it already to 'memos'.

We might as well keep it as memo as that is what it is called in the protobuf so (most probably) is what other implementations will call it.

**Comment by gary-rowe** [comment]
Memo in the context of an invoice seems rather technical to me. Notes is much more accessible to ordinary folk and is used throughout the rest of the application. Can we change it to notes and then if other wallets use memo we'll just update accordingly?

**Comment by jim618** [comment]
Sure no problem.

**Comment by jim618** [comment]
Screenshot with persisted Payment and PaymentACK notes:
![screen shot 2015-04-09 at 14 59 41](https://cloud.githubusercontent.com/assets/919427/7068595/59e829d6-decb-11e4-967c-af99c59a3fd0.png)

**Comment by jim618** [comment]
The easiest way to test this is:
1) Start up the PaymentProtocolHTTPSServer. This runs on localhost:8443
2) Fire up MBHD with the command line parameter: file:///<project dir>/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/localhost-signed.bitcoinpaymentrequest
3) Run through the use case from the alert

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. 

One observation: in the case where the Payment send fails the note is not recorded. This might be better entered as "Failed to send" but actually just shows up as blank in both fields. This is a corner case that can be picked up in Release 0.1.

Closing.
