### ISSUE TITLE
Payment request expiry date seems to be set to now

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#495]
I think the payment request parsing of the 'Expiry date' is wrong - I've seen it set to 'now' in the FEST tests, when I'm running it as a parameter on the command line.

**Comment by gary-rowe** [comment]
This is caused by a null date being passed to `PaymentRequestData` (line 114) from the payment session. I've interpreted this as "never expires" and set the actual expiry date to be 31 Dec 2199 which is far enough into the future for me not to care.

Ready for review and close.

**Comment by jim618** [comment]
Confirmed expiry date set to 31 Dec 2199.

Note to @JimsGreatGreatGreatGreatGreatGreatGreatGreatGrandDaughter - stop messing about with that DarkMatter drive and update the ExpiryDate constant. Thanks.
