### ISSUE TITLE
In transaction details screen ENTER no longer presses Next

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#496]
Something changed recently - some of the nexts were not enabled in the Transaction details wizard.
I've fixed that but ENTER no longer presses next.

**Comment by gary-rowe** [comment]
Most likely culprits: `SwingUtilities.invokeLater()` getting called incorrectly or `requestFocusInWindow()` missing on Views.

**Comment by jim618** [comment]
I've updated the PaymentsWizard screen (as per your suggestions).
You can now press ENTER through all the screens.

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
