### ISSUE TITLE
Suppress 'There is a new Trezor' alert message if it's the same Trezor as current wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#498]
If the user (for whatever reason) unplugs and plugs in a Trezor when THAT trezor wallet is being displayed, suppress the 'There is a new trezor' alert.

I thought we had done this already but I saw it just now.

**Comment by gary-rowe** [comment]
I *think* we include the device ID in the `equals()` which gets reset during re-attach.

**Comment by jim618** [comment]
Yeah it was using devideId rather than label in t he comparison
Bumped back to Beta 8.

I've fixed this - it'll go in once I retest it all.

**Comment by jim618** [comment]
Checked that unplugging the same Trezor does not show an alert.
Also checked plugging in a _different_ Trezor does show an alert.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
