### ISSUE TITLE
Trezor firmware 1.3.3 changes the amount display during sign

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#499]
The new display shows the total amount including fees:
```
Really send
0.00794 BTC
from your wallet?
Fee included:
0.00003 BTC
```
The previous display was:
```
Really send
0.00791 BTC
from your wallet?
Fee will be:
0.00003 BTC
```

**Comment by jim618** [comment]
Shall we just make this show the "1.3.3" text ALWAYS rather than make it conditional on the firmware release ? On KISS grounds.

**Comment by gary-rowe** [comment]
Yeah. Almost everyone will upgrade at this stage, especially if we provide an outdated firmware alert.

**Comment by gary-rowe** [comment]
I've added support for a "deprecated firmware" alert. This will provide an incentive for users to upgrade their firmware and also sets up an expectation of mild incompatibility: such as why the display is different on their device to that showing in MBHD. 

![screen shot 2015-04-08 at 16 17 59](https://cloud.githubusercontent.com/assets/342133/7049879/1c0b7250-de15-11e4-97ff-24f6422c3159.png)

**Comment by jim618** [comment]
good idea

**Comment by gary-rowe** [comment]
Updated the text to match the 1.3.3 firmware. See screenshot:

![screen shot 2015-04-08 at 17 55 28](https://cloud.githubusercontent.com/assets/342133/7050353/c47a3f4a-de18-11e4-8060-b5a1f6712a67.png)

Ready for review and close.

**Comment by jim618** [comment]
Confirmed text matches what is on the Trezor screen for both Send bitcoin and Empty wallet.
Closing.
