### ISSUE TITLE
Sign message for a Trezor wallet is asking for a password

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#500]
If you have a Trezor plugged in the 'Sign message' is asking for a password (which you don't know for a Trezor wallet) rather than asking the Trezor to sign it.

Marked as Beta 8 but we might want to slip it to the Release 0.1

**Comment by gary-rowe** [comment]
This should be relatively straightforward to implement. If it takes more than a morning then I'll bump it to Release 0.1.

**Comment by gary-rowe** [comment]
I've added preliminary support for Trezor message signing. To verify do the following:

1. Unlock a hard wallet
1. Use Payments/Request Bitcoin to obtain an address
1. Enter short text message
1. Click Sign message
1. Confirm on the device
1. Observe "signing was successful" message

There are some limitations:

* there is no separate panel view providing a Trezor display which is a break away from the standard UX
* only address 0/0 is supported regardless of what is entered
* there may be an upper limit on the length of the message to be signed which I haven't explored yet
* the PIN support is currently untested

Ready for interim review.

**Comment by gary-rowe** [comment]
Added support for PIN (usual re-attach to trigger) and for arbitrary receiving address. Both panel views will now suggest the current receiving address for signing to save complex lookup operations but can be overridden if necessary. 

I've verified long messages are OK with the Trezor and result in a truncated screen display so I'll add a display panel for UX consistency.

**Comment by jim618** [comment]
It all works except if you detach and reattach you can get a 'Trezor is invalid' in the log. (And nothing on the screen). This is a bit of an edge case so am closing.

**Comment by gary-rowe** [comment]
'Old yer 'orses!  :-)

Still have some more to come with the display screen...

**Comment by jim618** [comment]
Ha Ha

**Comment by gary-rowe** [comment]
OK, I've added the confirm panel now. 

Ready for review and close.

**Comment by jim618** [comment]
Works all very nicely. 
Closing.
