### ISSUE TITLE
Display info during initial loading 

### ISSUE THREAD

**Issue by sipak** [bitcoin-solutions/multibit-hd#502]
It takes up to 15 seconds for MultiBit 0.7 to start (Linux / Windows) after users clicks icon. "Loading" info would be nice to inform user that everything is going alright

**Comment by jim618** [comment]
We've put in a splash screen in to Beta 8 to 'fill in the time' yes.
Also shaved a couple of seconds off the start up time.
Good usability point..
Closing.
