### ISSUE TITLE
Fiat amounts aren't right

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#503]
The fiat amounts for tx don't look right.
Look at the 3 donations for 10 mBTC in this screenshot:

![screen shot 2015-04-09 at 22 16 43](https://cloud.githubusercontent.com/assets/919427/7077121/47061b4e-df06-11e4-8be4-e69ef3b76f6d.png)

**Comment by jim618** [comment]
Note that these were all BIP70 payments

**Comment by jim618** [comment]
this was due to the changeAddress not being specified in the SendRequest (and hence getting counted in the fiat equivalent calculation).
Fixed and pushed.

(I have also updated the BIP70 screenshots in the multibit blog article as these were wrong too).

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
