### ISSUE TITLE
Mark Trezor firmware before 1.3.3. as not supported

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#504]
It is maked as deprecated now but needs to be marked as 'Not supported' as it is a mandatory security update.

**Comment by jim618** [comment]
![screen shot 2015-04-11 at 11 57 42](https://cloud.githubusercontent.com/assets/919427/7101155/5bd79556-e042-11e4-9de8-696e35eb939d.png)

Updated multibit-hardware to mark earlier than Trezor 1.3.3 as unsupported.
Checked with Trezors version 1.3.1 and 1.3.3

Ready for review and closing

**Comment by gary-rowe** [comment]
Verified working with MultiBit Hardware 0.4.0.

Closing.
