### ISSUE TITLE
Change output moved from ok to unavailable

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#505]
I just saw a change output change from 'being available for use' because it was an output on a tx sent by MBHD to unavailable until confirmed
Screenshot:
![screen shot 2015-04-13 at 21 14 08](https://cloud.githubusercontent.com/assets/919427/7124635/974e101a-e222-11e4-94dc-987094520b8b.png)

I expect the change will become available on confirmation.

Could be something to do with whether the tx is marked as 'sent by self' or 'network'. Possibly being overwritten when the tx comes in from the network

**Comment by jim618** [comment]
Everything is as expected after confirmation:
![screen shot 2015-04-13 at 21 19 58](https://cloud.githubusercontent.com/assets/919427/7124683/e6010da2-e222-11e4-91e0-571a75d8d5af.png)

**Comment by jim618** [comment]
You also see this if you have some tx being sent, close down MBHD and immediately start it up again.
Suggests the txes coming in from the network are being 'dominant'

**Comment by jim618** [comment]
Since the update to the bitcoinj code in #480 I haven't seen this problem occurring - I cannot replicate this.

Awaiting review and closing

**Comment by gary-rowe** [comment]
I can't replicate this and the fix in the bitcoinj should fix it.

Closing.
