### ISSUE TITLE
Remove 'flicky' progress bar

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#507]
The sync progress bar is a bit 'flicky' when MBHD is finding peers.
It disappears whilst a Peer is newly seen.

Change so that it says visible on Peer change events

**Comment by jim618** [comment]
Fixed flickiness on Peer related ProgressChangedEvents in FooterView.
Awaiting review and closing

**Comment by gary-rowe** [comment]
Fix removes capability to instantly hide the progress bar. However I don't think we ever used that in the end so it's fine.

Closing.
