### ISSUE TITLE
Productionize BRIT server

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#508]
Make sure backups of key data are made regularly.
Check operation In Real Life is what we expect

**Comment by gary-rowe** [comment]
This should be done in line with #168 work.

**Comment by jim618** [comment]
Switched to @gary-rowe as this is similar to error-reporting-service work

**Comment by gary-rowe** [comment]
I'll raise a couple of [issues on its repo](https://github.com/bitcoin-solutions/brit-service) to cover the ongoing work here.

**Comment by gary-rowe** [comment]
Marking as awaiting issue since [BRIT Service #4](https://github.com/bitcoin-solutions/brit-service/issues/4) should cover these changes.

We can close this issue when both BRIT and Error Reporting services are:

* released as 0.1
* verified operational for MBHD Release 0.1
* included in server backup processes

**Comment by jim618** [comment]
I just tried out the BRIT server by creating a new wallet.
It worked OK but I was expecting to see 50 addresses in the returned message, whereas I saw:
```
[2015-05-20 15:09:22,803] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.u.HttpsUtils - Attempting to post 642 bytes to URL https://multibit.org/brit 
[2015-05-20 15:09:25,004] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Matcher response (encrypted):160 bytes 
[2015-05-20 15:09:25,008] DEBUG [safe-fixed-create-wallet-0] o.m.h.b.s.FeeService - Matcher response (decrypted):
1
1432134565453
1ESmJ8q89QSN9WUyR9ewydbmgBFQb1LipT
1CTf4coo7R6ZqyTrukYK1pGopx8DrnBhE3
1H8Mz5vzYZPvWFnRhkGzTeNZLxmHUHNJ6a
17WZTWMwNZwusaPfJz5VqCUiBifnsjh43b
```

It is thus working but perhaps the new BRIT service code is not deplayed to multibit.org yet ?

**Comment by gary-rowe** [comment]
Correct in that it hasn't been deployed yet. 

I want to verify it working locally first - you can use the contents of `src/test/resources/matcher` under `var/brit/matcher` if you need a test scenario (if will fail the healthcheck as its using the test key).

**Comment by gary-rowe** [comment]
Assigning this to @jim618 in order to get the backup process on the servers prepped for Release 0.1.

**Comment by gary-rowe** [comment]
Backup process is now in place so closing this.
