### ISSUE TITLE
On cold start ask user to attach Trezor device in welcome wizard

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#509]
User feedback has indicated that the welcome wizard should include a clear indication to attach a Trezor device at the options screen. This would help to avoid confusion during the initial start process when the user is still going through the learning curve.

**Comment by gary-rowe** [comment]
This was also noted by @crwatkins.

**Comment by jim618** [comment]
Agreed. It is not obvious users need to plug in their Trezor (for the first time).

**Comment by jim618** [comment]
I've updated the WelcomeWizard to prompt the user to insert their Trezor.

Rather than add the text on the "Select option' page I have put it one screen earlier (Languages). I have also moved the 'MBHD needs a secure environment' one screen earlier (to the Licence screen) too as the Languages screen was becoming a bit incoherent.

I have tried it out with initialised Trezor / no Trezor / wiped Trezor.
The only imperfection is that if the user does the following sequence:
1) inserts trezor as requested on Language screen.
2) Clicks next
3) Clicks previous
4) Removes Trezor and clicks next
5) Screen incorrectly thinks Trezor is still present. I've debugged it and the HardwareWalletService still thinks the Trezor is ready. 

This is quite off-the-beaten path so I think it is acceptable for now.

I'll post the screen shots a bit later - cannot upload in Starbucks !

**Comment by jim618** [comment]
![screen shot 2015-04-23 at 15 36 36](https://cloud.githubusercontent.com/assets/919427/7301864/4c3627d0-e9dd-11e4-8c76-139ff545a295.png)

![screen shot 2015-04-23 at 15 49 01](https://cloud.githubusercontent.com/assets/919427/7301878/5b649ebc-e9dd-11e4-8e00-245e8946ce07.png)

**Comment by gary-rowe** [comment]
Agreed on the "secure environment". The security note should be the first thing anyone sees.

Disagree on some aspects of "Select Language". This screen is now a bit disjointed. It asks for a language selection, and gives a heads up about a hardware wallet which is conceptually unrelated to language. I'm concerned that we're asking the user to do too much and not leading them enough.

Consider this alternative workflow:

1. "Select language", click Next
1. "Attach hardware wallet" (user optionally plugs in Trezor - device attach/existence detected quickly enough so we can make a decision before user regains the mouse to click Next) Could provide list of currently supported devices + firmware.
1. "Select options" (create/restore etc)

I think having its own interstitial panel view would make the message much clearer to users who are completely new.

**Comment by crwatkins** [comment]
That would have mitigated all of my confusion.  Thanks. Would "If you have a" be better than assuming "To use your"?  That would make the more common path of not having a Trezor require less thought and a more obvious decision.

**Comment by jim618** [comment]
Agreed that a dedicated screen would be clearer.
Also "If you have a Trezor" is clearer language (most people WON'T have a Trezor and can just click Next.

No need to list currently supported devices + firmware - that's just geeky stuff.
If it's not supported we will tell them.

**Comment by gary-rowe** [comment]
I'm in the mood to work on MBHD for a bit (too many REST services recently) so I'll quickly put a first draft in place now.

**Comment by gary-rowe** [comment]
Show the attach hardware wallet screen (rolls in just like the preparation screen so acts as a primer too):
![screen shot 2015-04-23 at 22 06 32](https://cloud.githubusercontent.com/assets/342133/7307811/1aaeb860-ea07-11e4-8890-95af8a4a191f.png)

And if there is a problem with the Trezor the popover appears as expected:
![screen shot 2015-04-23 at 22 18 13](https://cloud.githubusercontent.com/assets/342133/7307810/1aa8642e-ea07-11e4-90ae-98f12e6a5f1a.png)

I've updated the FEST tests for "create wallet en_US" and "create wallet ro_RO". 

To verify prepare a clean application directory and start 'er up then observe:
* attach hardware wallet rolls in after language
* Previous returns to language, Next to standard wallet
* Attach a supported initialised hardware wallet, Next to PIN
* Attach a supported wiped hardware wallet, Next to Create Trezor wallet
* Attach an unsupported hardware wallet (e.g. firmware or passphrase) observe popover

Ready for review and close.

**Comment by crwatkins** [comment]
That would have eliminated any of my confusion with my Trezor.
One note:  I don't think I know what "the history" is or where I would check that.
(like I'm not sure if that is an MB or Trezor concept)

**Comment by gary-rowe** [comment]
Yeah, I noticed that. It's sort of a holdover from earlier work. Consider it gone.

**Comment by gary-rowe** [comment]
Here's the revised popover without the History reference (other popovers within the wallet still have the History reference since it provides useful audit information):
![screen shot 2015-04-23 at 22 41 11](https://cloud.githubusercontent.com/assets/342133/7308158/dffdb27c-ea09-11e4-88fe-13e2000891d4.png)

**Comment by crwatkins** [comment]
OK

**Comment by jim618** [comment]
Nice educational 'Attach hardware wallet' screen.

A bug: When I plugged in a wiped Trezor and click next and then chose the 'Create Trezor wallet' option but it then started up the non-Trezor wallet creation.

**Comment by gary-rowe** [comment]
I've made the screen more interactive to stop people from skipping ahead of themselves. If you plug in the device a message will appear indicating attachment/failure. If you detach the device then the message disappears. 

The text indicates that the user should wait for a message to appear if the device is successfully detected but if they do shoot on ahead and see the wrong wallet screen they can always use Previous then Next to have another go. We cannot know their intentions ahead of time so the Next button must remain enabled.

A wiped Trezor will go straight to the wallet preparation screen, an initialised one will go to the select wallet since the user may want to create/restore.

![screen shot 2015-04-25 at 13 56 18](https://cloud.githubusercontent.com/assets/342133/7332957/5b3b224a-eb53-11e4-90a5-3d053f32bfdf.png)

Ready for review and close.

**Comment by jim618** [comment]
All looks good and smooth - "organic" is the word.
I noticed one gotcha:
+ If the user already has a Trezor attached, they don't get a message saying that a Trezor was attached, which is confusing.

**Comment by gary-rowe** [comment]
OK. I've added a message that will appear if the Trezor is detected while the text is rolling down. I've also added some bold text to encourage the users to wait during initial handshake of the device.

Ready for (another) review and close.

**Comment by jim618** [comment]
Looks good.
Tried it out both with Trezor plugged in before MBHD started and on the 'Attach hardware wallet' itself.

I've pushed a minor layout tweak to avoid flickiness on the 'Trezor is attached' appearing (row constraints in MIG layout).

Closing
