### ISSUE TITLE
Ensure all text supports copy and paste or consider a Copy All facility

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#513]
User feedback from @crwatkins has indicated that many text fields/labels do not support copy/paste operations. In particular the transaction details panel views would benefit from this facility (or perhaps a "Copy All" button similar to the Sign message screen) to assist users when reporting problems.

**Comment by jim618** [comment]
Text fields should be copiable.
A 'Copy All' isn't necessary and just introduces visual clutter.

**Comment by gary-rowe** [comment]
I think the "Copy All" has a valid use case when a user wishes to gather all the relevant information about a transactions into a single "standard" format. They could then send that to a merchant in a signed message with a couple of clicks. 

The button could be placed on the button strip above the table and act on multiple selected Payment rows.

**Comment by jim618** [comment]
This would be used in 1 in a 1,000,000 times but clutters up the UI for everyone.
It's an out of scope use case

**Comment by jim618** [comment]
You'd just send the txid or the blockchain.info URL

**Comment by gary-rowe** [comment]
Closed.
