### ISSUE TITLE
History screen should have a Close button

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#515]
All the other button-driven screens result in a wizard that has Cancel/Finish except History. This has come about due to the migration of History from the sidebar into the Manage Wallet screen. However the UX is inconsistent as a result and was noted by @crwatkins.

To assist with an obvious return to the underlying screen a "Close" button could be added which would also improve accessibility.

**Comment by jim618** [comment]
Agreed with add Close.

**Comment by jim618** [comment]
History has been removed so no longer required.
Awiating review and closing

**Comment by gary-rowe** [comment]
History is gone so closing.
