### ISSUE TITLE
Insufficient funds message during Send is confusing

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#517]
User feedback from @crwatkins indicated that the message shown when a Send is attempted with insufficient funds is too confusing for non-Bitcoiners. It introduces the concept of a "Satoshi" and does not match the currently selected display units.

A better approach would be to parse known exception messages from Bitcoinj and provide a localised representation to be more user-friendly.

**Comment by jim618** [comment]
Agreed it's confusing.
Duplicate of #188 so closing.
