### ISSUE TITLE
More detail on the Verify Network panel view

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#518]
User feedback from @crwatkins has indicated that the Verify Network panel view is made less useful by the lack of supporting information for the data provided. 

Some examples of additional text could be:

* A Peer count of zero indicates a problem with your network (see Help for common solutions)
* A Peer count of 6 or more indicates a healthy connection to the Bitcoin network
* When the block count reaches zero then you are fully synchronized with the Bitcoin network and your current balance will be shown
* If the block count has not moved for a minute or so see the Help for common solutions

**Comment by jim618** [comment]
Verify network is pretty sparse so we can have a sentence of description for each field if we want.

**Comment by jim618** [comment]
Added more descriptive information for 'peer count' and 'blocks left'.
Also added a callout to the 'Verify network help at the bottom (rather than putting technical blurb on screen).

Screen shot to follow (uploading not working).

Awaiting review and closing

**Comment by jim618** [comment]
![screen shot 2015-04-21 at 16 14 51](https://cloud.githubusercontent.com/assets/919427/7256647/49fb8244-e848-11e4-80ae-35f6a7c0ac46.png)

**Comment by crwatkins** [comment]
Looks good to me.

**Comment by gary-rowe** [comment]
And me.

Closing.
