### ISSUE TITLE
Client fees are not reported correctly on Empty wallet (dust output)

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#519]
User feedback from @crwatkins indicated that the client fees were not being reported correctly on the Empty wallet screen. A fee of 2000 satoshis was claimed but not actually added to the final transaction (probably due to dust requirements). It would be better for the wallet to state "No fee will be taken" under these circumstances to avoid being inaccurate.

**Comment by jim618** [comment]
I've fixed this so that the client fee shown on the Empty wallet is actually added to the transaction.
Checked using the transaction details screen and copy/pasting the raw tx into block chain.info/decode-tx.
Checked with both Trezor and non-Trezor wallets.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Minor change to code. Verified working.

Closing.
