### ISSUE TITLE
Rethink the Restore button on the Unlock screen

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#520]
User feedback from @crwatkins has indicated that the Restore button on the Unlock screen is confusing. Perhaps a better approach would be to have two buttons: "Create..." and "Restore..." which both target the welcome wizard but use a different starting panel view. 

This would remove any confusion in the mind of the user about creating a new wallet.

**Comment by jim618** [comment]
In discussions we agreed that better text than what we have at the moment is:
+ I have forgotten my password
+ I want to restore a wallet
+ I want to use an existing wallet

**Comment by jim618** [comment]
Updated in line with this post.
There is now a Create button on the Credentials 'Enter password' screen that takes the user to the 'Create wallet preparation' screen. I have adjusted the 'Select option' lists to remove the previous create option.

Tried it out with various configurations, cold start, warm start, restore, use existing wallet etc and the screen flow what what you'd expect. Probably worth playing with it for a bit to see if I have missed anything though.

I've pushed all the changes so you can review the functionality but still have the FEST tests to do yet.
Will also post some screenshots later

**Comment by gary-rowe** [comment]
The handover between the credentials wizard and the welcome wizard isn't quite working correctly leading to problems with events getting sent to two wizards and causing strange state changes as a result (see #534).

I'll incorporate your updates as I progress with that issue.

**Comment by jim618** [comment]
I've got the FEST tests running cleanly now.
Also added a 'Create wallet' to the Select wallet option screen only on a cold start (where the user won't have a wallet and most likely will want to create one).

Awaiting review and closing.

**Comment by jim618** [comment]
Screenshots:

![screen shot 2015-04-25 at 15 38 43](https://cloud.githubusercontent.com/assets/919427/7334251/1ebbace4-eb86-11e4-8442-b7a93f0df98f.png)
![screen shot 2015-04-25 at 15 39 23](https://cloud.githubusercontent.com/assets/919427/7334252/20166a66-eb86-11e4-8297-b97297533f2c.png)
![screen shot 2015-04-25 at 15 46 33](https://cloud.githubusercontent.com/assets/919427/7334253/226d8a92-eb86-11e4-9877-c6e4ac5d08e8.png)

**Comment by jim618** [comment]
Updated the text on the 'Enter password' screen to reflect that there are now two buttons:
![screen shot 2015-04-25 at 20 30 18](https://cloud.githubusercontent.com/assets/919427/7334425/f1418604-eb89-11e4-82d2-b14043c8177c.png)

**Comment by gary-rowe** [comment]
Works fine. 

One nit: there is no way back to the Unlock screen after starting the Create process without an Exit. It remains possible through the Restore button. Perhaps the Previous button on the wallet preparation screen should be re-instated with a return to the display of the options containing "use existing wallet" presented. It's a bit incongruous, but it gives an escape from accidentally clicking Create.

**Comment by jim618** [comment]
Added Previous button that navigates to the 'Select option' screen.
Also checked the Trezor create wallet preparation screen has a Previous button.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working (soft and hard wallet)

Closing.
