### ISSUE TITLE
When restoring a wallet the timezone is reported as GMT but is actually local

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#521]
When selecting a backup from the dropdown list during Restore the timezone information is incorrect. Local time should be preferred in all cases.

**Comment by jim618** [comment]
I've changed the formatter used in BackupSummaryListCellRenderer. The utcHttpDateFormatter has the string 'GMT' hardwired into it which was causing the problem.

Screenshot of time of restores in 'New York time':
![screen shot 2016-03-04 at 09 52 39](https://cloud.githubusercontent.com/assets/919427/13528983/79c26fb0-e211-11e5-840d-46cc9b619759.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Hmm, not seeing a commit against this...

**Comment by jim618** [comment]
Now pushed

**Comment by gary-rowe** [comment]
When FEST testing this (`StandardFestTests.verifyRestoreWallet_en_US_ColdStart`), I noticed the following error repeated in the logs:

```
[2016-03-04 14:25:26,002] ERROR [NioClientManager] o.b.core.Peer - Failed to walk the block chain whilst constructing a locator 
```
Thoughts?

**Comment by gary-rowe** [comment]
Verified formatting.

Closing.
