### ISSUE TITLE
"Wallet timestamp" should be renamed to "wallet date"

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#522]
User @crwatkins noted with surprise that the wallet timestamp did not change after a few hours. Since a timestamp is normally associated with an instance in time that changes on each refresh a better name for the timestamp field would be "wallet date" which may be more accessible to users and provide a better indication of its purpose.

**Comment by jim618** [comment]
Wallet date would be a bit confusing because there are other BIP32 based wallets (e.g. LightHouse) where their 'wallet creation date' is an actual date. Calling this field 'wallet date' suggests you could type in a date, which you cannot.

How about 'date stamp' to suggest that it is encoded (i.e. a 'stamp') and date related (hence does not change so quickly ?

**Comment by crwatkins** [comment]
As a user, I don't know what the timestamp is for.   I don't know why I wrote it down.  I don't know where I would use it.  I can't parse the numbers to translate to a date for pure information sake.

**Comment by jim618** [comment]
That's kind of the point.
We JUST want you to write it down.

Here is some information: just write it down.
By trying to explain exactly what it is, what the encoding is etc we dilute considerably what the primary message is, which is: Just write it down.

**Comment by gary-rowe** [comment]
Perhaps an accompanying note: "The date stamp makes wallet restore operations faster in MultiBit HD. Please record it alonside your wallet words now."

**Comment by jim618** [comment]
I have renamed timestamp to datestamp. 
Also added explanatory sentence on wallet creation screen.
Screenshot:
![Uploading Screen Shot 2015-04-20 at 14.37.13.png . . .]()


Awaiting review and closing

**Comment by gary-rowe** [comment]
If screenshots aren't working, check that you're not running NoScript, or that you've enabled all the GitHub scripts. Should be a simple drag/drop operation on Mac.

**Comment by gary-rowe** [comment]
Could you have another crack at getting a screenshot here to assist third-party review?

**Comment by jim618** [comment]
![screen shot 2015-04-21 at 12 05 21](https://cloud.githubusercontent.com/assets/919427/7250991/bcae0a2a-e81e-11e4-8d16-eb70e71ae1e9.png)

**Comment by gary-rowe** [comment]
Looks good, apart from one nit: "Your wallet words protects all your bitcoins" is a hold over from our previous use of seed phrase, perhaps a quick update to "Your wallet words protect all your bitcoins".

Paging @crwatkins to review the screenshot :-)

**Comment by crwatkins** [comment]
This screenshot definitely addresses all the concerns I provided.  For newbies, instead of "protects all your bitcoins" which is a little abstract, perhaps "allows you to restore your wallet if..." would be more informative.  Again, this is fine as-is.

**Comment by gary-rowe** [comment]
We did consider the "Allows you to restore your wallet" approach in an earlier iteration but it made the screen rather wordy and user testing indicated that most people didn't read the screen anyway.

**Comment by jim618** [comment]
Looks like I can close this now.

**Comment by gary-rowe** [comment]
Agreed.
