### ISSUE TITLE
Delete request button should not be available if a request is not selected

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#524]
User @crwatkins noted this behaviour on the Payments screen during a review.

**Comment by jim618** [comment]
Needs greying out.

**Comment by crwatkins** [comment]
Consider similar treatment for Undo.  I'm not really sure what I can undo or when I can use it.

**Comment by gary-rowe** [comment]
Undo is a bit more tricky, because it spans the user's entire session with the wallet. They could leave the table screen, do a bunch of operations, come back and click Undo and see their entry re-appear. 

That said, it should be disabled until it actually has an entry in the stack (similar to how the Help navigation buttons work).

**Comment by jim618** [comment]
I have updated the listeners to the 'Delete request' and 'Undo' buttons so that:
+ 'Delete request' is only enabled if you have a payment request selected in the table
+ 'Undo' is only enabled if you have done a delete and there is something on the undo stack.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
