### ISSUE TITLE
Client fees should be separated from transaction fees more clearly

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#525]
User feedback from @crwatkins indicates that the client fees (and the "Payable later" message) could be interpreted to mean a time-locked Bitcoin transaction. There is also the potential conflation with transaction fees. 

Perhaps a simple horizontal line separating the transaction and client fees would be sufficient to frame the information and so remove the confusion.

**Comment by jim618** [comment]
![screen shot 2015-04-20 at 16 28 42](https://cloud.githubusercontent.com/assets/919427/7233710/9455d3f4-e77a-11e4-9dd9-6e77aaafe66f.png)

I've put in a faded dotted line to group the client fee information. Tried various things but this looks the neatest - it shouldn't be too high in the mix.
In the space we have allocated to the client fee info I don't think we can explain what it is so I propose we leave the text as is.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Looks good to me. 

@crwatkins Would you mind chiming in at this point?

**Comment by crwatkins** [comment]
That's definitely less confusing.  Would it be possible to move "Payable later" left any?
The large horizontal white space seems to imply that it may not be associated with the Client fee.
In any case, it's better now.

**Comment by gary-rowe** [comment]
Personally I think the line blocks it out nicely and moving the items further to the left would upset the vertical lines between the text and the Previous/Send buttons below.

Let's leave it for Release 0.1 and see if wider user feedback indicates a problem.

**Comment by gary-rowe** [comment]
Verified working. Closing.
