### ISSUE TITLE
Coinomi compatibility

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#527]
A throwaway comment about Trezor on reddit:
http://www.reddit.com/r/Bitcoin/comments/32z4kg/trezor_omg/

```
The seed is compatible with the coinomi wallet.
```
Worth checking out sometime for MBHD compatibility

**Comment by gary-rowe** [comment]
Agreed. I've pushed it further down the time line for now.

**Comment by jim618** [comment]
I don't think we should spend time on this - we use Lighthouse compatibility as the go to wallet.
Closing
