### ISSUE TITLE
speed up Bitcoin network connection

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#528]
I've made some changes to speed up connection to the Bitcoin network:

+ removed sipa peer from list of seeds to connect to - this has been regularly failing and isn't reachable if you ping it
+ (change to ALICE) - changed PeerGroup so that if the system property java.net.preferIPv4Stack is true it does not bother trying to connect to ip6 addresses
+ reduced peer timeout from 5000 ms to 4000ms

Try it out and see what you think.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Has the staging repo been updated for Alice?

**Comment by gary-rowe** [comment]
With just a basic review (no Alice update yet) the synch start felt a lot faster. I'd suggest dropped the logging level of the `MultiBitPeerEventListener` to trace (along with any other high frequency developer-only messages). This will help to keep the log sizes down and free of any private information.

**Comment by jim618** [comment]
The staging repo has not been updated no

**Comment by gary-rowe** [comment]
Removed some extraneous logging for you (speeds overall start up time)

**Comment by gary-rowe** [comment]
Built and pushed latest Bitcoinj Alice to the staging repo. Verified working with latest MultiBit HD. Sync startup was faster (no sipa or IPv6 messages).

Based on the above changes, I'm going to close this.
