### ISSUE TITLE
Improve send progress to avoid showing 'dipped' available to spend

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#533]
It's confusing to the user that the available to spend balance is shown whilst a tx is in the process of being sent.
I think the send status screen would be improved if we do the following:

+ Hide the balance whilst a send is in progress
+ Make the Finish button disabled until the tx is 'sent' ( = seen by 2 peers)
+ Show the balance when seen by 2 peers (change is then available)
+ Have a 10 second timer that starts on send. If no peers have seen the tx after 10 seconds give the user feedback that their balance may be lower because 'your bitcoins are tied up in a current transaction', enable finish and show header.

This way the user would normally never see the 'dipped' balance due to available to spend being lower. They still get useful feedback and are not trapped if "Something Bad Happens" and the tx does not propagate.

It makes the send progress screen slightly more modal as the finish is disabled until send completes/ times-out but I think that is OK. Sending a tx is an important action so keeping the user on the send progress screen is acceptable.

**Comment by gary-rowe** [comment]
Agreed. This will also affect the Empty Wallet process. It may be time to introduce a wizard model base class for these two.

**Comment by jim618** [comment]
I've added in code to implement the balance hiding in both the regular send, the BIP70 send and the empty wallet. (I haven't put in an abstract base class mainly because it's Sunday and sunny!)

The transaction checking service in MainController is used to ensure that the user can escape if the transaction disappears off to nowhere. After 10 seconds the send 'fails' and the user sees an error message that 'the spendable balance may be lower because some of your bitcoins are tied up in ongoing  blah blah'. They also get the alert.
(The easiest way to replicate this is to comment out the broadcast code in BitcoinNetworkService).

There remains a slightly annoying flicky balance when the header comes back on which is something to do with the various events the header sees. I've left this for now as it is minor and can be tidied up later.

Awaiting review and closing

**Comment by jim618** [comment]
This isn't quite right with Trezor sends.
The tx is sent a screen earlier - in a trezor interstitial - so the header balance needs switching off a little earlier.

I've left it as 'Awaiting review' as the main path is still ok to review

**Comment by jim618** [comment]
I've added in code so that when the Send is performed with a Trezor the header gets switched off just after the tx is sent. This avoids seeing the 'dipped' balance. 

Header is switched on if cancel button in either MBHD or on the Trezor is pressed.

Awaiting review for both Trezor and non-Trezor sends and closing if ok.

**Comment by gary-rowe** [comment]
Balance header hides during send as expected, reappears once Finished is clicked. Verified working.

Closing, but see note against #541.
