### ISSUE TITLE
Change log file format to be JSON

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#536]
Currently the log file format needs to be parsed into JSON for processing by ELK. A better approach is to write the log as JSON to the disk (through Logstash encoder), but keep the console format the same. 

This will keep our existing IDE logging unchanged but will greatly simplify the processing of uploaded error reports from users. It also has the advantage that objects can be serialized as JSON allowing for more accurate unmarshalling than the `.toString()` approach.

This is a quick fix involving a new JAR dependency and a small change to the `LoggingFactory`.

**Comment by gary-rowe** [comment]
To verify:

1. Start MBHD as usual in an IDE. Observe the normal console logging taking place.
1. Examine the current log file. Observe JSON instead of the normal console mirror.

Ready for review and close.

**Comment by jim618** [comment]
Confirmed log format is now JSON and console loggin (in the IDE) is unchanged.

Closing.
