### ISSUE TITLE
When running Bitcoin Core MBHD just connects to local, one peer confuses send

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#537]
If you are running Bitcoin Core locally, MBHD connects to the local instance but does NOT connect to any more peers. It thus gets a bit confused when sending - it sends it correctly but because it does not see the tx come back from the network on any other peer it does not consider the change spendable.

MBHD needs to connect to more peers (but it'll still use the local Core as the ping time will be excellent)

**Comment by jim618** [comment]
I've fixed this but I will bundle up the change with the refresh of bitcoinj-alice

**Comment by jim618** [comment]
Fixed with #480 

Awaiting review and closing

**Comment by gary-rowe** [comment]
Closing based on #480.
