### ISSUE TITLE
'View in external browser' no longer being highlighted

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#538]
The 'View in external browser' is not being highlit when the cursor is over a link that cannot be rendered in the MBHD browser. The link still works but it is a nice feature.

**Comment by jim618** [comment]
I have changed the mouseover so that it changes the 'View in external browser' text color rather than the background. I think the custom button painting of our buttons messes up the change of backgound color.

![screen shot 2015-05-04 at 12 36 42](https://cloud.githubusercontent.com/assets/919427/7452828/7fc68b1e-f25a-11e4-9e28-4759d70fe1c2.png)

The color used is the link color for harmony.
Awaiting review and closing

**Comment by gary-rowe** [comment]
Still attracts the eye sufficiently to get the message across.

Closing.
