### ISSUE TITLE
Can empty wallet to address in wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#539]
Whilst it works ok, I thought we had a check so that you could not empty a wallet to an address IN the wallet.

Screenshot showing the tx gets sent:

![screen shot 2015-05-03 at 16 35 34](https://cloud.githubusercontent.com/assets/919427/7445607/9e46a2e8-f1b2-11e4-88f7-0c9b4e4e9441.png)

**Comment by jim618** [comment]
Note the amounts are a bit screwy. The bitcoin amount is the net amount sent, the fiat amount is the total amont sent.

**Comment by jim618** [comment]
Fixed - missing a break in a switch statement.

Screenshot:

![screen shot 2015-05-04 at 13 48 34](https://cloud.githubusercontent.com/assets/919427/7453811/2150285a-f265-11e4-925e-b4151a7d2ef8.png)


Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
