### ISSUE TITLE
Give user feedback when there is unconfirmed bitcoin

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#540]
I think we might have to show the amount of change that is unconfirmed.

In this screenshot I have a Mycelium clone wallet.
I did a send from Mycelium.
The tx gets seen ok in MBHD but because it is coming in from the network the change output is not trusted and hence not spendable.

![screen shot 2015-05-03 at 17 14 49](https://cloud.githubusercontent.com/assets/919427/7445762/3652de94-f1b8-11e4-9cbc-e644908a8c2a.png)

There are other scenarios where the spendable output is lower (e.g. tx not seen by multiple peers).

One possibility is to add a line on the Send/ Request screen at the bottom, centred with text something like:

"Bitcoin tied up with ongoing transactions: mB 23.45 ~ $4.56 (Kraken)

Whilst not terribly intuitive it gives the user the feedback that their bitcoin has not "gone" but is simply "tied up" until the tx confirm.

The Send / Request screen would then indicate all the 'present tense continuous' activity i.e.:

+ bitcoin that is currently being sent = Sending
+ bitcoin that is currently being received = Receiving
+ bitcoin that is currently tied up. Would be nice to have a present continous phrase for this. Ongoing ? hmm, that's not right

**Comment by jim618** [comment]
After discussion with Gary we agreed to have an alert:
"Low spendable balance detected. See Send/Request screen for more details"

and then on the Send/Request screen have, at the bottom:

"information icon" (icon-circle) Low spendable balance detected. Amount returning from Bitcoin network: mB 1234.56 ~ $7890"

This gives the user feedback about all the bitcoin that is being sent and received and the unconfirmed change (though we don't call it that on KISS grounds).

**Comment by jim618** [comment]
The user now gets a message at the bottom of the Send/Request screen indicating the 'amount returning' = unconfirmed change.

Also the user gets a message on the Send progress screen and an alert message where appropriate.
Screen shot:
![screen shot 2015-05-05 at 14 13 08](https://cloud.githubusercontent.com/assets/919427/7473273/ed232e7e-f331-11e4-9620-a932f8be621b.png)

I tested it using a clone of a Mycelium wallet (a send from mycelium the change is not spendable until confrmed in MBHD).
You could also do a few sends in MBHD until one does not send cleanly and you'd see it.

UI could be a bit whizzier but it does the job.
Awaiting review and closing

**Comment by jim618** [comment]
Needs a bit more work - payments being received give an estimated balance different to the available balance and hence trigger the warning - false positive

**Comment by jim618** [comment]
You might want to review what we have now.
In principle it will be difficult to distinguish a regular receive with an unconfirmed change address. It's all the same really under the covers.

**Comment by gary-rowe** [comment]
Just a trivial point before I crack on with a review. Could you left justify (RTL/LTR notwithstanding) the messages? Having one on the left and the other centered hurts my eyes. In a perfect world the icon would be in its own cell with L and A lining up vertically.

**Comment by jim618** [comment]
I don't think this approach is the way to do it Gary 
(so I don't want to tweak the layout. Simply left justified it looks bad as the information icon should be separate. That then interferes with the upper layout)

I think we will have to 'embrace the unconfirmed' and put it in the header and not put it in the Send / Request screen. In general I don't think we can avoid telling the user about ALL the unconfirmed.

For instance we could have in the header:

mB 123.45 000 ~ $123.45    + Unconfirmed: mB 20.00 000 ~ $12.34

(note that the exchange is dropped just to keep it simple).

In general it's painful trying to distinguish between 'unconfirmed due to an unconfirmed receipt' or 'unconfirmed because it is a change output that we didn't send and hence we are treating as unconfirmed'.
You could do it programmatically but it doens't mean anything to the user - just gobble-de-gook.

**Comment by jim618** [comment]
So I am thinking of adding the unconfirmed - something like:

![screen shot 2015-05-06 at 10 48 52](https://cloud.githubusercontent.com/assets/919427/7491051/91588204-f3dd-11e4-9921-8c7c99921b2c.png)

Obviously with different styling, a sort prefix text to distinguish the unconfirmed.

What do you think ?

If we have it in the header I think we should remove what I've added to the botto of the Send / request screen.

**Comment by gary-rowe** [comment]
Having a double balance up there seems to be overwhelming. The situation they are in doesn't warrant display on the header.

Let me recap where we currently are with this:

1. User performs a send locally which causes funds to be tied up, or remotely (another wallet) which has the same effect. The user is now waiting for the Bitcoin network to confirm.
1. We can detect that this has occurred so we show them an information alert describing the situation using simple terms
1. They decide to investigate the situation further and we need to accurately present what has happened to their bitcoins and provide reassurance that this is normal

How about we treat this as just another type of Request? It fits (just) into the mental model of waiting for the Bitcoin network to unlock a transaction output so could be implemented as follows:

* Send/Request: Introduce a new term in the Request column "Waiting" and provide an explanation in the Help
* Payments: Reflect the "Waiting" entry in the table 
* Transaction details: Provide a short explanation with a link to a block explorer

We may need to discuss some more offline.

**Comment by jim618** [comment]
The problem is Gary that in general we cannot:
We can detect that this has occurred so we show them an information alert describing the situation using simple terms

An incoming receipt (just a regular send to the wallet) is just the same as an unconfirmed change output.
I can send you some money to a change output you've used.

Trying to avoid all possible cases of 'unconfirmed-ness' is just whack-a-mole

**Comment by jim618** [comment]
As per our discussions offline I have removed the extra info from the Send/Request screen and added an "+Unconfirmed" in the header.

There are probably some tweaks we can make to the appearance but I've done the basic alignment and get the size right".

Awaiting review and closing

**Comment by gary-rowe** [comment]
Took few attempts (just got lucky with receives) but managed to get one out:

![screen shot 2015-05-10 at 19 23 40](https://cloud.githubusercontent.com/assets/342133/7555651/2a086892-f74a-11e4-9be7-092f9568f2c8.png)

The display looks fine and disappears correctly when the payment confirms.

Closing.
