### ISSUE TITLE
Restore button appears when wiped Trezor is inserted

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#542]
When clicked the button closes the wizard but does not hand over to another leaving the user with nowhere to go but Exit.

The Next button handles the transition correctly so the button is extraneous.

**Comment by gary-rowe** [comment]
Updated the text and removed the button:

![screen shot 2015-05-04 at 18 00 06](https://cloud.githubusercontent.com/assets/342133/7457841/713f7fec-f287-11e4-830e-ef4bbf17d8a1.png)

Ready for review and close.

**Comment by jim618** [comment]
Confirmed Restore button is not present for a wiped device.
(We restore using awallet id to find backups, so cannot restore a wiped device)

Closing
