### ISSUE TITLE
Seeing lots of "error" messages from bitcoinj in the logs

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#543]
The logging level for the `o.b.core.Context - Performing thread fixup` message is set to `ERROR` and is multi-line. This will show up in log analysis as a serious problem. 

Is there a way to remove this error message?

* change the time/conditions when the listener is attached?
* reduce the logging level to `WARN` in bitcoinj Alice?
* fix the code causing the message?

**Comment by jim618** [comment]
I have modifed the Context in bitcoinj-alice to log as info.
Setting a Context is voluntary in bitcoinj-0.13 so there shouldn't be any need to set it explicitly (possibly changing code behaviour undesirably) so I left this unchanged.

Whilst at it I have updated bitcoinj-alice to merge in the latest canonical bitcoinj changes.
Pushed changes to develop and staging repo

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified absence of messages.

Closing.
