### ISSUE TITLE
Spell Tor (the onion routing network) correctly

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#547]
The onion routing network "Tor" is not spelled "TOR" (see also https://www.torproject.org/docs/faq.html.en#WhyCalledTor). This should be corrected e.g. on https://github.com/bitcoin-solutions/multibit-hd to prevent irritation if maybe something other than Tor could be meant.

>The MultiBit Staging repository contains a bitcoinj-0.13-alice-develop-SNAPSHOT and supporting Orchid JAR for TOR that is aligned with the MultiBit HD develop branch.

There is also multibit-hd Issue #45 where I guess Tor is meant and being misspelled.

**Comment by gary-rowe** [comment]
Thanks for the feedback. I'll make the necessary changes.

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by wodry** [comment]
As of what I saw, Issue can be closed...

**Comment by gary-rowe** [comment]
Closing.
