### ISSUE TITLE
Trezor got stucked in state "Waking up" (on Trezor display) after entering the PIN

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#550]
As said [here](https://github.com/bitcoin-solutions/multibit-hd/issues/549#issuecomment-100529863), after one successful unlocking of the Trezor wallet (firmware version 1.3.3) with the built MultiBit HD source code from today, three more tries did not succeed. Each time after entering the PIN the Trezor got stucked in state "Waking up" (on Trezor display) and nothing more happened. Before the third try I also rebootet the computer for the case of OS device hazzle.

Since I have only one "hard" wallet in the ~/.MultiBitHD directory which cannot contain any coins, I moved that away and started without a ~/.MultiBitHD directory but with already connected Trezor MultiBit HD again. Now there was a screen to click "Next" if one does not have a Trezor, or to connect the Trezor when one has a Trezor and then wait for "a message" (User feedback: One is wondering, what mysterious message that would be...). 
But my Trezor was already connected and nothing happened in a minute. So I exited MultiBit HD, deleted the freshly created ~/.MultiBitHD directory again, disconnected the Trezor, started MultiBit HD again, and when prompted, I connected the Trezor. Now came (a very small) message saying "Trezor detected" or so. User feedback: At first, the "Next" button was stated only to create a soft wallet. But now it looked like one had to click "Next" to go on with the "hard" wallet. That worked, but as user I was somehow unsure.
Entering PIN worked, Trezor got **not** stucked this time, and balance (of account 1) was shown correctly. So the wrong balance shown in the issue linked above seems to have been a sanchronization issue.
User feedback: One is unsure whether to connect the Trezor to connect before starting MultiBit HD, or after starting. Which would work more stable.

**Comment by gary-rowe** [comment]
Thanks for taking the time to fill in the details (and user feedback :-) ) and I'm glad the sync worked correctly after some fiddling.

Is it possible that you were logged on to myTrezor.com and MultiBit HD at the same time? This would lead to a USB contention which would mean that one or the other would have difficulty communicating with the device.

Fixes for this issue would be:

* make the "insert Trezor and wait" instructions clearer
* make the "Trezor found" feedback more prominent
* include clear instructions about clicking Next once the message shows

**Comment by gary-rowe** [comment]
Updated the "Attach Hardware Wallet" notes to give clearer instructions:

![screen shot 2015-05-10 at 20 15 35](https://cloud.githubusercontent.com/assets/342133/7555899/516e6770-f753-11e4-893b-64232c50fe1c.png)

I've used "plus-circle" and "plus-square" icons to draw attention to the greater security from a hardware wallet in a subtle manner (more black with "hard" wallets). I've also added more info about closing browser sessions on myTrezor.com (to avoid USB contention).

I tried changing the colour of the message, but once it appears it's pretty obvious and various local user feedback indicates this is OK.

Ready for review and close.

**Comment by wodry** [comment]
I am no design icon psychologist, I am more the kind of person who reads the text and not looking at the icons. But maybe I am influenced by them as well without knowing.

But the additional texts I like, I think they are very clear and helpful.

But agin, this silently appearing small line "A Trrezor was detected..." I find a little bit too silent, hard to detect, I would like a big popup window with just an "OK" button additional to the small info line more. But don't make this a release stopper :)

**Comment by gary-rowe** [comment]
Thanks for the update :-)

When we put in the attach screen (see #509) we found it necessary to have a popup screen to tell the user that they've inserted an unsupported Trezor (e.g. one with a passphrase or deprecated firmware). The idea of the lesser message is as a quiet indication that all is well, leaving the more "shouty" popup for problems. 

Bear in mind that people with multiple Trezors may be re-attaching several at this time so having a big message would probably be too noisy.

@jim618 If you're OK with the new layout and wording feel free to close this.

**Comment by jim618** [comment]
I tested this out with a clean install of MBHD and saw the 'Attach hardware wallet' fine. 
Created new wallet successfully.
Closing
