### ISSUE TITLE
Unconfirmed balance showing at start up when no network connection found

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#551]
Unconfirmed amount was showing with no main balance when network connection failed.

This has been fixed so that the unconfirmed amount does not show at start up until network is connected.

There is also a fix to bitcoinj-alice to fix why the network connection was failing (bitcoinj retransmits unsent tx at start up. It was checking the state was 'pending' but we had some 'unknowns').

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. 

Closing.
