### ISSUE TITLE
if you do Trezor | Buy Trezor, prev next is always disabled

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#552]
If you do Tools | Trezor | Buy Trezor, next and then do prev the next button never enables, whatever you do.
Screenshot:
![screen shot 2015-05-12 at 18 33 40](https://cloud.githubusercontent.com/assets/919427/7593984/a2cfed9a-f8d5-11e4-8181-f86311b95295.png)

**Comment by jim618** [comment]
Ensured Next button is enabled after "Buy a Trezor, Next, Prev" roundtrip.
Awaiting review and closing.

**Comment by wodry** [comment]
Next button is enabled after "Buy a Trezor, Next, Prev" roundtrip, for me

**Comment by gary-rowe** [comment]
Verified working. Closing.
