### ISSUE TITLE
Error report contains user name

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#557]
The error report contains the user name which can be safely removed to protect privacy.

**Comment by gary-rowe** [comment]
Updated the code to replace the currently logged in user name with `*blank*` in both Unix and Windows paths. A blanket removal is not possible due to user names like "a" being present.

Here's a screen shot showing the path replacement in action (centre of error report):

![screen shot 2015-05-13 at 22 22 35](https://cloud.githubusercontent.com/assets/342133/7621469/0323b674-f9bf-11e4-8d80-e8290544b5f0.png)

Ready for review and close.

**Comment by jim618** [comment]
Confirmed that the username is substituted when an error report is created.
Closing.
