### ISSUE TITLE
Canadian exchange Cavirtex reopen, please add to exchange list

### ISSUE THREAD

**Issue by tenakakhan** [bitcoin-solutions/multibit-hd#559]
Though it shutdown briefly, Cavirtex (www.cavirtex.com) has reopened after being acquired by Coinsetter.

Another major Canadian exchange, www.quadrigacx.com is also missing from the Beta 8 exchange list.

**Comment by gary-rowe** [comment]
Thanks for the feedback. It's a trivial thing to re-instate cavirtex so I'll put this issue into Release 0.1. 

The additional one will require an update to XChange which is scheduled for Release 0.3 at present under #446.

**Comment by jim618** [comment]
Added Cavirtex exchange back into list of exchanges. Checked CAD feed ok.
Screenshot:

![screen shot 2015-05-14 at 16 05 28](https://cloud.githubusercontent.com/assets/919427/7634519/50b685c6-fa53-11e4-8c43-f5007bac704f.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

One nit: Due to Virtex being the name in XChange the list appears to be non-alphabetic. Not a biggie and will probably be fixed in #446.

Closing.
