### ISSUE TITLE
Transaction outputs doubled in wallet after 'Repair wallet' - balance is then wrong

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#560]
I just did a 'repair wallet' on a perfectly ok wallet (just to try it out).
The balance was _higher_ after the repair wallet and a send failed with:
```
{"@timestamp":"2015-05-14T17:22:23.606+01:00","@version":1,"message":"Could not commit the transaction","logger_name":"org.multibit.hd.core.services.BitcoinNetworkService","thread_name":"safe-fixed-bitcoin-network-2","level":"ERROR","level_value":40000,"stack_trace":"org.bitcoinj.core.VerificationException$DuplicatedOutPoint: Duplicated outpoint\n\tat org.bitcoinj.core.Transaction.verify(Transaction.java:1239) ~[multibit-hd.jar:na]\n\tat org.bitcoinj.core.Wallet.maybeCommitTx(Wallet.java:2226) ~[multibit-hd.jar:na]\n\tat org.bitcoinj.core.Wallet.commitTx(Wallet.java:2291) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.core.services.BitcoinNetworkService.commit(BitcoinNetworkService.java:1057) [multibit-hd.jar:na]\n\tat org.multibit.hd.core.services.BitcoinNetworkService.performCommitAndBroadcast(BitcoinNetworkService.java:392) [multibit-hd.jar:na]\n\tat org.multibit.hd.core.services.BitcoinNetworkService.performSend(BitcoinNetworkService.java:371) 
```

Screenshots before and after (notice the balance has changed although there have been no sends or receives).

![screen shot 2015-05-14 at 16 05 28](https://cloud.githubusercontent.com/assets/919427/7636390/e01e466c-fa5e-11e4-93cb-0f9cbe81488c.png)

![screen shot 2015-05-14 at 17 23 02](https://cloud.githubusercontent.com/assets/919427/7636394/eb3db910-fa5e-11e4-9128-1d4d48279fe5.png)

Possibly the same unspent transaction output is appearing in the wallet twice ???

p.s. After another repair wallet the wallet balance increased again so the same tx is probably being added repeatedly. Screenshot:

![screen shot 2015-05-14 at 17 33 43](https://cloud.githubusercontent.com/assets/919427/7636508/7d68b542-fa5f-11e4-8698-439653003587.png)

**Comment by jim618** [comment]
This was caused by the set of unspent tx "myUnspent" in Wallet not being cleared when the wallet was being repaired. Fixed.

There is an update to bitcoinj-alice which is pushed to the staging repo.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Reviewed bitcoinj code covering this and it looks fine. Removed some logging that flooded the logs during repair since we are limited to 200Kb and Repair is likely to occur if someone is encountering problems.

Closing.
