### ISSUE TITLE
Request for Tooltip for the blue "progress bar" on the lower left

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#561]
I just built the current code and logged in with the Trezor.
After Synching, I clicked around in the menus and changed the Exchange to Kraken.
Then I recognized this blue progress bar or whatever it is on the lower left edge of the screen right above the Trezor shield symbol (see screenshot).

I am wondering what that would be? Please make a Tooltip for it...

**Comment by gary-rowe** [comment]
The screen shot hasn't uploaded - would you mind adding it? 

If it's blue then it's possible you're seeing a horizontal scroll bar for adjusting the width of the sidebar - just drag the black vertical line to the right to expand it.

**Comment by wodry** [comment]
You're right, it's a horizontal scroll bar. Not to be intuitively recognized by me... 
![multibithd](https://cloud.githubusercontent.com/assets/8447873/7639956/366a6c96-fa80-11e4-9638-17fdf7f700bf.png)

**Comment by gary-rowe** [comment]
Since this is a common UI component I'm going to close this.
