### ISSUE TITLE
Crash in preferences->language->Clicking button "I would like to help"

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#562]
When clicking "I would like to help" button in preferences->language, a window popups "MultiBit HD error report.
After entering a comment and clicking "Upload error report" there comes the message

"Upload failed. Please try again later or visit multibit.org for help".

After clicking on "abort" on the error report window, MBHD exits (crash).

**Comment by wodry** [comment]
Screenshot
![multibithd](https://cloud.githubusercontent.com/assets/8447873/7638417/cb994f78-fa74-11e4-9dc8-d07ef2b647fc.png)

**Comment by gary-rowe** [comment]
Congratulations! You're the first person outside of the MultiBit labs to see the error report dialog!

I'm just wiring up the back end to allow uploading so it may be a little while before the uploads are successful.

BTW That horizontal blue bar is definitely a scrollbar.

**Comment by wodry** [comment]
Cool :)
So don't fix the bug, so we can test the error report upload first ;)

**Comment by gary-rowe** [comment]
I've configured the server side now so please feel free to upload error reports. 

I've tried to replicate your situation but my browser launches to the CrowdIn website just fine so this will be a great test. I probably won't be able to offer feedback for a day or so but I will be looking into it.

If all goes well you should experience a short delay during upload (about 10s), followed by an "Upload complete" message.

**Comment by wodry** [comment]
Now, uploading of error report worked :)
There should be a "Finish" button after successful upload, IMHO. Now, there is only a "X Cancel" button left to click on, which gives a negative feeling.

I am scared, that the error report is uploaded to Crowdin, to the "cloud". The cloud is not trustworthy. I thought, the error reports would be uploaded to multibit.org directly via secure connection, so to Your trusted developers eyes only. You can't be sure, that there isn't some confidential / private information left in the error report, and You can't be sure, that the information can only be read by You when it is uploaded to Crowdin external service :( At least, You should give the user the information, where the error report will be uploaded exactly to, and who will have access to it.
![multibithd](https://cloud.githubusercontent.com/assets/8447873/7646915/b57b1cec-facb-11e4-9f8e-da1172d96ebe.png)

**Comment by gary-rowe** [comment]
More congratulations - you are the proud owner of the first live error report! :-)

Agreed on the cancel button being misleading - I've raised #564 to cover this.

Regarding the privacy aspect - the [updated Help files](https://rawgit.com/bitcoin-solutions/multibit-website/release-4.0.0/src/main/resources/views/html/en/help/hd0.1/offline-help.html) (not yet released) provide more information.

To be extra certain, here is the code that does the work: https://github.com/bitcoin-solutions/multibit-hd/blob/develop/mbhd-core/src/main/java/org/multibit/hd/core/error_reporting/ExceptionHandler.java. Have a look at line 56 for the upoad destination. You can verify this behaviour occurred by looking into your own logs or using a packet sniffer.

Regarding the cause of you seeing the error reporting dialog, it appears that your external browser is not being discovered by Java - there may be a permissions issue. I haven't investigated deeply but I thought I'd give you some early feedback.

**Comment by jim618** [comment]
When the external browser cannot be started, rather than crashing we should put up a dialog or something saying "External browser could not be started to view site <name of site>'.
If we make the <name of site> copiable at least the user can copy-pasta into their browser as a fallback

**Comment by wodry** [comment]
So it seems the "launches to the CrowdIn website" has nothing to do with error reporting, seems there was a misunderstanding. Very good.

On my Debian box $BROWSER is empty. I have only set the default browser the Debian way, which is the symlink
/etc/alternatives/x-www-browser
which points to /usr/bin/iceweasel
Dont' know what Java does to detect the default x-www-browser. Maybe You can tell, so I can do the environment setting. Then there should be some help text howto set the default x-www-browser on Debian.

Regarding the exception:
This is already well handled on Payments->Select transaction->Transactions details->Next->Next->View on blockchain.info
Shows yellow bar "java.io.IOException: Failed to show URI:https://blockchain.info/tx-index/....."

(opening default browser does not work there also)

**Comment by gary-rowe** [comment]
Some information from [KDE.org](https://forum.kde.org/viewtopic.php?f=63&t=88820):
Java doesn't use `xdg-open` to locate the default browser. It looks like Java determines the default web browser in the same way that GNOME does by consulting `~/.local/share/applications/mimeapps.list`. This file maps various URI schemes, MIME types and file extensions to application entries in `/usr/share/applications`. 

Therefore to change Java's default browser, you need to look in `/usr/share/applications` and find the file corresponding to your browser (or, if it doesn't exist there, create it, using some other file as a model). Then you should edit `~/.local/share/applications/mimeapps.list` and change the relevant entries (`x-scheme-handler/http`,`x-scheme-handler/https`, `text/html`, etc.) so that they map to that file. 

For example, editing `~/.local/share/applications/mimeapps.list` to contain the following (assuming `iceweasel.desktop` is present) should do it:

```
[Default Applications]
text/html=iceweasel.desktop
application/x-extension-htm=iceweasel.desktop
application/x-extension-html=iceweasel.desktop
application/xhtml+xml=iceweasel.desktop
application/x-extension-xhtml=iceweasel.desktop
x-scheme-handler/http=iceweasel.desktop
x-scheme-handler/https=iceweasel.desktop
```

**Comment by gary-rowe** [comment]
Jim, in general all our external links should have this construct:
```java
if (Desktop.isDesktopSupported()) {
   desktop = Desktop.getDesktop();
   desktop.browse(someUri);
} else {
   // Show failure
}
```

**Comment by wodry** [comment]
Gary, I could edit ~/.local/share/applications/mimeapps.list and modify it. But I've never heared of that file before, and the steps You tell are very geeky. So I could do the step and then it might work. But should every dummy user need to do that? I think there should be another way, for all normal users. At least, I am no dummy user and I have no lust to frickle with that file...

**Comment by gary-rowe** [comment]
Agreed. That solution is only for someone with strong technical knowledge. Unfortunately, it also falls outside of MultiBit's remit to fix external environment issues within user's system. 

Consequently, about the most we can do is to reference that approach as a workaround in the help files (possibly in the Linux installation guides) and put up a message to indicate that this situation has occurred.

**Comment by gary-rowe** [comment]
Added `SafeDesktop` utility class to wrap `Desktop` and provide fall back to alternative browser launching methods. In particular, if the Desktop is not available on Linux it will fall back to using `xdg-open` to launch the user's default browser. 

Verification of this behaviour (beyond normal code review) will require @wodry to attempt to open an external link (perhaps off the Help screen) and report back.

Ready for review and close.

**Comment by jim618** [comment]
Performed code review and checked there are no browser regressions on Mac OS.
@wodry to check Linux behaviour is acceptable and close accordingly.

**Comment by wodry** [comment]
When clicking "I would like to help" button in preferences->language, I hear now a piezo beep, nothing more happens.

**Comment by gary-rowe** [comment]
Just a note for @wodry about the beep. That indicates that the `xdg-open` method of locating your default browser failed. If you think it should be able to launch the browser using this method, please use the "Report Error" as before just after getting a beep (the logs are deliberately kept short) and mark it with this issue number (562) and I'll see if there's anything that can be done.

**Comment by wodry** [comment]
Thanks, @gary-rowe . Upload of error report after beep is done.

There should be a "Finish" button after successful upload, IMHO. Now, there is only a "X Cancel" button left to click on, which gives a negative feeling.

**Comment by gary-rowe** [comment]
I've raised a separate issue for the UX of the error report dialog. See #571.

Thanks for the feedback :-)
