### ISSUE TITLE
Updated error reporting dialog to use Exit/Cancel button

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#564]
User feedback has indicated that the error reporting dialog would benefit from an Exit/Cancel button as follows:

* user has experienced a crash - button is Exit (they must restart as the safest option)
* user reporting an issue - button is Cancel (they can resume)

**Comment by jim618** [comment]
Closed as duplicate of #562 (broswer behaviour)

**Comment by gary-rowe** [comment]
No. This is covered as a separate issue based on the error reproting dialog not being friendly enough.

**Comment by jim618** [comment]
oops - closed wrong one!

**Comment by gary-rowe** [comment]
Added Exit button (with theme colour if Nimbus LaF has loaded, default otherwise) if this is a crash. Cancel button remains for user error reporting.

![screen shot 2015-05-16 at 21 55 58](https://cloud.githubusercontent.com/assets/342133/7667932/97c95e6a-fc16-11e4-8c02-cbbf3dfc1228.png)

To verify theme simply add a NullPointerException to the `CredentialsEnterPasswordPanelView`, otherwsie add NPE to `CoreServices`.

Ready for review and close.

**Comment by jim618** [comment]
Successfully tested error report screen - closing.
