### ISSUE TITLE
Unpredictable Trezor communication hangups

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#565]
Unfortunateley, I have to create this issue.
To besure, the reason is not a bad USB cable, I just today bought a new one at the computer store. But the instability is the same. I am wondering, if other users are facing the same issue. It's a long standing issue for me also with mytrezor.com which I nearly cannot use, because the sending of transactions only works in 1 of 5 tries or so, and if it works or not, seems to be random. In most of the tries, is does not. I cannot reproduce the missbehaviour, neither I can reproduce the succes case.

I have a big deversity of hangup situations.
The most stable way to unlock the Trezor with MBHD is to boot the PC with Trezor disconnected, then start MBHD, select language, wait for the welcome screen topics, and the connect the Trezor. I had have now great 7 times or so in a row that was successful, I was already thinking that would stable work. But just now, I had again a case, where it hangsup on the screen "Requesting Trezor unlock". See screenshot.
![multibithd](https://cloud.githubusercontent.com/assets/8447873/7652494/762f5ec6-fb0d-11e4-9ce9-c72a16df5c27.png)
What almost never works, was the case, when after successfull unlock as described above, to exit MBHD, wait 10 s and then start MBHD again. Then the unlock never worked, until... just before some minutes. Surprisingly I did not have to enter the PIN again, only confirm the unlock request by MBHD. But I am sure that is a feature.
But afterwards, I exited MBHD and started it again with still connected Trezor, and now, it is not detected anymore, instead the welcome screen appears after language selection, with the suggestion "Connect Your device...". So I disconnect the Trezor, wait 10 s, connect it again, MBHD say it detectet the Trezor, then comes "Requesting Trezor unlock", but this time there is absolutely no action on the Trezor display. In other cases, at least there is the "Waking up" progress bar with turning gears, until 100% is reached and the the communication freezes, the gears standing still. 

So, in short, there are many combinations of misbehaviour, which I am unable to reproduce, they seem to happon randomly and unpredictable. I am just happy, if at one time, it works. But I cannot reproduce the success cases.

I really would like to help to solve this issue, since after I had this issues also at mytrezor.com my hope was that MBHD would not have this problems. Maybe my Trezor is broken? I tried now with three USB cables- one I had on my own, the very short one delivered with the Trezor, and now the one I bought today. So the cable should not be responsible.

The Ubuntu udev rules it seems I do not require, the permission slook good:

crw-rw---- 1 root plugdev 180, 0 Mai 15 14:30 /dev/usb/hiddev0

Maybe it is a OS issue with udev / hotplug whatever.

My OS is Debian 8 "Jessie" amd64.
But I faced the same issue with Debian 7 "Wheezy" x86 before, so it seems not be an OS issue.

So please tell me how I could help You debugging this.

I also created a support cas at Satoshi Labs some months ago, but the support was very very poor, the best conclusion I remember was "we had other users reporting this issue, also".

Trezor firmware is 1.3.3. I had the same issue with firmware version before that version.

On mytrezor.com, I think the unlocking nearly always works, only sending coins in most cases does not work, when it hangs on "Signing transaction"

Maybe I should buy a new Trezor to check if my current is just broken somehow?

**Comment by gary-rowe** [comment]
You're correct that the short USB cables that come with the device have intermittent data problems, but using any standard mobile micro-USB cable usually sorts that out which implies that you're seeing something weird. 

Fortunately, we have the error reporting system availalble now.

Can you unlock any wallet (Trezor or not), go to the Help screen and click the Report Error button. Reference this issue in the user notes (e.g. `See #565 for details`). Click upload. This will allow us to see your logs securely which will give us a lot of under the covers details about your issue. 

You can then click Cancel and carry on as normal (no restart required).

**Comment by wodry** [comment]
Thank You very much. So here what I've done:
Start MultiBit HD without Trezor connected. Tried to get to the help screen. Did not manage that. Shutdown MultiBit HD. Startedt it again. I had now suddenly to accept the license, which I hade not to do since weeks. Accepted it. Welcome topics appeared. Connected Trezor. Trezor detected. Entered PIN. Trezor hangup, screenshot the same as originally posted. Exit. Disconnect Trezor. Wait 10 s. Start MultiBit HD again. Select language.  Connect Trezor. "Trezor detected" message.  Click Next. Hangup. Shutdown MBHD, disconnect Trezor while MBHD is in shutdown state. Wait 10 s. start MBHD with disconnected Trezor. Select language. Connect Trezor. "Trezor detected". Click Next. Enter PIN. Trezor unlocked. Now in the MBHD dashboard. Disconnect Trezor. Got Help. Click "Report error". Upload success. Click "Cancel". Exit MBHD. Thanks again!

**Comment by gary-rowe** [comment]
Thanks for persevering! Sounds like your Trezor is giving you some trouble. I'll take a look at the error reports over the weekend (assuming I get some free time) and see what's causing this.

**Comment by gary-rowe** [comment]
I've had a chance to look at the uploaded logs and there is no communications error showing up - packets are definitely written successfully to the USB buffer. The logs indicate correct detach of device and match the sequence described above.

The normal request/response sequence to unlock is:

1. CREDENTIALS_REQUEST_MASTER_PUBLIC_KEY (to form deterministic hierarchy)
2. CREDENTIALS_ENTER_PIN_FROM_MASTER_PUBLIC_KEY (Optional)
3. CREDENTIALS_REQUEST_CIPHER_KEY (to form password)
4. CREDENTIALS_ENTER_PIN_FROM_CIPHER_KEY (Optional)
5. CREDENTIALS_PRESS_CONFIRM_FOR_UNLOCK (to confirm unlock)

There seems to be a hang occurring inconsistently after 1 or 3 above. One commonality is the expectation that the device will respond with a PIN matrix request. A quick test involving removing the PIN from one of our test devices and restarting yielded a smooth Unlock experience (as expected).

We regularly test this code with a range of devices and have seen consistent smooth behaviour on OS X. However, it may be that your system has an unusual set up that could lead to this behaviour. If possible it would be worth testing the same device on a different operating system.

**Comment by gary-rowe** [comment]
I'm going to mark this as closed for now since there's not anything I can do to fix it. However, I'm OK with re-opening it should there be more supporting evidence for the behaviour.
