### ISSUE TITLE
Repair wallet is not showing zero confirmation tx

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#566]
It looks like the repair wallet is not showing/ adding to the wallet's zero confirmation tx (both send and receive).

If you have a zero conf tx and do a repair it 'disappears' until the tx is confirmed (at which point I think it reappears with the metadata but am not 100% sure about this last point)

**Comment by jim618** [comment]
This was quite a tricky bug to track down - it was caused by the mempool (TxConfidenceTable) not getting cleared when we reset the Bitcoin network connection.

It needed an update to bitcoinj-alice which has been pushed to our staging repo.

To test it you need to have zero conf sends and receives and do a wallet repair.
On the sends you'll see the change 'move over' to the unconfirmed amount. This is expected as the tx is coming in from the network.

I don't like the header alerts for the zero conf tx - they aren't useful and the send amounts are misleading (whilst technically they are correct - the mempool is synced with the Bitcoin Core before the blocks).
I'll raise a separate issue to suppress these which I think will be simpler for users.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Code review of the bitcoinj update looks fine.

Closing.
