### ISSUE TITLE
Suppress zero-confirmation alerts in Repair wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#567]
Mentioned in #566.

When a repair wallet is performed any zero confirmation tx in the wallet create a new 'You have received XXX btc' alert in the Alert Bar. It would be better if these were suppressed.

Not only are they a bit noisy but, because mempools are synced before blocks are downloaded, the sends are misleading. The sends are reported as 'Receiving whatever was on the change address'. This is technically correct but pretty confusing to the user.

Better that the repair wallet is quiet and that everything is reported on the 'Repair wallet' lightbox.

**Comment by jim618** [comment]
I've put a boolean into MainController that is used to suppress the 'you have received / you have sent' X bitcoin alerts. It is activated before a repair wallet and switched off on sync complete.

If you do a repair wallet where there are zero conf txes you now no longer see alerts for these txes.

As a side effect if someone actually sends you bitcoin when you are doing a repair you won't see an alert but it will appear in the payments ist and on the Send / Request screen (and in the header as unconfirmed) which I think is acceptable.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Sent to the wallet, showed up as unconfirmed. Began a Repair Wallet operation and observed no display or alerts during the operation.

Closing.

One nit: I'm not seeing any Received alerts and their accompanying sound even outside the Repair. Is this is intentional (unclear from your description) or should I raise a fresh issue to cover their absence?

**Comment by jim618** [comment]
RE: nit - there should be the same receive alerts and sounds outside of Repair so it's a bug.
I moved the 'alert and sound' code into MainController so perhaps this has created a regression.
