### ISSUE TITLE
Feature request: Connect exclusively to a defined (local) full node

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#568]
Found this in the Bitcoin Wiki about the advantage of connecting MultiBit HD exclusively to a full node which the User is also running in parallel.

>if you use a lightweight client like MultiBit but configure it to connect exclusively to your full node, then you will contribute to the network's economic strength and receive protection from some possible attacks against lightweight nodes. 

([source] (https://en.bitcoin.it/wiki/Full_node#How_to_run_a_full_node))

Since I am running a full node, I would like to take the advantage of connecting my MultiBit HD exclusively to my full node's Onion address (Tor hidden service, bitcoin node is tor-only).

**Comment by jim618** [comment]
In the current code it will automatically connect to a Bitcoin Core running on a localhost.
It does connect to more nodes than that though as it uses this when working out whether broadcasts are successful. This in turn is used to determine when change is spendable.

Thus we wouldn't implement a 'connect to localhost ONLY' as it would effect too many other aspects of usability.
