### ISSUE TITLE
Add enforcer rules to prevent dependency chain attacks

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#569]
Simple addition to the POM now that we're freezing the dependencies. 

See [Bitcoinj enforcer rules](https://github.com/gary-rowe/BitcoinjEnforcerRules) project for details.

**Comment by gary-rowe** [comment]
Added enforcer URNs to the parent POM. This will only trigger during a verify or higher (install/deploy etc).

To verify the build should pass both locally and on Travis. If it fails then we should investigate the root of difference and determine the correct SHA1 of the library.

Ready for review and close.

**Comment by wodry** [comment]
Build fails on my box, even after deleting the multibit-hd build folder and the ~/.m2 maven folder.
```
Downloading: https://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.jar
Downloaded: https://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.jar (45 KB at 205.8 KB/sec)
[INFO] Verifying URN: org.mockito:mockito-core:1.8.5:jar:null:test:7904ce54a754031a32ac78ec7103f484f81b56c6
[INFO] Verifying URN: org.multibit.hd.hardware:core:0.5.0:jar:null:compile:6077d279eae6b95e6b39308e4b9c763ce9b8d28a
[ERROR] *** CRITICAL FAILURE *** Artifact does not match. Possible dependency-chain attack. Expected='6077d279eae6b95e6b39308e4b9c763ce9b8d28a' Actual='f1bb33e28e5f9c11c8a499ecf45dc78c55edb512'
[INFO] Verifying URN: org.multibit.hd.hardware:trezor:0.5.0:jar:null:compile:89fb097aefd64f55732e1be84463c54f11fba57c
[ERROR] *** CRITICAL FAILURE *** Artifact does not match. Possible dependency-chain attack. Expected='89fb097aefd64f55732e1be84463c54f11fba57c' Actual='11112e8ba67617bfe2748af23fec9bef11940967'
[INFO] Verifying URN: org.objenesis:objenesis:1.0:jar:null:test:9b473564e792c2bdf1449da1f0b1b5bff9805704
[INFO] Verifying URN: org.slf4j:jul-to-slf4j:1.7.2:jar:null:compile:2ee8f3304632a2025d3c58aa3b63cd8842740f84
[INFO] Verifying URN: org.slf4j:slf4j-api:1.7.2:jar:null:compile:0081d61b7f33ebeab314e07de0cc596f8e858d97
[INFO] Verifying URN: uk.co.froot.maven.enforcer:digest-enforcer-rules:0.0.1:jar:null:runtime:16a9e04f3fe4bb143c42782d07d5faf65b32106f
[WARNING] Rule 0: uk.co.froot.maven.enforcer.DigestRule failed with message:
At least one artifact has not met expectations. You should manually verify the integrity of the affected artifacts against trusted sources.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MultiBit HD ....................................... FAILURE [5:08.728s]
[INFO] MultiBit HD BRIT .................................. SKIPPED
[INFO] MultiBit HD Core .................................. SKIPPED
[INFO] MultiBit HD Swing ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:17.662s
[INFO] Finished at: Sat May 30 19:53:32 CEST 2015
[INFO] Final Memory: 20M/83M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce (enforce) on project mbhd-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
```

**Comment by gary-rowe** [comment]
Yeah. Travis has kicked it out. I'm on it at the moment.

**Comment by gary-rowe** [comment]
Travis has successfully built the project so I'm putting this back out for review. However, in order to correct the hashes in the staging repo I've had to rebuild the release artifacts which is not good from a Maven point of view. 

Therefore, in order to test this, it is necessary to run Maven 3 as follows:
```
mvn -U clean install
```
In Maven 3 (not Maven 2) this will force an update of both release and snapshot artifacts. 

However, if this results in a failed build with nasty URN messages then the following released artifacts must be deleted from local repos so that they can be downloaded from the staging repo once again:

* org/hid4java/hid4java/0.3.1
* org/bitcoinj/bitcoinj-core/0.13-SNAPSHOT-alice-0.0.9
* org/bitcoinj/bitcoinj-parent/0.13-SNAPSHOT-alice-0.0.9
* org/multibit/hd/hardware/core/0.0.5
* org/multibit/hd/hardware/parent/0.0.5
* org/multibit/hd/hardware/trezor/0.0.5

Ready for review and close.

**Comment by wodry** [comment]
Could now build with the README documented command (to be sure, I deleted the multibit-hd build folder and ~/.m2 folder first)

**Comment by jim618** [comment]
To get the build to run successfully I had to:

+ delete ~/m2 org.bitcoinj, org,multbit, org.hid4java
+ delete build folders
+ build multibit-hd with  mvn clean dependency:sources install

Of course now we are going to have to adjust the dependency hashes every time we build / change bitcoinj-alice (or anything else).

Closing
