### ISSUE TITLE
After a Trezor Send exchange rate is not switched back on properly

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#570]
After a send from a Trezor the header is not all switched on properly.
Screenshot:

![screen shot 2015-05-22 at 14 34 17](https://cloud.githubusercontent.com/assets/919427/7771525/ea7c41ae-008f-11e5-9c95-81aca34c961a.png)

I have seen this display intermittently over the last week so it might not be Trezor specific

**Comment by jim618** [comment]
I have changed the logic slightly in HeaderView so that a missing local amount always switches off the local amount display fully. 
I cannot reproduce the screenshot display posted in the OP so think this issue is fixed.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Hmm. You'd get this situation if the `exchangeLabel` was visible but the `localDisplay` was null/empty in the `DisplayAmountView`. The `localDisplay` comes from `Formats.formatLocalAmount` which will return `""` on null. I think a further check on line 173 of `DisplayAmountView` to test for empty will squash this properly.

I've added this, so I'll bounce it back for you to review and close.

**Comment by jim618** [comment]
Looks good to me.
I've tried it out now a few times and don't see anything unusual so will close it now.
Let's just keep an eye on it during our IRL testing next week.
