### ISSUE TITLE
Check world/ group access of exe on Mac

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#572]
Raised in the MultiBit issues db but might also apply to MBHD:

Just installed latest version for OS X (from https://multibit.org/releases/multibit-0.5.18/multibit-0.5.18.dmg). Permissions on the executable in the .app bundle include world and group write permissions. Seems this could provide an injection point for malware.

-rwxrwxrwx@ 1 sysadmin  admin    72K Apr 28  2014 MultiBit.app/Contents/MacOS/JavaApplicationStub*
Seems to me -rwxr-xr-x would be a more secure choice. Can/should this be changed?

**Comment by jim618** [comment]
Originally raised here:
https://github.com/jim618/multibit/issues/694

**Comment by gary-rowe** [comment]
Should be a case of editing "Installer | Screens & Actions" and making the changes for each variant. We could add +x to the Linux install script too.

**Comment by jim618** [comment]
This is not a problem with the MultiBit HD installed JavaApplicationStub (It uses a different installer to MultiBit Classic).

The rights are:

```
jims-macbook-91:MacOS jim$ ls -l
-rwxr-xr-x  1 jim  admin  55988  9 Jun 13:49 JavaApplicationStub
```

which is what we want. Thus no change to the installer is necessary.
The change to MultiBit Classic is still required and covered by the issue jim618/multibit#694

Awaiting review and closing

**Comment by gary-rowe** [comment]
Checked this a few nights ago so we're good to go.

Closing.
