### ISSUE TITLE
Cancel of wipe trezor in MBHD does not clear Trezor

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#578]
If you go to Tools | Wipe Trezor and then click Cancel IN MBHD the Trezor display does not reset.
It still shows the 'Are you sure you want to wipe the Trezor'.

If you press the Cancel button on the Trezor it correctly navigates to the 'Wipe cancelled' report screen and the Trezor display resets.

**Comment by jim618** [comment]
Bumped to 0.2 as not critical

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by jim618** [comment]
Yes the Cancel on the Wipe Trezor screen works now.
The user then gets a 'There is a Trezor '' attached' Do you want to use it?' alert that is shown that is a bit unintuiitive but not critical.

Closing.
