### ISSUE TITLE
Change 'Verify network' to '10 or more is healthy'

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#579]
As I have increased the number of nodes to 10 (to match the WalletTool) the localisation text on Verify Network should be updated.

Screenshot:
![screen shot 2015-05-25 at 13 34 00](https://cloud.githubusercontent.com/assets/919427/7797362/dd73e8b8-02e2-11e5-9fe8-c848cbe5531d.png)

Makes more sense to say 10 nodes is healthy.

**Comment by jim618** [comment]
Updated text to match '10' peers.

Awaiting review and closing

**Comment by wodry** [comment]
I can not confirm it with German language environment. I just completed the German translation on Crowdin and saw, that the peer count ist statically in the message text (in the German language file it was still 8). I would suggest to make the healthy peer count a variable in the language file.

**Comment by gary-rowe** [comment]
I agree. We may change the value later and we don't want to go through a whole translation exercise to ensure consistency. I'll handle the modification.

**Comment by gary-rowe** [comment]
I've done the modification and seen it working so I think this issue can be closed. 

@wodry Many thanks for contributing to the German translation effort - it's really appreciated :-)

**Comment by jim618** [comment]
I have uploaded the updated language.properties to crowdin.
