### ISSUE TITLE
Crypto-trade.com is out of business and should be removed from exchange list

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#582]
During security certificate updates crypto-trade.com continuously times out, and according [to this article]()https://www.cryptocoinsnews.com/another-bitcoin-exchange-shuts-little-warning) is out of business.

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by jim618** [comment]
Confirmed Crypto-Trade has disappeared.
Closing.
