### ISSUE TITLE
Improve error message if transaction cannot be completed

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#583]
At present the contents of the exception returned from Bitcoinj are presented, which can be "null" if a transaction cannot be completed due to unconfirmed transactions during an empty operation.

**Comment by gary-rowe** [comment]
As an interim measure, I've added an English-only error message to give some indication of the failure:

![screen shot 2015-05-30 at 21 43 42](https://cloud.githubusercontent.com/assets/342133/7899289/4fdffd8e-0715-11e5-9f05-bbed89e6ebae.png)

Ready for review and close.

**Comment by jim618** [comment]
I just did an empty wallet with unconfirmed tx and did not see this message (tx was sent fine - it leaves the unconfirmed which is what you would expect).

I have done a code review to check that the edge case is covered as per the OP so closing.
