### ISSUE TITLE
Change "Your bitcoin were sent successfully" to something more readable

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#584]
The current message is highly visible (seen on a send) and is grammatically incorrect. An alternative would be "Bitcoin sent successfully". 

Also the related "Your send transaction was created ok." does not read well either - perhaps "Transaction created successfully".

**Comment by gary-rowe** [comment]
Adjusted the text accordingly. I think it looks a lot better now:
![screen shot 2015-05-31 at 10 48 44](https://cloud.githubusercontent.com/assets/342133/7901500/d108a4f2-0782-11e5-846d-dd6afb7c8cb7.png)

Ready for review and close.

**Comment by jim618** [comment]
This reads fine.
Generally shorter clearer text is preferable on a UI I think..

Closing

**Comment by jim618** [comment]
Trying out the UI, I think we should have:

"Bitcoin broadcasted successfully"
rather than
"Bitcoin sent successfully"

Then the flow is:

"Broadcasting your transaction to the Bitcoin network"
"Bitcoin broadcast successfully".

(In rest of UI)
Sending . .  .
then, after a confirmation
Sent

At the moment we are using 'Sent' to mean two different things.

**Comment by jim618** [comment]
I mean "broadcast" rather than "broadcasted" which I don't think is a word!

**Comment by jim618** [comment]
Decided on: 
"Transaction broadcast successfully:.

Screenshot:
![screen shot 2015-05-31 at 16 08 23](https://cloud.githubusercontent.com/assets/919427/7902361/5cbce874-07af-11e5-9815-ac207030bfb9.png)

**Comment by jim618** [comment]
Hmm, grammatically I think it should be "broadcasted" as it is the past tense but that is a horrible word.

I'll change it to "Transaction broadcast was successful"

**Comment by jim618** [comment]
![screen shot 2015-05-31 at 16 22 34](https://cloud.githubusercontent.com/assets/919427/7902427/4f4c980e-07b1-11e5-88ca-15bcc5773bd3.png)

That's enough bikeshedding. :-)

**Comment by gary-rowe** [comment]
Since we're painting the bike shed, how about "Transaction was broadcast successfully". Only joking. 

Closing.
