### ISSUE TITLE
Restore password for Trezor soft wallet does not show result (pass or fail)

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#585]
Going through a password restore for a BIP44 soft wallet does not yield any text in the report. It's just blank.

**Comment by gary-rowe** [comment]
It turns out I was being impatient. It just took a long time to get the seed from the seed phrase for some reason. This highlighted a UX problem so I've added a "Working" label so users don't give up too quickly. On completion (pass or fail) it is replaced with the report result.

Ready for review and close.

**Comment by jim618** [comment]
Just tried a restore from seed phrase for Trezor soft wallet.
Did not see the working label (i.e. saw report fine) but code review looks good so closing.
