### ISSUE TITLE
Inserting Trezor with old firmware crashed MBHD

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#588]
If you have MBHD running and insert a Trezor with old firmware, you see the 'old firmware alert' but then see the CrashReporter. Not only that but the CrashReporter is unusable as it keeps 'refreshing' over and over.
In the log is the error:
```
{"@timestamp":"2015-06-03T15:41:18.739+01:00","@version":1,"message":"Uncaught exception","logger_name":"org.multibit.hd.core.error_reporting.ExceptionHandler","thread_name":"AWT-EventQueue-0","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalStateException: LightBoxPopover should not be called unless a light box is showing\n\tat com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.components.Panels.showLightBoxPopover(Panels.java:365) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.wizards.AbstractWizardPanelView.checkForEnvironmentEventPopover(AbstractWizardPanelView.java:454) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.wizards.welcome.WelcomeAttachHardwareWalletPanelView.access$100(WelcomeAttachHardwareWalletPanelView.java:33) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.wizards.welcome.WelcomeAttachHardwareWalletPanelView$2.run(WelcomeAttachHardwareWalletPanelView.java:211) ~[multibit-hd.jar:na]\n\tat 
```

**Comment by jim618** [comment]
P.S. MBHD was showing a Trezor wallet (running 1.3.3) I removed it and then plugged in one running something older.

**Comment by gary-rowe** [comment]
This is another of those timer driven problems (this one uses a timer from MultiBit Hardware). I think we need to put in a one-off latch into the Error Reporter so that multiple exceptions are thrown away and we avoid stacking.

**Comment by jim618** [comment]
I'll do the latch in ErrorReporter

**Comment by jim618** [comment]
Modified ErrorReporterDialog so that only one is shown even with repeated events.
Also a 'bringToFront' added to prevent it being hidden by MBHD.

You can test it by doing repeated 'Report errors' in the help or adding new exceptions into the code to force crashes.
Awaiting review (of this change)

Assigning back to @gary-rowe to look at the proximal bug

**Comment by jim618** [comment]
Just tried recreating the initial bug but was unsuccessful.
I think once you've (@gary-rowe) checked the CrashReporter this can be bumped to Release 0.2

I think I saw the bug after a cold start with a full sync of a Trezor but cannot be sure

**Comment by gary-rowe** [comment]
Overall this is fine. I shortened some of the crazy-long variable names and added a bit at the end to ensure the application frame is disabled and the dialog is brought to the front in case people lose it.

I verified the operation with a couple of well placed stacked exceptions and it behaved correctly.

Closing.

**Comment by gary-rowe** [comment]
Re-opening to cover the crash case in Release 0.2

**Comment by jim618** [comment]
I thought it was quite a poetic name for an iterator:

iteratorThatCountsUpwardsMonotonicallyWithTheFullForceAndGustoOfAYoungManDeclaringHisLoveToHisBelovedGirlfriend

Calling it simply 'it' loses the magic I feel.

:-)

**Comment by gary-rowe** [comment]
Looks like 0.1.3 is turning into a "Trezor tune up" release.

**Comment by gary-rowe** [comment]
Tried this out with a 1.3.1 firmware device and 0.1.2 MBHD code. The security alert appeared and was dismissed. No sign of a crash reporter. It looks like the exception was a stacking issue and no longer applies.

Closing.
