### ISSUE TITLE
German translation uses Beenden for both Finish and Exit

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#589]
Screenshot:

![screen shot 2015-06-03 at 18 12 53](https://cloud.githubusercontent.com/assets/919427/7966483/4199bb66-0a1c-11e5-83d0-bbdbf61d9031.png)

**Comment by jim618** [comment]
I'll change the 'Exit' one to 'Ausfahrt' which is what autobahn exits are called over there

**Comment by jim618** [comment]
Also needs changes to sidebar text and text on 'Exit or Switch' panel (title, radio button text, exit button) for consistency

**Comment by jim618** [comment]
Updated and pushed.
Screenshot:

![screen shot 2015-06-03 at 21 16 08](https://cloud.githubusercontent.com/assets/919427/7970409/d831c3b6-0a35-11e5-83b9-7d9140dc3da0.png)

Awiating review and closing

**Comment by gary-rowe** [comment]
My German is pitiful so I'll just acknowledge that you've made the changes.

Closing.
