### ISSUE TITLE
Help | Report error can freeze UI / bring to front has disappeared

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#590]
This is a result of #588 

Now if you select Help | Report error:

+ the bring to front has disappeared.
+ if you press the report error button again and then press cancel on the report error the WHOLE of the MBHD UI becomes inactive, except for close

**Comment by jim618** [comment]
Oh you don't have to click it twice. A simple cancel on the error report locks the MBHD UI

**Comment by gary-rowe** [comment]
OK, that should fix it. Missed it earlier when I was thinking about it.

**Comment by jim618** [comment]
Looks good to me.
Closing

**Comment by gary-rowe** [comment]
This has the handy side effect of helping one find the missing dialog when reporting an error should it get hidden behind another window. Just click the "Report error" button once again and it'll pop to the front.
