### ISSUE TITLE
Cannot sign a multisig address using Trezor

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#591]
I just tried signing a transaction with a Trezor to a Copay multisig address.
It didn't work.
The Trezor just shows 'Signing transaction' forever.

**Comment by gary-rowe** [comment]
I've replicated this situation at my end. 

This is deep into the Tx processing code of MultiBit Hardware. The current code was not designed with P2SH in mind beyond selecting the output type. The structure of the input script is different and isn't being handled correctly. 

There are some ancillary UX issues arising from this:

* clicking Cancel only closes the Send wizard and leaves the Trezor hanging
* no adequate time out feedback to indicate something has gone wrong

Here's a [useful article detailing the structure of P2SH](http://www.soroushjp.com/2014/12/20/bitcoin-multisig-the-hard-way-understanding-raw-multisignature-bitcoin-transactions/) 

This will take a few days to fix.

**Comment by gary-rowe** [comment]
Scratch that last pessimistic post - I've just got it working :-)
![screen shot 2015-06-04 at 22 40 38](https://cloud.githubusercontent.com/assets/342133/7995080/c204a2cc-0b0a-11e5-9d35-9aa7d1f2b98a.png)

To verify just use the latest develop-SNAPSHOT of MultiBit Hardware and HD and attempt to spend to a P2SH address.

Ready for review and close.

**Comment by jim618** [comment]
Verified working fine for both P2SH and P2PKH addresses.
Closing

**Comment by jim618** [comment]
With further testing I noticed a defect in the MBHD display that is meant to match the Trezo display in signing. Screenshot:

![screen shot 2015-06-05 at 14 21 38](https://cloud.githubusercontent.com/assets/919427/8006776/a3abd212-0b8e-11e5-855f-fc1ff5c1cd03.png)

(It's in Spanish as I am checking the Spanish translation).

Note that the address that you are sending to is not shown. It is shown correctly on the Trezor secure display, just not in MBHD.
The tx gets signed and sent ok so it's just a UI glitch.

**Comment by jim618** [comment]
I have added code to both the Trezor Send and Trezor Empty Wallet screens so that multisig addresses are correctly shown to the user.

Awaiting review and closing by @gary-rowe

**Comment by gary-rowe** [comment]
Verified working.

Closing.
