### ISSUE TITLE
Seeing all tx unconfirmed and change tx not being spendable

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#592]
Checking Trezor operation today I am seeing this:

![screen shot 2015-06-05 at 11 46 29](https://cloud.githubusercontent.com/assets/919427/8004570/a6f2ab46-0b78-11e5-90fd-ddb8aa49486b.png)

This looks like something to do with the mempool.

Also seeing the change output of (Trezor) sends not being immediately spendable

**Comment by jim618** [comment]
You have to do a Repair wallet to get the wallet in a normal state again

**Comment by jim618** [comment]
And then if you close down MBHD and start it up again the problem comes back

**Comment by jim618** [comment]
This is due to some old transitive dependencies - we'll bump release numbers of bitcoinj-alice, multi bit-hardware and rebuild things which should eliminate this

**Comment by jim618** [comment]
If you build using the bitcoinj-alice 0.1.0 you should not see this anymore.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
