### ISSUE TITLE
Confusing message on slow send

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#593]
If you have a send that is a bit slow (but normal) you can see on the send progress the error message "some of your bitcoins are tied up" and THEN the broadcast tick appears. The error message is not cleared.

**Comment by jim618** [comment]
I have updated the SendBitcoinReportPanelView so that it always clears the detail message if it changes the primary message.
You can test this by forcing it to 'fail fast' by changing MainControler#NUMBER_OF_SECONDS_TO_WAIT_BEFORE_TRANSACTION_CHECKING to, say, 6 seconds rather than 60.

Then if you do a send you should see it 'fail' and then send successfully given a tidy success message.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
