### ISSUE TITLE
Create wallet help - does not mention create wallet button

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#595]
In the Create wallet help the paragraph "Enter password" mentions that create new wallet is in restore - this is now a separate button

**Comment by jim618** [comment]
Updated text to:
```
This is the first screen that you will see each time you start MultiBit HD. Simply enter your password and click the "Unlock" button (or press ENTER) to begin using your wallet. You can use the "Create" button to create a new wallet. You can use the "Restore" button if you forget your password or need to restore a wallet.
```

Awaiting review and closing

**Comment by gary-rowe** [comment]
I don't see a commit against this issue - has it been pushed?

**Comment by jim618** [comment]
Only pushed it in the website (so the internal MBHD help will be slightly out of date but I don't want to rebuild it)

**Comment by gary-rowe** [comment]
OK, it'll get included in the upcoming rebuild as a result of #599.

**Comment by gary-rowe** [comment]
Switching this to "awaiting issue" to better reflect the situation.

**Comment by gary-rowe** [comment]
Verified working. Should have updated this sooner.

Closing.
