### ISSUE TITLE
Sometimes Recipient field on Send is red on first opening

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#596]
Sometimes the Recipient field is background red on first opening.
Everything still works but it's a bit dissonant.

Put to Release 0.2 as it's a minor UI thing.

**Comment by gary-rowe** [comment]
Bumped to 0.1.3 since we should address it sooner rather than later and it appears to be straightforward to fix.

**Comment by gary-rowe** [comment]
Not seen this in a while. Is it still occurring?

**Comment by jim618** [comment]
I just tried to reproduce this but was not successful.

On my machine there is a very short red flash if the user clicks 'Cancel' on the Send form when the recipient field is empty before the dialog disappears but that is pretty minor.

I'll close this.
