### ISSUE TITLE
Where are the GPG signatures?

### ISSUE THREAD

**Issue by MrSkinny** [bitcoin-solutions/multibit-hd#597]
When I go to beta.multibit.org and click OS X, it immediately downloads the .dmg file. The auto-refreshing page tells you to check the signature, but when you [click that instruction](https://beta.multibit.org/blog/2013/07/24/how-to-check-signatures.html#Step 3) it directs you to the OLD Multibit website front page. This is not the right sig/download.

When I go to the [Multibit HD Downloads](https://beta.multibit.org/download.html) section directly, it does not provide signature links either, just release notes.

Thanks!

**Comment by jim618** [comment]
Yes - that is an oversight on the new web layout that we need to fix.
In the mean time you can access them all here:
https://multibit.org/releases/multibit-hd/multibit-hd-0.0.8beta/

**Comment by MrSkinny** [comment]
Thanks for the quick reply! Does it make sense to include sigs/shasums as a txt within the Github repo and on the official website? Then both logins would have to be compromised to keep them synced.

**Comment by jim618** [comment]
That's a good idea but if someone gets rights to all the other signing we do then we've probably been completely compromised and it's thus more work for no real extra security.

**Comment by jim618** [comment]
I've raised an issue in the website repo:
https://github.com/bitcoin-solutions/multibit-website/issues/211

**Comment by gary-rowe** [comment]
[MultiBit website issue #211](https://github.com/bitcoin-solutions/multibit-website/issues/211) is ready for review and has screen shots so that @MrSkinny can offer some feedback.

**Comment by gary-rowe** [comment]
Since this is a website issue, I'll bump this to Release 0.2 to take it out of the current release iteration.

**Comment by jim618** [comment]
Closing as MultiBit website issue 211 is now closed.
