### ISSUE TITLE
BouncyCastle is included in the final JAR which invalidates its signature

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#599]
This has several knock-on effects:

* all PGP/GPG encryption fails (BRIT addresses, error report upload)
* we may be forced to include it externally

AES is unaffected since it uses SpongyCastle which may offer an alternative route.

**Comment by gary-rowe** [comment]
Switching entirely to SpongyCastle (the Bitcoinj crypto provider) has resolved the JCA problem. The following modifications/verifications were made:

* upgrade the `PGPUtils` from BC 1.46 to SC 1.51.0.0
* remove BC dependency throughout
* verify existing wallets can be opened successfully (already SC dependent)
* verify error report can be uploaded (PGP encrypt)
* verify BRIT request response is working (PGP encrypt/decrypt)
* verify usual Bitcoin operations are unaffected

When running in either a signed or unsigned installer the SC operations worked without issue on Windows, OS X and Linux.

Ready for review and close.

**Comment by jim618** [comment]
Created signed installer and checked can open wallets, send, change password, update error report.
Closing
