### ISSUE TITLE
Firefox doesn't know how to open protocol (Bitcoin)

### ISSUE THREAD

**Issue by btcmacroecon** [bitcoin-solutions/multibit-hd#600]
Firefox doesn't know how to open this address because the protocol (Bitcoin) isn't associated with any program. How do I fix?
http://bitcoinmacroeconomics.com/2015/06/08/wildlife-photography-test-c/ … after copy address I see error @ waiting payment from you (blue)? solution?

I've tried everything and finally got Firefox updated to to latest version....(separate issue, I think)
Thanks. Love the wallet at Multibit, solved some problems on my end with litemode vs that darn core QT, way better.

**Comment by jim618** [comment]
Thanks - we'll add in some help about associating bitcoin protocols in browsers to MBHD.

Raised here: https://github.com/bitcoin-solutions/multibit-website/issues/212

**Comment by jim618** [comment]
The link you posted is incomplete - doesn't show anything

**Comment by btcmacroecon** [comment]
![screenshot from 2015-06-09 09 20 07](https://cloud.githubusercontent.com/assets/7543793/8065820/ceaffb52-0e98-11e5-9dfa-c90de94fc19e.png)   thanks for your assistance, I look forward to resolving. Couldn't do it without ya!

**Comment by btcmacroecon** [comment]
I attached a screenshot. Thanks for your prompt service!

**Comment by btcmacroecon** [comment]
Hello, I am new here and not sure if I can bump this up but just trying to resolve this issue as it is work in progress (educating....)....but not sure how to fix this protocol error in Firefox. Your assistance would be greatly appreciated. I have been told by Firefox community that I need to maybe ask MultiBit. Does that sound right?

**Comment by gary-rowe** [comment]
I can't tell which operating system you're using from the screenshot. If you're using MultiBit HD 0.1.0+ you can use Help | Report error to upload an error report containing all this information in an anonymous and encrypted manner.

When I was writing the [Linux installation guide](https://beta.multibit.org/en/help/hd0.1/how-to-install-linux.html) I needed to fix the Firefox problem and the information there may help.

**Comment by btcmacroecon** [comment]
thanks, just trying to keep on marching...work in progress....very cool
stuff.

**Comment by gary-rowe** [comment]
Are we OK to close this now?

**Comment by jim618** [comment]
Yeah - it is firefox configuration
