### ISSUE TITLE
Crash at startup (A fatal error has been detected by the Java Runtime Environment)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-solutions/multibit-hd#601]
After typing in the wallet words, the program crashes while trying to create the wallet. Maybe fedora is not supported due to lack of the required crypto libs?

Some lines which may be helpful:
```
# JRE version: OpenJDK Runtime Environment (7.0_79-b14) (build 1.7.0_79-mockbuild_2015_04_15_06_33-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.79-b02 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.5.5
# Distribution: Built on Fedora release 20 (Heisenbug) (Wed Apr 15 06:33:03 UTC 2015)
# Problematic frame:
# C  [libc.so.6+0x93e60]  __memcpy_sse2_unaligned+0x1e0
```
and
```
Stack: [0x00007f5d5f9fc000,0x00007f5d5fafd000],  sp=0x00007f5d5faf8e98,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x93e60]  __memcpy_sse2_unaligned+0x1e0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.lambdaworks.crypto.SCrypt.scryptN([B[BIIII)[B+0
j  com.lambdaworks.crypto.SCrypt.scrypt([B[BIIII)[B+14
j  org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(Ljava/lang/CharSequence;)Lorg/spongycastle/crypto/params/KeyParameter;+71
j  org.multibit.hd.core.crypto.AESUtils.generate160BitsOfEntropy([B[B)[B+54
```

Is there any way I can send you the error report file in private?

**Comment by gary-rowe** [comment]
Thanks for the feedback. The crash reporter should have provided you with an upload button. However for something related to crypto like this it's probably going to fail.

Can you [review the Linux installation guide](https://beta.multibit.org/en/help/hd0.1/how-to-install-linux.html) and see if the solutions offered there provide a solution?

**Comment by MarcoFalke** [comment]
Removing the libs from the installed jar file fixed it. Thank you.

```zip -d "multibit-hd.jar" lib/x86_64/{freebsd,linux}/libscrypt.so```

**Comment by gary-rowe** [comment]
Glad it worked out :-)
