### ISSUE TITLE
Trezor "Operation failed" contains a "Success" message

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#603]
Uploaded error report contains this exception:

```
 	java.lang.ClassCastException: org.multibit.hd.hardware.core.messages.Success cannot be cast to org.multibit.hd.hardware.core.messages.Failure
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.showOperationFailed(CredentialsWizardModel.java:361) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractHardwareWalletWizard$9.run(AbstractHardwareWalletWizard.java:321) ~[multibit-hd.jar:na]
```

With surrounding log messages indicating a `Success` was generated but wrapped in a `SHOW_OPERATION_FAILED`. 

Sequence of events appears to be

* unlock Trezor hard wallet
* do nothing
* receive spontaneous `Success` message from device after approx 15mins of inactivity

Possibilities include browser connected to mytrezor.com or spontaneous message from device for keep-alive purposes.

**Comment by gary-rowe** [comment]
Paging @prusnak to see if there is a situation with myTrezor.com, or internally to the Trezor device, where, after almost exactly 15 mins, a Ping or other message with a `SUCCESS` response is sent. Perhaps a session clear?

The log has device going idle (from MultiBit's perspective) at `22:43:57.176` then a spontaneous `SUCCESS` message occurs at `22:58:57.960` which is 900.784 seconds later.

**Comment by prusnak** [comment]
Yes. myTREZOR sends ClearSession message after 15 minutes of inactivity and Success message is returned.

**Comment by gary-rowe** [comment]
Thanks, @prusnak, that clears this little mystery up. I'll put in some extra code to gracefully handle this situation in MultiBit Hardware.

**Comment by gary-rowe** [comment]
Ready for code review and close.

**Comment by jim618** [comment]
The fix for this is in the referenced multibit-hardware issue, now closed.
Closing.
