### ISSUE TITLE
"Open containing folder" executes the download file

### ISSUE THREAD

**Issue by MrSkinny** [bitcoin-solutions/multibit-hd#609]
Just launched Multibit HD OSX and the auto-update installer appeared to download v0.1.0 .dmg. Once download was completed, it brings up the dialog:

* Execute installer now
* Manually install later
  * [Open Containing Folder](#)

The "Open containing folder" link should open the ~/downloads folder or whatever folder the installer was retrieved into. Instead, it launched the .dmg (mounted the drive).

**Comment by jim618** [comment]
I think we want to bump this to 0.2 - I don't think it's a quick fix.

**Comment by gary-rowe** [comment]
Not sure I'm understanding the issue here. On OS X the `.dmg` contains the latest version of the installer. To run this manually you'd need to open the `.dmg` you'd just downloaded and double click the installer contained within - the manual option facilitates this by presenting the installer.

**Comment by MrSkinny** [comment]
Yeah, I'm relatively new to OS X so I was actually not sure if that terminology is standard in installers. In Windows, I would consider "Open Containing Folder" to just send me to the appropriate directory of the received `.zip` or `.exe` in Explorer. The same sort of context as this Downloads list in Chrome:

![image](https://cloud.githubusercontent.com/assets/3757471/8192787/82245ae8-1425-11e5-9071-3652b865a16e.png)

**Comment by gary-rowe** [comment]
I see where you're coming from. On OS X it's a bit different due to the wrapping performed by the `.dmg` which is essentially a mounted drive.

I think this can be closed, but thank you for the feedback and please continue to provide more as you explore the application.
