### ISSUE TITLE
Date stamp default for non Multibit users

### ISSUE THREAD

**Issue by negedzuregal** [bitcoin-solutions/multibit-hd#615]
Users who want to open a bip32 compliant passphrase do not have a datestamp (which format is it ???). Can a default one be used in that case ?

**Comment by jim618** [comment]
There is a default one used, which is the 'earliest age of an HD wallet'.
MultiBit HD then syncs from then.

This is similar to an extant Trezor wallet where we don't know how old the wallet is.

Thus you can just enter yout BIP 32 passphrase and leave the date stamp blank.
The tooltip indicates you can leave it blank IIRC - we didn't put it on the UI so as not to clutter it up.

Closing as already implemented
