### ISSUE TITLE
Send / Request disabled

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#616]
I saw the Send / Request buttons disabled with a Trezor wallet after a block was mined (I think)

Screenshot:

![screen shot 2015-06-18 at 16 42 31](https://cloud.githubusercontent.com/assets/919427/8235332/45229ed8-15d9-11e5-9f2b-2422f8a7c546.png)

**Comment by gary-rowe** [comment]
Possibly related to #620 in terms of approach.

**Comment by jim618** [comment]
Just tried reproducing this with a regualr wallet, left open over a new block creation.
Send / Request and Empty wallet buttons all worked properly.

Reviewing the code I cannot see anything obvious wrong with it it.

Suggest closing.

**Comment by jim618** [comment]
Code is in SendRequestScreenView/updateSendRequestButtons

**Comment by gary-rowe** [comment]
I haven't seen this at my end in a long time and the code looks fine.

Closing, with the proviso that we'll re-open if we get reports of it happening again.
