### ISSUE TITLE
multibit.org website shows strange symbols

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#617]
When visiting https://multibit.org, on the right side the bullets of the list "Why choose MultiBit HD ?" are shown as strange symbols, see screenshot.

Environment:
Debian Jessie 64 Bit
Iceweasel 31.7.0
NoScript Extension that blocks javascript from multibit.org, ajax.googleapis.com, bootstrapcdn.com and fonts from fonts.gstatic.com and maxcdn.bootstrapcdn.com etc.
Using Proxy privoxy

A good website should work without (third party) JavaScript, fonts etc., IMHO.

![multibithd](https://cloud.githubusercontent.com/assets/8447873/8235555/f2f2e9e2-15e2-11e5-9f3a-7ec1104daf7d.png)

**Comment by jim618** [comment]
We have a separate repo for the website so I have cross posted it in there:
https://github.com/bitcoin-solutions/multibit-website/issues/217

**Comment by wodry** [comment]
Sorry for posting in the wrong project

**Comment by jim618** [comment]
No problem !

**Comment by jim618** [comment]
I close this issue as the other issue in the website repo will be the one we work against.
