### ISSUE TITLE
Seeing 'wallet is ready to use' but still syncing

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#620]
I have seen on the Wallet start up page 'Your wallet is ready to use' whilst the wallet is still syncing.
This is a bit confusing to users.

I suspect it is extra Bitcoin network status messages being sent, perhaps when the PeerGroup swops peers or something like that.

**Comment by jim618** [comment]
Pushed changes that check whether download is still occurring in BitcoinNetworkService before firing off 'I'm done' events. Different peers can have different peer heights and 'I'm done' can mean when the lower height of a peer is reached (which can be halfway through the download).

Tested on all my wallets and repair wallet done without seeing anomalous behaviour.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working with several wallets. No sign of an overlap.

Closing.
