### ISSUE TITLE
Change Trezor affiliate link to a=multibit.org

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#622]
As per: 
https://github.com/bitcoin-solutions/multibit-website/issues/223

**Comment by gary-rowe** [comment]
Updated all references.

Ready for review and close.

**Comment by jim618** [comment]
There was one reference missed in trezor.html that I have updated and pushed.
Checked in UI in trezor help and the trezor 'Buy trezor' command.

Closing
