### ISSUE TITLE
multibit.org failover: Remove update.xml network dialog

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#623]
If multibit.org is down at startup of MBHD the user gets a dialog titled 'Internet connection - MultiBit HD'.
This doesn't do any good and is just a distraction so we should eliminate it.

**Comment by gary-rowe** [comment]
Bringing this into 0.1.1 as we're doing some other related work there and it's a trivial change: Installer | Screens and Actions | Updater | Startup | Check for Update.

* untick ask for proxy
* connect timeout reduced to 2,000 (we respond in 58ms typically)
* read timeout reduced to 2,000

These settings will reduce the startup time in the absence of multibit.org. 

Consider "failure strategy" of Continue on failure in this case.

**Comment by gary-rowe** [comment]
Assigning you, Jim since you're "Installer guy" for 0.1.1 :-)

**Comment by jim618** [comment]
Updated install4j as per points above. Also selected 'Contine on failure' so that the main installer will run.
Tested by switching WiFi off and on and installing in both cases.

Pushed updated install4j project (in bitcoin-solutions/multibit-installer project)
Awaiting review and closing

**Comment by gary-rowe** [comment]
All fine (and released).

Closing.
