### ISSUE TITLE
CrashReporter: PaymentChannel enum failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#627]
"@timestamp": "2015-06-22T16:00:30.166+02:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "java.lang.IllegalArgumentException: No enum constant org.multibit.hd.ui.views.screens.Screen.PAYMENT_CHANNELS at java.lang.Enum.valueOf(Enum.java:236) ~[na:1.7.0_80] at org.multibit.hd.ui.views.screens.Screen.valueOf(Screen.java:12) ~[multibit-hd.jar:na] at org.multibit.hd.ui.views.SidebarView.createSidebarContent(SidebarView.java:177) ~[multibit-hd.jar:na] at org.multibit.hd.ui.views.SidebarView.<init>(SidebarView.java:98) ~[multibit-hd.jar:na] at org.multibit.hd.ui.views.MainView.createMainContent(MainView.java:400) ~[multibit-hd.jar:na] at

**Comment by jim618** [comment]
Also seeing:
"java.lang.NullPointerException: null at org.multibit.hd.ui.views.MainView.unsubscribe(MainView.java:464) ~[multibit-hd.jar:na] at org.multibit.hd.ui.controllers.MainController.onShutdownEvent(MainController.java:167) ~[multibit-hd.jar:na] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_80] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80] at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[multibit-hd.jar:na] at

**Comment by gary-rowe** [comment]
That `PAYMENT_CHANNELS` enum looks like a StrawPay issue. The user in question may be re-using an old wallet previously created with StrawPay.

Paging @ollekullberg for a comment.

**Comment by gary-rowe** [comment]
I've set the default to be the same as the configuration in case of failure.

Ready for review and close.

**Comment by jim618** [comment]
You've put the screen default to help in 881526a and Send/Request in db7176f.
Suggest it is Send/Request in both (for the Help network dependency you mention)

**Comment by gary-rowe** [comment]
I think you missed that the second push corrects the error in the first.

**Comment by jim618** [comment]
Yeah I missed that it was the same code changing.
Fine with the end result.
Closing

**Comment by ollekullberg** [comment]
I agree, this must be someone messing with my version of MBHD.

**Comment by gary-rowe** [comment]
@ollekullberg It might be worth you checking/adjusting the `InstallationManager` in your fork so that it targets a different `MBHD_APP_NAME` (and other bits and bobs in there too).

**Comment by ollekullberg** [comment]
Ok
