### ISSUE TITLE
Provide a currency ticker for instant exchange rate

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#630]
User feedback has indicated that having a currency ticker is a useful tool. 

Two locations come to mind:
* the top right corner (as in Classic) - might be too confusing during Unconfirmed situations
* the right of the status bar to the left of Peer count

I think this would be useful to reinstate and positioning it in its own box on the footer bar would be a familiar place to look for it (Office apps often place information there so mainstream-friendly location).

**Comment by jim618** [comment]
Let's not do this.

It clutters up the UI.

**Comment by gary-rowe** [comment]
We could have it as an optional configuration. When I use Classic I do tend to note the current exchange rate in passing as a measure of "Bitcoin health". It only needs to be a single number with a currency symbol in the footer. I don't see it as clutter.

**Comment by jim618** [comment]
Let's just keep MultiBit as a wallet

We've deliberately reduced the number of visual elements to a minimum to keep things clear and easy to understand. Let's NOT start putting them all back

**Comment by gary-rowe** [comment]
OK, we're at an impasse here. I'll toss this into the Graveyard on the grounds of "it's work and other stuff needs to be done" and we'll see if user feedback resurrects it.

**Comment by jim618** [comment]
okey dokey
