### ISSUE TITLE
Install on USB Drive

### ISSUE THREAD

**Issue by manu777** [bitcoin-solutions/multibit-hd#632]
hello,
how can i install MultiBitHD on a external USB drive include the wallets and all other stuff?

i found the wallets under: C:\Users\<Name>\AppData\Roaming\MultiBitHD

best regards

**Comment by jim618** [comment]
Hi Manu,

Running everything from a USB drive is not supported in MultiBit HD.

There is a detailed explanation in the help here:
https://multibit.org/en/help/hd0.1/backups.html
It's the section:
"What about storing wallets directly on USB keys ?"

Basically when you add up the things that can go wrong the error rate is too high for us to support it.

Regards,

Jim

**Comment by gary-rowe** [comment]
Closing due to nothing further to be done.
