### ISSUE TITLE
Better error reporting when connecting by Tor fails

### ISSUE THREAD

**Issue by RaidForums** [bitcoin-solutions/multibit-hd#634]
Operating System: Windows 7 Ultimate - Service Pack 1
  MultiBit HD Version: 0.1.0

Every time i try go on my wallet, the password gets accepted but the wallet never connects to the peers.
I have tried port forwarding...
I have tried Repairing Wallet...
I have tried disabling all firewalls / avs...
I have tried resetting Router...
I have cleared everyone on internet explorer...
I have flushed dns and updated Policy...
I have reinstalled MultiBit and Java...
I have restarted my pc...

The thing that bugs me the most is that it was working perfectly 10 hours ago or so.

__________________________________________________________
I later realised the problem was the bitcoin wallet was on use tor "on".
Turned that to off and perfect. Fixed the error.

**Comment by RaidForums** [comment]
Error Log I found on directory of program...
http://pastebin.com/W3JmceLV

**Comment by gary-rowe** [comment]
While the issue was resolved by OP it highlights a user interface issue. An alert bar should appear if a Tor connection cannot be made within a reasonable time (perhaps 60s).

**Comment by gary-rowe** [comment]
Closing this in favour of full solution in #633.
