### ISSUE TITLE
No 'OER is not responding' for OER rates

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#638]
I usually use OpenExchangeRate. It has not been supplying data regularly in the last day or two but I am NOT seeing a 'OpenExchangeRate is not responding' alert at start up.

MBHD fails over cleanly - you just don't get fiat info but there should be an alert

**Comment by jim618** [comment]
Looks like it's a redirect:

![screen shot 2015-06-30 at 15 31 19](https://cloud.githubusercontent.com/assets/919427/8433396/6a795e8e-1f3d-11e5-8718-469377c9d429.png)

So OER has probably changed it's interface.
Anywhich way MBHD should respond appropriately

**Comment by jim618** [comment]
OER seems to be working now but there probably needs to be some tidy up so that it fails over better

**Comment by jim618** [comment]
I have added in a check for HttpStatusIOException which I think will cover it.
You can check for a related HTTP error code (409 - Conflict) by setting your exchange to OER/ GBP and then trying to switch to Hitbtc. The HTTP error code gets exposed on the UI correctly.

I believe this should also catch similar 303 errors when they occur again. (OER is not showing these errors currently.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Reduced error logging level. Closing.
