### ISSUE TITLE
Help container is not always drawing top border

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#639]
The help scrollpane sometimes does not have the top border drawn.
Looks a bit poor.
If you resize the screen it draws so it's probably a painting issue

**Comment by gary-rowe** [comment]
Can you provide a screen shot of it happening?

**Comment by jim618** [comment]
Just tried about twenty different pages in the help going clickety click and could not reproduce it.

I'll close it (nothing to do) unless I come across it again and get a screen shot
