### ISSUE TITLE
Make payment scrolling smoother with smaller increment

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#641]
I find the payment window scrolling a bit jerky.
It might look better with a smaller scroll increment so that it is smoother (albeit slower).

**Comment by jim618** [comment]
Experimenting you only got a smooth scrool with a very small increment (4 pixels or so) which is too slow to be useful.
Settting the scroll increment to be the row height works quite well and you can still navigate long lists so I have set it to that.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Works well. Closing.
