### ISSUE TITLE
BlockStore save failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#643]
"_score": null,
"_source": {
"@timestamp": "2015-07-02T17:05:47.152+07:00",
"level": "ERROR",
"thread_name": "safe-fixed-sync-wallet-0",
"logger_name": "org.multibit.hd.core.services.BitcoinNetworkService",
"message": "Blockstore not closed cleanly",
"stack_trace": "org.bitcoinj.store.BlockStoreException: Store closed at org.bitcoinj.store.SPVBlockStore.getChainHead(SPVBlockStore.java:229) ~[multibit-hd.jar:na] at org.multibit.hd.core.services.BitcoinNetworkService.closeBlockstore(BitcoinNetworkService.java:1504) [multibit-hd.jar:na] at org.multibit.hd.core.services.BitcoinNetworkService.replayWallet(BitcoinNetworkService.java:294) [multibit-hd.jar:na] at org.multibit.hd.core.managers.WalletManager$2.call(WalletManager.java:1142) [multibit-hd.jar:na] at org.multibit.hd.core.managers.WalletManager$2.call(WalletManager.java:1135) [multibit-hd.jar:na] at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_65] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65] at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65] ",
"level_value": 40000,
"@version": 1
},

**Comment by jim618** [comment]
Looking at the upload log this is not causing a problem - it is a close before the replay starts and te block ctore is reopened.

I've changed the logging to WARN rather than ERROR so that it does not giv false positives when searching the upload logs.

Awaiting review and closing

**Comment by gary-rowe** [comment]
LGTM - closing.
