### ISSUE TITLE
Increase range of possible fees

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#650]
I think because of the ongoing flooding of the network we should increase the range of fees possible.

Currently we have a slider:

Min: 1000 sat per KB
Default: 3000 sat per KB
Top: 10,000 sat per KB
Increment: 100 sat
Show 9 x10 increments i.e 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000

If you look at TradeBlock you can see there are lots of tx at around 10,000 sat per KB and above

Perhaps change it to:
Min: 1000 sat per KB
Default: 3000 sat per KB
Top: 51,000 sat per KB
Increment: 500 sat
Show 9 x 10 intervals i.e 1000, 6000, 11000, 16000, 21000, 26000, 31000, 36000, 41000, 46000, 51000

**Comment by gary-rowe** [comment]
What about ditching the slider and using a spinner instead?

**Comment by jim618** [comment]
A spinner doesn't give any sense of distance relative to minimum/ default/ maximum.
Would be easier to cover the range of values though

**Comment by jim618** [comment]
Note: we want to avoid the user typing in a number if possible.
All the localisation issues (, . ) for fees is a PITA.

**Comment by gary-rowe** [comment]
OK. A spinner is out on localisation and resulting size perception (1000 10000 100000 are very similar without localisation). Let's try your approach and see how it works in practice.

**Comment by jim618** [comment]
I have tweaked the slider so that it now has settings:

Min: 1000 sat per KB   (same as before)
Default: 10000 sat per KB (a reasonable value to get confirmed with the current network spam flooding)
Top: 50,000 sat per KB (0.5 mBTC / KB)
Increment: 200 sat (previously 100 sat)

Screen shots:

![screen shot 2015-07-09 at 09 51 08](https://cloud.githubusercontent.com/assets/919427/8591480/7c2311ea-2620-11e5-94a0-2faac5e8ea59.png)

![screen shot 2015-07-09 at 09 51 17](https://cloud.githubusercontent.com/assets/919427/8591483/815a216c-2620-11e5-8f11-7dca8ae96590.png)

![screen shot 2015-07-09 at 09 51 24](https://cloud.githubusercontent.com/assets/919427/8591486/85a953a0-2620-11e5-93b7-1a2f6d7ab589.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Works fine. Closing.
