### ISSUE TITLE
Update Bitcoinj to latest version 0.13.2

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#652]
The latest version of Bitcoinj contains many fixes that we should include. In particular a fix for Tor connectivity (see #651) in Orchid 1.2.

We should use bitcoinj 0.13 when it is released

**Comment by jim618** [comment]
Probably need to bump to use bitcoinj 0.13.2 when it comes out (in a week) as that is fixing some regressions in 0.13.1

**Comment by jim618** [comment]
There is a new update to alice:
release-0.13.2-alice-0.1.3

There is a branch pushed and the artifacts are in the staging repo.

It does NOT increment the version of Tor though - it is a few bug fixes to Wallet/ Transaction etc.
thus the Tor connectivity problems we've been seeing are not addressed by this bump.

It still needs all the intermediate repos (multbit-commons) etc updated. I have jammed in the dependency into the MBHD develop pom.

MBHD appears to work exactly as before - done sync, repair wallet, send/ receive etc.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
@jim618 Can you build the latest MBHW as develop-SNAPSHOT and verify that it correctly generates expected addresses for a Trezor wallet, please? Ideally using a fresh wallet compared against, say, https://dcpos.github.io/bip39/.

There was an API change in Bitcoinj that moved the `Utils.doubleHash()` into `Sha256Hash.hashTwice()` which is used in the `GetPublicKey` of MultiBit Hardware. I'm confident it's OK due to my own testing, I just want independent verification.

**Comment by jim618** [comment]
Successfuly tried out on a Mac:
+ empty and wipe existing Trezor wallet.
+ create new Trezor wallet
+ fund with 11 transactions from Classic
+ wait for confirmation on Trezor
+ check 2 receive addresses against https://dcpos.github.io/bip39/.
+ send 3 transactions out from Trezor
+ perform empty wallet on Trezor.

This all worked as expected.

Will install on the Windows 8 machine and try that out next

**Comment by jim618** [comment]
I have performed a similar test on the Windows 8 machine and it all worked correctly.
Closing
