### ISSUE TITLE
'Unexpectedly high' fee message on Trezor not replicated in MBHD

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#657]
I just increased my fee to 0.000 15 BTC/ KB.

When I do a send with my Trezor it shows, in order:
1) Confirm sending 0.002 BTC to "an address"/
Click OK on Trezor
2) Fee 0.00015 BTC is unexpectedly high. Send anyway ?
This is NOT shown in MBHD - you get a confusing empty trezor message. See screen shot.

![screen shot 2015-07-12 at 13 54 26](https://cloud.githubusercontent.com/assets/919427/8637858/d62a1c18-289d-11e5-8fca-0cff74e73209.png)

Click OK on Trezor
3) Really send 0.00215 BTC from your wallet ? Fee included 0.00015 BTC
Click OK on Trezor to send

**Comment by jim618** [comment]
Just to clarify: the send gets sent correctly - it's just the extra interstitial screen does not display in MBHD.

**Comment by gary-rowe** [comment]
Added support code for the additional button press request. Here's a screen shot:

<img width="1012" alt="screen shot 2015-07-26 at 15 23 51" src="https://cloud.githubusercontent.com/assets/342133/8894454/dfa24c90-33ae-11e5-89ad-498219210538.png">

It follows the same formatting pattern that we use everywhere else and has been applied to both Send and Empty use cases.

Supporting code (MultiBit Hardware and hid4java) has been pushed to Maven staging repo

Ready for review and close.

**Comment by jim618** [comment]
Confirmed the 'high fee' message appears ok.
Closing
