### ISSUE TITLE
Add fee rate (sat/byte) to help users

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#658]
In light of the ongoing spam, the fee rate of satoshi/byte is a useful measure for if a tx will 'get past the spam'.

We know the fee on sends so could add a fee rate next to it/  below it in the transactions details wizard.

**Comment by gary-rowe** [comment]
Do you mean after the fact (as in transaction details on Payments) or before the fact (as in confirmation screen on Send)?

**Comment by jim618** [comment]
It is most useful on the send confirmation screen but could appear on both. My inclination would be to put it on both.
It does not need to be stored as you can work it out (for sends where you have the tx fee stored).

Fee rates seem to have standardised on satoshi/byte e.g. see http://www.cointape.com

**Comment by jim618** [comment]
I have added the transaction fee rate, with units 'sat/byte' to the transaction details page.
It cannot be added to the Send confirm screen though as, at this point, the transaction is not signed so you do not know how big it is when serialised.

You can cross check the fee rate by selecting 'smartbit.com.au' as your block explorer as that bock explorer show fee rate.

Awaiting review and closing.

**Comment by jim618** [comment]
Screenshot:
![screen shot 2015-10-08 at 13 16 00](https://cloud.githubusercontent.com/assets/919427/10369020/ff68c4c2-6dcf-11e5-9111-61995f285f7d.png)

**Comment by gary-rowe** [comment]
Verified working.

Closing.
