### ISSUE TITLE
Chinese in titles not rendering on Windows

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#660]
On the Windows test machine none of the Traditional or Simplified Chinese titles are rendering in the light box. Actually a couple render - 'Manage wallet | Edit wallet and Payments', 'Tools | Appearance' options
The text in the body of the lightbox is rendering. It is just the titles.

It renders ok on Mac

I'll assign this to Gary as he has a Windows dev machine.

**Comment by jim618** [comment]
This has been introduced in 0.1.2
It works fine in 0.1.1

**Comment by jim618** [comment]
Most likely suspect for the cause of this fault is #384

**Comment by gary-rowe** [comment]
Confirmed. It is definitely the "SwingUtilities2" property causing the problem. However it only manifests in the Impact Regular font we provide which is used in the "non-Latin" languages (Arabic, Chinese, Farsi, Greek etc). Curiously, the anti-aliasing issue does not manifest in this font.

Therefore a fix is to only allow anti-aliasing for Corben and Open Sans which seems to work well.

Ready for review and close.

**Comment by jim618** [comment]
Confirmed working on Mac and Windows for Chinese, German, Arabic, English, various languages.
All titles appear and anti-aliaising is working.

Closing
