### ISSUE TITLE
Tamil is mainly not rendering on windows

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#661]
The Tamil translation is not rendering properly on Windows.
Except for the title bar all you see is little squares.

**Comment by jim618** [comment]
For non-tamil users (that may not have Tamil characters loaded) I have replaced the Tamil writing system text for Tamil in the language drop down with a simple 'Tamil' (in English). This will prevent non-Tamil users seeing little squares in the language drop down and won't particularly affect Tamil speakers.

(It does not fix Tamil characters actually rendering properly)

**Comment by gary-rowe** [comment]
This went out in the 0.1.2 release so closing.
