### ISSUE TITLE
Wallet will not connect to network 

### ISSUE THREAD

**Issue by OB-1Kanoby** [bitcoin-solutions/multibit-hd#666]
![screenshot 2015-07-17 12 37 45](https://cloud.githubusercontent.com/assets/13323246/8753671/3c437420-2c83-11e5-95d9-2751d1abdd28.png)
![screenshot 2015-07-17 12 39 28](https://cloud.githubusercontent.com/assets/13323246/8753672/3c4a1a00-2c83-11e5-9467-971376b18fe6.png)
![screenshot 2015-07-17 12 40 27](https://cloud.githubusercontent.com/assets/13323246/8753675/3c52913a-2c83-11e5-92c7-a2f13b4b7c8a.png)
![screenshot 2015-07-17 12 40 51](https://cloud.githubusercontent.com/assets/13323246/8753673/3c4d2d12-2c83-11e5-8e6f-62af42e47a83.png)
![screenshot 2015-07-17 12 41 40](https://cloud.githubusercontent.com/assets/13323246/8753674/3c4e8f2c-2c83-11e5-82c2-f1cb0c8c943d.png)
My MBHD wallett will is not connect to network. Will not verify. Therefor it cannot show bitcoins, cannot send or request. I don't know if I've lost my bitcoins or what is going.

**Comment by OB-1Kanoby** [comment]
My MBHD wallett will is not connect to network. Will not verify. Therefor it cannot show bitcoins, cannot send or request. I don't know if I've lost my bitcoins or what is going.

**Comment by jim618** [comment]
Have you had a read of the help on 'Verify network', which explains the port (8333) that MultiBit HD needs to be open to connect to the Bitcoin network.

If you LAN/ router/ firewall is blocking it you would not be able to connect

**Comment by OB-1Kanoby** [comment]
On 2015-07-18 05:59, Jim Burton wrote:
> Have you had a read of the help on 'Verify network', which explains
> the port (8333) that MultiBit HD needs to be open to connect to the
> Bitcoin network.
> 
> If you LAN/ router/ firewall is blocking it you would not be able to 
> connect
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bitcoin-solutions/multibit-hd/issues/666#issuecomment-122530011
I have opened Port 8333 and 8330 That's not the problem. I've turned of 
antivirus I've tried to create new walletts I've uninstalled cleaned all 
traces from my computer and reinstalled. It did not allow options like 
create passwords and write down passwords or print and when it opens it 
excepts the same password and still won't connect and verify. I'm at the 
end of my rope and need a life line.

**Comment by jim618** [comment]
The Lighthouse wallet uses exactly the same wallet words as MultiBit HD so I suggest:
1) Download Lighthouse from https://www.vinumeris.com/lighthouse
2) Setup your wallet (in Lighthouse) with the same wallet words as your MultiBit HD wallet
3) Wait and see if it syncs. If it does, you have control of your bitcoin again.
4)  If it does NOT sync then almost certainly it's a problem with your local network environment.  Lighthouse uses the same same library for its Bitcoin network connection as MultiBit HD. Try using a different machine or a different network (e.g. coffee shop wifi normally works).

**Comment by Baltsar** [comment]
Same issue here, gonna try another network.

**Comment by gary-rowe** [comment]
Looks like it's a Tor issue (you have the lock in the bottom right hand corner in your screenshots). This is a known problem with 0.1.1 and 0.1.2 (see #651 for details and #652 for solution).

Can you confirm that you can connect without Tor enabled (Labs | Tor)?

**Comment by Baltsar** [comment]
If you referring to me im using Firefox / Google Chrome and on a mac. Not Tor. Have the same issue as post creator.

**Comment by gary-rowe** [comment]
@Baltsar Apologies, it was a general message to the thread. I think further clarification by me is needed. 

From the screen shots it appears that the Tor configuration has been enabled within MultiBit HD (Preferences | Labs | Tor). This setting activates a self-contained Tor access framework which doesn't require any further system configuration by the user (no Chrome/FF etc). It has a known bug in some version of MultBit HD which can cause this behaviour.

If you could make the change to turn off Tor within MultiBit HD you should find network connectivity is restored.

**Comment by Baltsar** [comment]
@gary-rowe Thank you Gary, It solved my problem. Much appreiceted

**Comment by gary-rowe** [comment]
No worries. I'll close this here since we have a pending fix in another issue.

**Comment by suryadewa** [comment]
i also have some problem about this .. but now solved. i exit Kaspersky Internet Security and Turn oFF windows firewall :)

**Comment by badpasss** [comment]
plz i need help

**Comment by badpasss** [comment]
i just load my multibit hd  today and its stop working

**Comment by badpasss** [comment]
telling me there was an error in creating a connection to the bitcoin network can somebody plz help me out its my first time using this app

**Comment by rolandbreedveld** [comment]
Same issue here, it's not a network problem while my other app (BitCoin Core) is working fine.
 ERROR [PeerGroup Thread] o.b.c.PeerGroup - Peer discovery failure, class:org.bitcoinj.net.discovery.PeerDiscoveryException, message:No peer discovery returned any results: check internet connection?
