### ISSUE TITLE
Cannot open YAML file - permission denied

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#671]
"_index": "error-report-entries-ec9e35c",
"_type": "log-entry",
"_id": "126",
"_score": null,
"_source": {
"@timestamp": "2015-07-19T13:02:23.002+08:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.io.FileNotFoundException: /Users/*blank*/Library/Application Support/MultiBitHD/mbhd.yaml (Permission denied) at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_80] at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_80] at java.io.FileOutputStream.<init>(FileOutputStream.java:171) ~[na:1.7.0_80] at org.multibit.hd.core.config.Configurations.persistCurrentConfiguration(Configurations.java:109) ~[multibit-hd.jar:na] at org.multibit.hd.ui.views.wizards.welcome.WelcomeLicencePanelView.updateFromComponentModels(WelcomeLicencePanelView.java:169) [multibit-hd.jar:na] at org.multibit.hd.ui.views.wizards.welcome.WelcomeWizard$1.actionPerformed(WelcomeWizard.java:153)

**Comment by gary-rowe** [comment]
In this situation the user is unable to persist the configuration, so leaving the original in place is the safer solution. Typically a user will be shutting down at this stage so we don't have a realistic opportunity to inform them of the failure and showing an error dialog is too much. 

Ready for review and close.

**Comment by jim618** [comment]
LGTM. Closing.
