### ISSUE TITLE
Connections closed by remote host

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#672]
No errors in the upload but looks odd

{
"_index": "error-report-entries-fcc561a",
"_type": "log-entry",
"_id": "758",
"_score": null,
"_source": {
"@timestamp": "2015-07-18T14:03:48.097+01:00",
"level": "WARN",
"thread_name": "NioClientManager",
"logger_name": "org.bitcoinj.net.ConnectionHandler",
"message": "Error handling SelectionKey: An existing connection was forcibly closed by the remote host",
"level_value": 30000,
"@version": 1

**Comment by gary-rowe** [comment]
Bumped into 0.1.3 since it is similar to the other connection problems Bitcoinj is reporting.

**Comment by jim618** [comment]
Looking at the log more carefully the user synced ok so these stack traces aren't a problem.
