### ISSUE TITLE
Missing SpongyCastle class

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#674]
"message": "Exception in user thread",
"stack_trace": "java.lang.NoClassDefFoundError: org/spongycastle/asn1/BERTags at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_79] at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_79] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_79] at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_79] at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_79] at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_79] at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_79] at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_79] at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_79] at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_79] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_79] at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79] at org.bitcoinj.core.ECKey$ECDSASignature.decodeFromDER(ECKey.java:554) ~[multibit-hd.jar:na] at org.bitcoinj.wallet.DefaultRiskAnalysis.isInputStandard(DefaultRiskAnalysis.java:178) ~[multibit-hd.jar:na] at org.bitcoinj.wallet.DefaultRiskAnalysis.isStandard(DefaultRiskAnalysis.java:147) ~[multibit-hd.jar:na] at org.bitcoinj.wallet.DefaultRiskAnalysis.analyzeIsStandard(DefaultRiskAnalysis.java:198) ~[multibit-hd.jar:na] at org.bitcoinj.wallet.DefaultRiskAnalysis.analyze(DefaultRiskAnalysis.java:78) ~[multibit-hd.jar:na] at org.bitcoinj.core.Wallet.isTransactionRisky(Wallet.java:1663) ~[multibit-hd.jar:na] at org.bitcoinj.core.Wallet.receivePending(Wallet.java:1623) ~[multibit-hd.jar:na] at org.bitcoinj.core.Wallet.receivePending(Wallet.java:1686) ~[multibit-hd.jar:na] at org.multibit.hd.core.network.MultiBitPeerEventListener.onTransaction(MultiBitPeerEventListener.java:144) ~[multibit-hd.jar:na] at org.bitcoinj.core.Peer$4.run(Peer.java:700) ~[multibit-hd.jar:na] at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:107) ~[multibit-hd.jar:na] Caused by: java.lang.ClassNotFoundException: org.spongycastle.asn1.BERTags at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.7.0_79] at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_79] at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_79] at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_79] at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_79] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_79] at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79] ... 23 common frames omitted Caused by: java.util.zip.ZipException: error reading zip file at java.util.zip.ZipFile.read(Native Method) ~[na:1.7.0_79] at java.util.zip.ZipFile.access$1400(ZipFile.java:56) ~[na:1.7.0_79] at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:679) ~[na:1.7.0_79] at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:415) ~[na:1.7.0_79] at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[na:1.7.0_79] at sun.misc.Resource.getBytes(Resource.java:124) ~[na:1.7.0_79] at java.net.URLClassLoader.defineClass(URLClassLoader.java:444) ~[na:1.7.0_79] at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_79] at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_79] ... 29 common frames omitted ",
"level_value": 30000,
"@version": 1
}

**Comment by gary-rowe** [comment]
Looks like an older version of MBHD that may have a glitched Bitcoinj that doesn't pull in the correct SpongyCastle. User should upgrade.

Ready for review and close.

**Comment by jim618** [comment]
Agreed. Closing.
