### ISSUE TITLE
Adjusting fee slider on windows can overload UI

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#680]
On the Windows test machine adjusting the fee slider produced a spinner with 'the UI is not responding'.

I suspect it is firing events too quickly - perhaps a subset down to !isAdjusting is required.

**Comment by jim618** [comment]
This is temporary - the UI catches up ok after a few seconds

**Comment by jim618** [comment]
I've rejigged the code so that less is done in the event servicing code FeeSettingPanelView#setChosenFee which should help.
I don't want to change the slider resolution (which would change the number of events fired) as it is set to 200 satoshi at the moment. This works well.

Awaiting code review and closing.

**Comment by gary-rowe** [comment]
Updated code logged under #690 but verified working.

Closing.

**Comment by jim618** [comment]
Double chcked on Windows 8 test machine, Works fine. Closing.
