### ISSUE TITLE
Update Authenticode certificate

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#682]
Update the Windows Authenticode certificate to avoid expiry at the end of July 2015.

No code changes to the underlying binaries (rebuild from 0.1.2 on master and relabel as 0.1.3) required to ensure ongoing stability.

**Comment by jim618** [comment]
I have retrieved an updated Level 2 code signing cert for 'James Burton' from startssl.com.
I have recreated a p12 keystore file containing the cert, intermediate certs and the private key which can be used for code signing. The expiry date is now 2017-08-17.

The install4j project for multbit-hd-0.1.3 has been updated and pushed.

I have tried the Mac installer out on my Mac and the Win 64 on the Windows 8 test machine.

The installers have been uploaded to the 'multibit-hd-0.0.0' releases area on multibit.org:
https://multibit.org/releases/multibit-hd/multibit-hd-0.0.0/

@gary-rowe If you could try them out.

Also in this installer is the usage of the updates-test.xml so you will get prompted for an update to a non-existent 0.1.4. (Oddly it only seems to check the SECOND time you try out the installed shortcut - we can live with this).

There is a change in the signing methodology in that I am using the same p12 keystore file for BOTH windows and Mac signing. Previously the Mac cert was signing by the Apple root CA, now I am using the StartSSL.com root cert for both. This _appears_ to work fine - it'll simplify things if we can use the same key store so try out both the Windows and Mac installers. 

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified installers on:

* Linux - no problems, saw auto-update for "0.1.4"
* Windows 8 (latest updates) - "safe screen" then "verified publisher" then install then auto-update for "0.1.4" then launch then "firewall blocking - allow private" then successful sync

Looks like the certificates and auto-update are fine.

Closing.
