### ISSUE TITLE
On Windows 8 the light box overlaps the status bar - clearer if there was no overlap

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#684]
On Windows at the default opening size the light box overlaps (by about 30%) the status bar.
It is useful to be able to see the synchronising info when the light box is present so I think it would be worth either increasing the default height slightly.

**Comment by gary-rowe** [comment]
Agreed. Should be a trivial fix that could go into 0.1.3. Can you supply a screen shot for context?

**Comment by jim618** [comment]
Screenshot at default (smallest) size:
![short](https://cloud.githubusercontent.com/assets/919427/9384934/754e4d2a-474b-11e5-9a88-78570d1b330e.png)
(908px x 552px)

And then longer to keep the status bar unoccluded:
![long](https://cloud.githubusercontent.com/assets/919427/9384945/860b80ec-474b-11e5-9dfe-2a1b6431b979.png)
(912px x 603px)

So needs an extra 50px of height

**Comment by jim618** [comment]
Minimum / default size is now set to be 900px x 600px.
Screenshot:
![screen shot 2015-08-20 at 15 01 01](https://cloud.githubusercontent.com/assets/919427/9385118/8768bec2-474c-11e5-9fd0-9a1c9d3f267d.png)

Awaiting review and closing

**Comment by jim618** [comment]
And this is what the minimum size looks like on Windows 8:
![after](https://cloud.githubusercontent.com/assets/919427/9385561/0a4bd02a-474f-11e5-93e8-305125283d4d.png)

**Comment by gary-rowe** [comment]
Looks good to me.

Closing.
