### ISSUE TITLE
[Question] Should an MBHD seed work in Mycelium?

### ISSUE THREAD

**Issue by mendhak** [bitcoin-solutions/multibit-hd#687]
1. Create a new MBHD wallet, save the 12-words seed somewhere
2. Send some money to an address in this wallet
3. Open Mycelium and choose to restore using the above 12 word seed

In my testing, I found that Mycelium doesn't see the address in step 2, so it thinks the wallet balance is 0. 

Is this expected?

I know that [Mycelium -> MBHD works](https://github.com/bitcoin-solutions/multibit-hd/issues/362) just fine.  Should MBHD -> Mycelium work the same way?

**Comment by mendhak** [comment]
Search for ages, find nothing.  Post a question, suddenly the answer appears.

I am sure [this is the reason](https://github.com/mycelium-com/wallet/issues/119), so basically it's Mycelium not looking in the past.  Apparently you can archive and restore an account and it should rescan properly.

**Comment by gary-rowe** [comment]
@jim618 Would you mind chiming in here with the results of your investigation in Mycelium address quirks?

**Comment by jim618** [comment]
The addresses generated between Mycelium and MultiBit HD are the same for the Account 1.
Unfortunately there seem to be some optimisations in Mycelium that mean that they are not fully interoperable. Both Mycelium and MBHD have 'full rescans' where you (most likely) see everything but this is not practical for daily use.

**Comment by mendhak** [comment]
Thanks everyone for the answers and all your hard work on these applications, it's really appreciated.
