### ISSUE TITLE
Peer message crashing app

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#691]
"@timestamp": "2015-07-24T05:56:48.308+02:00",
"level": "WARN",
"thread_name": "PeerGroup Thread",
"logger_name": "org.bitcoinj.net.ConnectionHandler",
"message": "Error writing message to connection, closing connection",
"stack_trace": "java.nio.channels.CancelledKeyException: null at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73) ~[na:1.7.0_80] at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77) ~[na:1.7.0_80] at org.bitcoinj.net.ConnectionHandler.setWriteOps(ConnectionHandler.java:106) ~[multibit-hd.jar:na] at org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:151) ~[multibit-hd.jar:na] at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:88) [multibit-hd.jar:na] at org.bitcoinj.core.Peer.ping(Peer.java:1423) [multibit-hd.jar:na] at org.bitcoinj.core.Peer.ping(Peer.java:1414) [multibit-hd.jar:na] at org.bitcoinj.core.PeerGroup$11.run(PeerGroup.java:1347) [multibit-hd.jar:na] at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:582) [multibit-hd.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80] at java.u

**Comment by gary-rowe** [comment]
This should be fixed by an update to the Bitcoinj library due in 0.1.3.

**Comment by jim618** [comment]
Awaiting #652

**Comment by jim618** [comment]
Bitcoinj updated so marking as 'probably fixed'.
Closing.
