### ISSUE TITLE
Not connecting to network & btc balance disappeared

### ISSUE THREAD

**Issue by katykat1975** [bitcoin-solutions/multibit-hd#698]
I'm new to this but followed  the instructions, uploaded btcs to the wallet & sent some off to another wallet. This was when it stopped sending lost connection & has not connected / shown btc balance since?

 Hope I can get the coins back.

**Comment by Virosa** [comment]
Sound like the same issue as me. I posted yesterday with the error log.

**Comment by gary-rowe** [comment]
So long as you have your wallet words (seed phrase) you'll be able to get your bitcoins back. Not connecting to a network sounds like you have a firewall or other related issue. Can you verify that you've read this article: https://multibit.org/en/help/hd0.1/verify-network.html.

**Comment by gary-rowe** [comment]
This sounds very similar to #697 which contains more information so I'll close this as a duplicate.
