### ISSUE TITLE
Adjust Verify network and Repair wallet screens to cover connectivity

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#699]
Both Verify network and Repair wallet should contain information relating to potential problems with Tor. 

Verify:
Move the "If the peer count.." message above the peer count.
Add "You may find connectivity issues if Tor is enabled (a lock icon is present in the bottom corner). Use Preferences | Labs | Tor to disable it"

Repair:
Align the message vertically to position under the title like other wizards
Add:
"This tool will not:
1. Fix a connection issue (see Help | Verify network)
2. Restore a wallet (see Help | Restore wallet)

**Comment by jim618** [comment]
Agreed with the first one but the second saying what this tool does NOT do is a little odd.

Have you seen people trying to use repair wallet to fix connectivity and restoring a wallet ?

I don't think we want lots of text saying 'this DOES NOT do this' - it's just confusing.

**Comment by gary-rowe** [comment]
Yes, issue #697 provides (nidirect) user feedback indicating that Repair Wallet was used to attempt to fix a connectivtiy issue through the use of CA certificate install. Stating this at the start would help save users time and direct them to a better solution.

**Comment by jim618** [comment]
After conversation Gary and I agreed:
+ We plan to drop Tor support until it is working reliably so 'Verify' text not required.
+ We agreed to not put in the 'negative link' as it is a bit confusing.

Closing as no action required
