### ISSUE TITLE
Update BRIT so that small amounts are not charged on Empty Wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#700]
If a user tries out MBHD but then wants to Empty the wallet, BRIT fees are currently being applied.
These are for quite dusty amounts.

Update BRIT payment so that BRIT fees less than 0.000 05 BTC are not added when an Empty wallet is performed.

**Comment by jim618** [comment]
Updated BitcoinNetworkService so that any BRIT fees less than 0.000 05 BTC are elided.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. I've adjusted the methods to use the existing comparator methods which are more readable. If you're OK with the code review then it's good to close.

Ready for code review.

**Comment by jim618** [comment]
LGTM. Closing.
