### ISSUE TITLE
Gravatar image flashing on then off in send bitcoin screen

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#702]
In the Send screen when you choose a recipient with a gravatar image it flashes the image and then clears it. Only when you move focus to the amount field does the image appear and stay.

**Comment by jim618** [comment]
It only happens when you use the up and down arows to select a recipient, not if you use a mouse

**Comment by gary-rowe** [comment]
Finally got around to this. Was just a missing check against the existing recipient when multiple events occurred in quick succession as is normal in combo boxes. Tested with various combinations of mouse and keyboard operations and it looks good to me.

Ready for review and close.

**Comment by jim618** [comment]
This still isn't quite right.
You can defeat the code to get flicky behaviour as follows:
1) I've got three contacts, one with a gravatar
2) Type in the name of the contact with the gravatar
3) Use the mouse to select the single entry in the list box. Press enter.
4) The gravatar image flicks on and then off.
5) Move focus to the amount field with the tab key. Image then reappears.

This was the only sequence I could get it to fail, otherwise it works fine.

**Comment by gary-rowe** [comment]
I've tried following that exact sequence (with same contact setup and some variations) and I can't replicate it here. Given that it's quite a corner case perhaps we should raise another issue for a later release or just ignore it (I advocate ignoring it).

Awaiting review and close.

**Comment by jim618** [comment]
Yeah - it's obviously pretty minor.
Let's not wory about it.
Closing
