### ISSUE TITLE
Trezor spends don't work for me

### ISSUE THREAD

**Issue by mikehearn** [bitcoin-solutions/multibit-hd#705]
I synced my TREZOR successfully but when trying to send, I see two issues:

1) The first time I tried, the send button was disabled after entering address and amount

2) The second/third time I tried, after pressing send it just sat on the "Communicating with TREZOR" screen and nothing happened.

**Comment by gary-rowe** [comment]
Hi Mike :-)

Just to verify, were you using myTrezor.com at the same time?

**Comment by mikehearn** [comment]
The issue turned out to be that the USB cable died half way through me using the TREZOR.

**Comment by gary-rowe** [comment]
A common lament unfortunately.

**Comment by jim618** [comment]
Yeah the earliest USB cables they sent out seemed to have a very high failure rate.
I think they've fixed it now by using a different supplier.
I threw mine out.
