### ISSUE TITLE
org.bitcoinj.crypto.KeyCrypterException: Could not decrypt: pad block corrupted

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#706]
New error report uploaded. Id: 2ffaac2

MultiBit HD version: 0.1.2
Operating system: 64 6.1 Windows 7

User notes length: 9

Number of stack traces: 9
First stack trace:
org.bitcoinj.crypto.KeyCrypterException: Could not decrypt: pad block corrupted
	at org.multibit.commons.crypto.AESUtils.decrypt(AESUtils.java:127) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.loadWalletFromFile(WalletManager.java:954) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:1068) [multibit-hd.jar:na]
	at

**Comment by gary-rowe** [comment]
This looks like a failed password - did this trigger the error or was it later?

**Comment by jim618** [comment]
Agreed most likely a wrong password but it needs checking if the Error Reporter was triggered (which is incorrect) or not.

**Comment by jim618** [comment]
Just tried various incorrect passwords and:
+ the UI behaved as expected (show message, enable back button)
+ there were no stack traces in the log that would get picked up be the ErrorReporter
+ the ErrorReporter never fired.

As this is a 0.1.2 bug I'll close it as 'could not reproduce'
