### ISSUE TITLE
View and/or Regenerate Wallet Words

### ISSUE THREAD

**Issue by mclstr** [bitcoin-solutions/multibit-hd#711]
Is it possible to regenerate the wallet words for a running instance of Multibit-hd?
Situations like where the paper copy is missing and/or compromised come to mind.

Or should the coins be sent to another wallet and Multibit-hd be reinstalled?

**Comment by jim618** [comment]
It is not possible to regenerate the wallet words no. They are only shown in the wallet creation wizard and  no record of them is kept. This is for security reasons.

IF you have lost your wallet words then the best thing to do is:
1) Create a new wallet (press the create button on the password entry screen)
2) Generate a receiving address in the NEW wallet.
3) Switch to the old wallet and do a 'Manage wallet | Empty wallet' and transfer all your bitcoin to your new wallet.

That way if anything happens to the new wallet you will have your wallet words to recover your bitcoins.

**Comment by mclstr** [comment]
Makes a lot of sense. Yes I was planning on doing just that, but thought I'd check first.
Thanks.

Maybe those details could be added to the help files?

**Comment by jim618** [comment]
Glad you got that sorted.
This issue is probably all the documentation users need ! (it's quite a specific query rather than general help).
C

**Comment by gary-rowe** [comment]
Doubt many users will venture in here - I'll flesh out the restore article to cover this scenario.

**Comment by gary-rowe** [comment]
Added as [website issue #252](https://github.com/bitcoin-solutions/multibit-website/issues/252).
