### ISSUE TITLE
Trim pasted addresses

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#716]
I had a support mail this week which boiled down to leading/trailing spaces on pasting an address into the recipient field. This does not validate as a Bitcoin address.

Suggest automatic trimming of spaces after paste.

**Comment by jim618** [comment]
Updated Addresses.parse so that it trims off any whitespace.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
