### ISSUE TITLE
Change was not spendable

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#721]
I just sent a tx to blocktrail (multisig) and the change was not spendable until the tx confirmed.
The transaction was seen by 5 peers so I would have expected the change to be spendable immediately.
Needs checking (though difficult to track down possibly)

**Comment by jim618** [comment]
I understand this now it is to be expected.
1. Tx sent from MBHD to Blocktail. This is received and unconfirmed.
2. The unconfirmed tx output (in blocktrail) is then spent back to MBHD.

The money is received in MBHD ok but now there is a tx chain that includes the tx that was received to MBHD. This is an unconfirmed parent of the unconfirmed tx being received and (somehow) all that tx's outputs are marked as 'I'm not too sure about this tx's status as it is in an unconfirmed chain. Better mark it as unspendable'.

IT's a bit of an edge case that I don't think people would see particularly in the real world so closing.

**Comment by jim618** [comment]
Note that once the tx chain confirms it all becomes spendable so the user doesn't have to do anything.

**Comment by gary-rowe** [comment]
Is it worth an entry in the "Send Bitcoin" help just in case someone encounters it?
