### ISSUE TITLE
When a new KeepKey wallet is created 'Trezor' is put as the wallet description

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#727]
If you create a new KeepKey wallet 'Trezor' is shown in two places in the Wallet dashboard:

+ in the wallet description
+ in the wallet capabilities "Trezor signed wallet"

It should either say 'KeepKey' or made generic and 'hardware wallet' used.

**Comment by gary-rowe** [comment]
This is due to the lack of a KeepKey wallet type in Core which would normally be selected during wallet creation.

**Comment by jim618** [comment]
As discussed out-of-channel we have kept WalletType so that it does not differentiate between KeepKey and Trezor.

I have changed the wallet capabilities so that it is agnostic to the brand of hardware device - it just says:
```
Transactions signed by device
Private keys are held on device
--the BIP 44 path--

Also when a Trezor/KeepKey hard wallet is created the notes field is left blank rather than 'Trezor'. It's only the note so it doesn't matter that it is blank.

The BIP44 soft wallets had a localised bit of text for 'wallet' so has been left unchanged.

I have also renamed some of the WalletManager methods to use 'TrezorClone' rather than 'Trezor' to indicate that it is brand agnostic.

Note that to test you you will have to create NEW wallets as things are set at construction time

Pushed to keep_key branch only.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Code review looks good - still requires verification by me.

**Comment by gary-rowe** [comment]
Verified working. Closing.
