### ISSUE TITLE
Sign message text isn't quite right for KeepKey

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#728]
When signing a message MBHD shows:

"Message text"

Sign message ?

But on the KeepKey device it says:

SIGN MESSAGE
"Message text"

**Comment by gary-rowe** [comment]
Updated the text to switch between KeepKey and Trezor and also to handle LF characters that may cause overrun.

<img width="1012" alt="screen shot 2015-09-24 at 21 05 05" src="https://cloud.githubusercontent.com/assets/342133/10085352/9ea21096-6300-11e5-9989-157906edd645.png">

Ready for review and close.

**Comment by jim618** [comment]
Signed messages (with lots of CR in ) on both Trezor and KeepKey successfully.
Closing
