### ISSUE TITLE
Restore type needs to mention both Trezor + KeepKey

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#732]
When restoring from a set of wallet words the drop down list localisation had {0} as a placeholder.
In this use case there is no hardware wallet plugged in so it need to state explicitly 'Trezor/KeepKey'.

I've changed the text to:
Trezor/KeepKey device, Mycelium (BIP 44)

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
