### ISSUE TITLE
Restore menu is remembering KeepKey even when KeepKey removed

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#733]
I just did the following:

+ start up MBHD, see password entry screen
+ plug in KeepKey. The screen transitions to PIN entry screen
+ start up wallet as normal.
+ remove keepKey
+ do switch wallet
+ password entry screen is shown correctly BUT if you press the 'Restore' button the Restore screen has the first option:
   "I want to create a new KeepKey wallet"
As there is no KeepKey plugged in it should be "I want to create a MultiBit HD wallet".

**Comment by gary-rowe** [comment]
I've improved the attach/detach handling code so swapping between devices should be seamless in the primary wizards (Welcome and Credentials).

Ready for review and close.

**Comment by jim618** [comment]
I just repeated the sequence of events in the OP and still see 'KeepKey' in the list of options (see screen shot) even though the KeepKey has been detached.
![screen shot 2015-10-10 at 13 30 20](https://cloud.githubusercontent.com/assets/919427/10411115/4a2ea36c-6f53-11e5-98dd-edc457b4adab.png)

**Comment by gary-rowe** [comment]
It might be worth re-testing this in light of recent changes made under #745 and #746.

**Comment by jim618** [comment]
KeepKey : retested OP steps - works fine.
Trezor : retested OP steps - works fine.

Closing
