### ISSUE TITLE
Add smartbit to list of block explorers

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#734]
smartbit has a nice feature showing tx propagation through their nodes.
Also shows fee rate (though they call it fee size) in sat/B

https://www.smartbit.com.au/tx/131c6939154525de7e9854b8e147522be9511af88d2e419140ea1f9117d8f54e

**Comment by gary-rowe** [comment]
Agreed - looks useful.

**Comment by jim618** [comment]
Added smartbit to list of blockexplorers.
Also bumped blockr.io  URL from http to https.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
