### ISSUE TITLE
FEST tests not running smoothly

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#736]
Just ran the FEST tests in develop.
17 of the tests failed and I managed to crash the JVM.
I'll add a screenshot with the results a little later (cannot upload them in Starbucks for some reason)

**Comment by jim618** [comment]
![fest tests](https://cloud.githubusercontent.com/assets/919427/10252316/9a07ea2c-692e-11e5-9ecb-2bab7804f684.png)

**Comment by gary-rowe** [comment]
Yes, there's still lots to do with the wallet mode refactoring.

**Comment by jim618** [comment]
After discussion offline I'll look at this.

**Comment by jim618** [comment]
FEST test update:

StandardFestTest - these all run successfully but I sometimes see JRE failures (as per raised issue).
TrezorFestTest - 2 passed 10 failed. I saw a MBHD crash report whilst these were running.
KeepKeyFestTest - there's still quite a lot to do on these I think - still some references to Trezor classes in them.

**Comment by jim618** [comment]
TrezorFestTest, running tests individually in the IDE:
verifyCreateHardwareWallet_ColdStart : PASS
verifyCreateHardwareWallet_WarmStart : PASS
verifyUnlockHardwareWallet_WarmStart : PASS
verifyUnlockHardwareWallet_ColdStart : PASS
verifyReattachHardwareWallet : PASS
verifyRestoreWithLocalBackup : PASS
verifySendScreen : PASS

I'll stop there - as the tests are running ok individually it looks like something to do with either the test framework or the soft reset.

**Comment by jim618** [comment]
Remaining TrezorFestTests (each test run individually in IDE):
verifySendRequestScreen : PASS
verifyUnsupportedFirmware : FAIL
verifyPaymentsScreen : PASS
verifyUnsupportedConfiguration_Passphrase : FAIL

**Comment by jim618** [comment]
just did an update an reran the TrezorFestTests all together. I still get 2 passes, 10 failures.

**Comment by jim618** [comment]
Just reran the TrezorFestTests all together. I still get 2 passes, 10 failures.

There seems to be a mixup with the accessibility names of the labels and textareas. For instance, 'verifySendRequestScreen' is failing because there are two components labelled 'notes' on the PaymentRequestScreen and the FEST test is looking for one called 'notes.value'.

AccessibilityDecorator.apply just adds 'notes' so I am not sure where the '.value' should be added.

@gary-rowe Could you have a look at this please ?

**Comment by jim618** [comment]
Just reran the FEST tests:
Standard: 1 failure: verifyCreateWallet_ro_RO_ColdStart
Trezor: All tests pass.
KeepKey, 5 tests pass, 4 fail (verifyRestoreWithLocalBackup, verifyCreateHardwareWallet_ColdStart, verifyUnlockHardwareWallet_ColdStart, verifyCreateHardwareWallet_WarmStart)

**Comment by gary-rowe** [comment]
OK, I think I'm about done with the FEST tests for this release. I've got all but one working now (create Trezor from cold start) which is caused by a dangling reference to `MainController` being maintained through a `SOFT` reset. This won't occur in the real world and the test works fine in isolation.

Ready for review and close.

**Comment by jim618** [comment]
I have rerun all the tests and and all run except for verifyCreateWallet_ro_RO_ColdStart
I didn' get this to run in isolation.

I think this will do for this release - we have full coverage of the Trezor and KeepKey running fine.

Closing.
