### ISSUE TITLE
Comparison with MultiBit classic, esp. the sending fee

### ISSUE THREAD

**Issue by dandv** [bitcoin-solutions/multibit-hd#737]
Is there a (wiki) page where MultiBit classic is compared to HD?

In particular, the HD version says

> We will charge you 1,000 satoshi (about $0.005) each time you send bitcoin using the Software.

Is this charge going towards the development of MultiBit (which would be great), or is it [the Bitcoin sending fee](https://en.bitcoin.it/wiki/Transaction_fees#Sending) made mandatory to speed up transactions (in which case, a better phrasing than "We will charge you" might be "You will be charged")?

**Comment by gary-rowe** [comment]
You can find a lot of information about this on the website. Here are some articles to get you started:

* https://multibit.org/en/help/hd0.1/how-brit-works.html
* https://multibit.org/try-multibit-hd.html
* https://multibit.org/en/help/hd0.1/how-to-upgrade-from-classic.html

The fee is to support ongoing development of MultiBit (both HD and Classic) and also upstream projects that we depend on.

**Comment by jim618** [comment]
I think Gary's reply covers this issue so closing.
