### ISSUE TITLE
missing bitcoin transfer from MultiBitHD to Trezor

### ISSUE THREAD

**Issue by smiles57** [bitcoin-solutions/multibit-hd#738]
Hi 
I bought 1 Bitcoin and had it sent to my multibit-hd wallet. I saw it received in the wallet. I plugged in the Trezor device into the laptop and expected to see the 1 BTC transferred to the online wallet at www.mytrezor.com. The BTC is not showing in the MultiBit wallet now nor has it credited to the mytrezor.com online wallet. Any clues?

Thanks

**Comment by gary-rowe** [comment]
Can I just verify the steps that you've taken:

1. You attached a Trezor device in MultiBit HD and unlocked its wallet
2. You clicked Request bitcoin and generated a receiving address (using Account 1 on Trezor)
3. You sent 1 BTC to this address and saw it arrive and confirm in MultiBit HD
4. You closed MultiBit HD and switched to mytrezor.com
5. The mytrezor.com website detected your Trezor and showed you your balance
6. The 1 BTC credit was not present

Is this correct?

**Comment by smiles57** [comment]
Hi gary-rowe
Thanks for coming back to me on this. As I remember I:
1. opened the MultiBit HD wallet. 
2. Cut and pasted the wallet address from MultiBit HD into the wallet I was sending the money from, (an exchange)
3.Sent 1 BTC to the address generated by the MultiBit HD wallet.
4. Saw and heard it arrive twice in the MultiBit HD wallet.
5. Inserted the USB cable for Trezor into the computer and logged onto mytrezor.com
6. Accepted viewing Trezor balance -expected that there would be an automatic synchronisation between MultiBit HD and Trezor.
7. Saw my balance on Trezor which did not show the 1 BTC
8. Rechecked the MultiBit HD wallet and saw a zero balance.

Regards

Smiles57

**Comment by smiles57** [comment]
Hi gary-rowe
Just logged onto MultiBitHD and it is now showing 1 BTC balance. Strange.

**Comment by gary-rowe** [comment]
It may be that you're confusing MultiBit HD running with a Trezor attached ("hard" wallet mode) with it running without ("soft" wallet mode). Each mode results in a completely different wallet being generated. I think you have generated an address using a "soft" wallet and then plugged in your Trezor and expected it to be copied across. 

The correct procedure for keeping your mytrezor.com and local MultiBit HD in sync is what I detailed above in my earlier email. 

To recover from what I think you have right now, you need to do the following:

1. Start MultiBit HD without a Trezor attached
2. Unlock your "soft" wallet and observe the 1 BTC balance
3. Use Exit/Switch to return to the Unlock screen
4. Attach your Trezor and unlock the "hard" wallet (you'll see a small shield icon in the bottom left)
5. Create a fresh receiving address using Request Bitcoin
6. Copy the address to the clipboard and note the start and end characters (e.g. 1abc... ...4ghi)
7. Use Exit/Switch to return to the Unlock screen
8. Detach your Trezor
9. Unlock your "soft" wallet and observe the 1 BTC balance
10. Send 1 BTC to the receiving address in your clipboard (verify the start/end characters to be sure) - you can use Empty Wallet if you prefer
11. Wait for successful broadcast
12. Use Exit/Switch to return to the Unlock screen
13. Attach your Trezor
14. Unlock your "hard" wallet and observe the 1 BTC being confirmed

Let me know how you get on.

**Comment by smiles57** [comment]
Hi Gary

Thanks for your help. 

This seems to have resolved it.

Best regards

Steve


Steve Shellabear

office: +44 (0)1908 644791
mobile: +44 (0) 7710 407945

**Comment by smiles57** [comment]
I have to say though it was not the easiest of processes. I am glad you picked this up and were able to give me directions.I am going to forward this thread to Trezor as it would be helpful to have this insight as part of their standard operating instructions.

**Comment by gary-rowe** [comment]
Would be useful if others are encountering the same problem. Overall, MultiBit HD is a separate desktop wallet that also supports Trezor (and soon KeepKey) but does require a bit a of learning curve if you're coming at it from just a Trezor perspective.

Anyway, I'm glad it's resolved now so I'll close this issue.

**Comment by smiles57** [comment]
Hi bitcoin-solutions/multibit-hd,

dancing lion - contact centre training invited you to join more than 1.000.0000 registered businesses in Lynkos, the first B2B online network designed to help your business achieve its full potential.

Get new customers, suppliers, business partners and opportunities while taking advantage of the of the network’s productivity tools.

Join now following the link below:

http://link.lynkos.biz/wf/click?upn=How3MXqFQy4VbScjIOnIr7xHWZqw4a2AP7m2Xgsvq8y3AeoA5Lm18NVVEZL5da-2BC6r6hYQjBuHrCBvWxDuqVE30X52f44cN318pBvUz2l49AFyJ0p-2Fw3IG4dxxnms0KcD7S6185g9wiQeGDBK4z0-2BXiVloC7mztfvlurCwL42JDThEGZvlFmsBtNBvJtuxqFWJZ5peoXQtvk7C-2FlwRrZdgELX2mOhrjpn21O-2Bp56OfmYBDUcmTmwVwTlbBf-2BqykZmllgRgwJpIGA8n8Ugti7Y8P21gPCrmeaopHL-2Bi07sx3Iqj7NMTLCWostWRlj6a3YPKetSWqZkxIq5UOjZdXP84tELaaqRuluNXjsjp-2FDmOM5KdBxcLGQVRtiPA-2BZ-2BIgU-2F8nhsI4a5tCmrbFpNmpOrA-3D-3D_s5UH8bhnBaopYjthcNSRcfYMQzupOAEgwnaaptWCl6o62-2FvMhYcZ4PQW2WgcA3no-2BqaMlvtsRy3YhOOlYeoo7rWnnLyxiz9sDZtbRf3GVG1WMEtSKcIFma5R-2B7m2Nbh-2FsXJn7Ab4rtcTLEiT7IjQcv-2BwBuvYsB7NDdlnHFIkZwYVelxCPo8eqkB-2FgDakcDdg1sg32-2BGuiIjz0nzR-2F7zTmmxV-2B0xMg0IIIMaU4NY-2FO9HyxOclf5JMQeBMcxCpGcVpVeLY-2BBAvOQdzuCa3LT7jBKAjdNJ-2FvLTugyRG-2Fu-2BXDyyR1ZDJjZBLyJewDLL4R8TOr2p2BMMqMp9GmzuCocCtKRMrVfPKg-2FnVMEaFvbKiyUmDKur7b0qHfk3YjBQr-2FdW59QOFZwIZNHaQEUNhETCAm60bOKSh1PrIVj4YvrgV5AY-3D
