### ISSUE TITLE
Payment request needs some text wrapping

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#741]
You can donate to Eclipse.org using a Bitpay Payment Request but some of the screens need tidying up.
See screen shots:

Initial request: OK
![screen shot 2015-10-08 at 15 11 04](https://cloud.githubusercontent.com/assets/919427/10368859/4322e96e-6dcf-11e5-87fb-f61670ac9cfe.png)

Payment request details: notes field too long
![screen shot 2015-10-08 at 15 11 17](https://cloud.githubusercontent.com/assets/919427/10368903/6330421a-6dcf-11e5-8baa-05ad9268554f.png)

Confirm send : ok
![screen shot 2015-10-08 at 15 11 35](https://cloud.githubusercontent.com/assets/919427/10368917/756cf07c-6dcf-11e5-955d-e91ef6b1424d.png)

Transaction drill down : notes field too long
![screen shot 2015-10-08 at 15 12 53](https://cloud.githubusercontent.com/assets/919427/10368934/84014822-6dcf-11e5-8dd9-38e327175d5f.png)

**Comment by jim618** [comment]
URL to use: https://eclipse.org/donate/

**Comment by jim618** [comment]
I have made the notes field into a JTextArea.

Awaiting review and closing

**Comment by jim618** [comment]
![screen shot 2015-10-13 at 16 50 09](https://cloud.githubusercontent.com/assets/919427/10464985/769d414a-71e4-11e5-848b-6f2c8534d20c.png)

**Comment by jim618** [comment]
Added a scroll pane for long Notes - it will look like this:
![screen shot 2015-10-15 at 12 49 02](https://cloud.githubusercontent.com/assets/919427/10512853/40f91818-733b-11e5-90ab-bb42977d689c.png)

**Comment by gary-rowe** [comment]
Verified working.

Closing.
