### ISSUE TITLE
Payment request - fiat amount is shown as negative

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#742]
With the eclipse.org/donate payment request, if you make a payment and then drill down to the transaction the FIAT amount is negative.
Screenshot:
![screen shot 2015-10-08 at 15 39 09](https://cloud.githubusercontent.com/assets/919427/10369568/e0447f3e-6dd2-11e5-959e-05e5d898227f.png)

It should be positive, like the bitcoin amount

**Comment by jim618** [comment]
Updated BIP70PaymentRequestDetailPanelView so that it shows the abs() value of the fiat amount.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
