### ISSUE TITLE
When no Trezor/ KeepKey plugged in see "MultiBit" instead of Trezor

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#743]
And if you click on it you get options to:
Buy a MultiBit
Verify a MultiBit
Wipe MultiBit

Looks a bit confused.

Screenshot:

![screen shot 2015-10-08 at 16 23 18](https://cloud.githubusercontent.com/assets/919427/10370969/1e8aa7cc-6dd9-11e5-883d-d44b2d62f40c.png)

**Comment by gary-rowe** [comment]
I've added support for historical branding to ensure that ongoing user experience remains consistent (e.g. Trezor was previously the default branding for the hardware wallet button). This changes if a different device (such as a KeepKey) is driving the current wallet session but it is not dynamic.

Ready for review and close.

**Comment by jim618** [comment]
When MBHD is first started you see the Trezor branding ok.
Closing
