### ISSUE TITLE
Switching between Trezor and KeepKey needs work

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#745]
Part of the "rainy day" support. When a user is in a hardware wallet session the following switching use cases are expected (KeepKey and Trezor are interchangeable in each use case):

**Attached KeepKey allows switch to Trezor**
1. User has an unlocked KeepKey session underway with an attached KeepKey
2. User detaches KeepKey and attaches Trezor
3. Expect to see a switch alert with Yes button
4. User clicks Yes and is taken to Credentials wizard in Trezor mode (KeepKey events are ignored)

**Unlocked KeepKey session with detached KeepKey**
1. User has an unlocked KeepKey session underway but has detached their KeepKey
2. User re-attaches earlier KeepKey - no alert shown
3. User attaches a different KeepKey - expect a switch alert

**Comment by gary-rowe** [comment]
See #746 for additional behaviour use cases.

Ready for review and close.

**Comment by jim618** [comment]
Test: Plug in uninitialised KeepKey. Create wallet. Detach. Attach Trezor. See alert. Click yes. Enter PIN. Unlock. Sync. PASS
Test: Plug in KeepKey. Enter PIN. Unlock. Sync. Detach. Attach Trezor. See alert. Click yes. Enter PIN. Unlock. Sync. PASS
Test: Plug in Trezor. Enter PIN. Unlock. Sync. Detach. Attach KeepKey. See alert. Click yes. Enter PIN. Unlock. Sync. PASS.

Test: KeepKey wallet active. Unplug. Plug in same KeepKey. No alert. PASS.
Test: KeepKey wallet active. Unplug. Plug in different KeepKey. See alert. Click yes. Enter PIN. Unlock. Sync. PASS

Test: Trezor wallet active. Unplug. Plug in same Trezor. No alert. PASS
Test: Trezor wallet active. Unplug. Plug in different Trezor. See alert. Click yes. Enter PIN. Unlock. Wallet syncs fine. PASS.

Closing
