### ISSUE TITLE
Plugging in KeepKey causes Error report screen

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#746]
I did the following and got an Error report screen:

1) Start up MBHD with soft wallet
2) Plug in KeepKey
3) See 'You have a KeepKey xyz plugged in. Do you want to use it?' Click yes
4) Get 'Requesting MultiBit HD unlock screen' and then an Error Report screen
![screen shot 2015-10-10 at 13 33 55](https://cloud.githubusercontent.com/assets/919427/10411142/38ca20f0-6f54-11e5-9682-bb4128c98fa4.png)

Error is at CredentialsRequestMasterPublicKeyPanelView#afterShow() Optional.get() cannot be called on an absent value

**Comment by gary-rowe** [comment]
Just checked and it appears that this is fixed by #745.

Ready for review and close.

**Comment by jim618** [comment]
KeepKey: plugging in whilst on soft wallet password screen works fine
Trezor: plugging in whilst on soft wallet password screen works fine.

Closing
