### ISSUE TITLE
Bump minimum tx relay to 5000 sat / KB

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#749]
In light of this post:
https://www.reddit.com/r/Bitcoin/comments/3oecqm/psa_to_address_mempool_flooding_bitcoin_core/

We should bump the min amount possible in the tx fee slider to 5000 sat / KB)
The code has been written so that any amount lower than that (currently minimum is 1000 sat / KB) will get lifted.

**Comment by jim618** [comment]
The minimum tx fee slider value is now 5000 sat/ KB.
Also this rate is used as the minimum in any send.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. 

I've released a new version of BRIT Core (0.4.0) since it's unlikely there is anything else that will need to change there.

Closing.
