### ISSUE TITLE
Deleted payment request, can I get the coins?

### ISSUE THREAD

**Issue by dhjw** [bitcoin-solutions/multibit-hd#752]
Hi, I created a payment request which generated an address, then I gave out the address and deleted the request. Is there any way to get coins that were sent to the address? Can I manually re-add the address and does Multibit HD know the key? Or can I hack the key since I hear it's <a href="https://www.reddit.com/r/Bitcoin/comments/3ctnfg/help_with_multibit_hd_how_to_export_the_private/">predictable</a>? Thanks

**Comment by jim618** [comment]
If you delete the payment request from the user interface, the address is still in the wallet. Any funds sent to that address will appear in the wallet as normal.

If you don't see them, try a Tools | Repair wallet to resync with the blockchain.

**Comment by dhjw** [comment]
Thanks for clarification. :-D
