### ISSUE TITLE
Verify Trezor text not right when no Trezor plugged in

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#757]
When you do NOT have a trezor plugged in and try the 'Verify Trezor' option the text refers to MultiBit HD which is confusing.

Screenshot:

![screen shot 2015-10-17 at 14 11 00](https://cloud.githubusercontent.com/assets/919427/10558887/143eae06-74d9-11e5-8204-c211d5b73536.png)

**Comment by jim618** [comment]
Sorry - this was Verify Trezor, not Wipe Trezor

**Comment by gary-rowe** [comment]
Covered by #758 which disables the verify if the current session wallet is not hardware.

Close if you're OK with this.

**Comment by jim618** [comment]
Closing as #758 has been closed.
