### ISSUE TITLE
'Donate now' Next button not enabled

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#759]
When user does a 'Donate now' in the Preferences | Fees screen the Send confirm screen is shown all filled out. However the 'Next field is not enabled until the user 'touches' on of the other fields with a focus traversal. The Next should be enabled initially.

Noticed on Windows test machine but probably applies to all OSes

**Comment by gary-rowe** [comment]
Just a missing wizard button event after showing.

Ready for review and close.

**Comment by jim618** [comment]
Confirmed the Next> button is enabled on dialog first opening.
