### ISSUE TITLE
When swopping between Trezor and KeepKey the 'hardware' display does not resize

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#766]
When swopping between a KeepKey and Trezor the width of the display panel for what is being shown on the hardware wallet does not resize.

The KeepKey display is wider than the Trezor but if you use a Trezor first and then swop to a KeepKey the width of the 'hardware' display does not change.

It will be a rare instance someone has both a Trezor and KeepKey so this is a minor nit.

**Comment by gary-rowe** [comment]
Not sure I can replicate this. Here are my steps:

1. Warm start MultiBit HD without any device attached
2. Attach Trezor and perform PIN unlock 
3. Observe "encrypt key" screen in Trezor-width
4. Detach Trezor and observe switch to password screen
5. Attach KeepKey and perform PIN unlock
6. Observe "encrypt key" screen in KeepKey-width

This appears to be correct behaviour.

If a Trezor/KeepKey switch takes place during an open wallet session then we're entering an unknown state where the device is suddenly different to the one opening the wallet and we'll be seeing lots of unusual behaviour. We don't trigger a shut down to allow the user the opportunity to work with the wallet with their device locked in a drawer or something.

Can you provide the sequence you went through to get the incorrect behaviour, or shall we close this one off as "won't fix"?

**Comment by jim618** [comment]
Yeah - I switched it 'on the fly'.
This is going to be a very edge case (how many users have both a Trezor and KeepKey?)

Let's "won't fix" this one.

Closing.
