### ISSUE TITLE
Check dust limit is appropriate for 0.0005 min tx relay fee when bitcoinj bumped

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#767]
The dust limit for unspent outputs is a function of the min tx relay fee.
There is a discussion of it in this bitcointalk thread:
https://bitcointalk.org/index.php?topic=1214993.0;all

It may be necessary to update this value (or double check it when we update to latest bitcoinj)

**Comment by jim618** [comment]
The current value (set in Transaction) is:
```
    public static final Coin MIN_NONDUST_OUTPUT = Coin.valueOf(546);
```
According to the logic in the thread the current dust value is 2730 satoshi. This is x5 to reflect the change from min tx relay of 0.000 01 to 0.000 05 BTC

We will need to bump our version of our bitcoinj fork

**Comment by jim618** [comment]
I have increased the minimum dust level to 2730 satoshi and the min tx relay fee to 5000 satoshi.

There is a new version of bitcoinj: bitcoinj-0.13.3-alice-0.2.0-SNAPSHOT with this in and deployed to our staging repo.
MBHD develop points to this in the toplevel pom (but each of the intermediate libs (multibit-hardware etc) need to be updated to point to it when they have their versions incremented when released from develop).

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by jim618** [comment]
For validation purposes:
Here is the same change made by Andreas Schildbach in the upcoming bitcoinj 0.13.4:
https://github.com/schildbach/bitcoinj/commit/8a7aa1ef0dbf05b19187567501406420d50c0db1

**Comment by gary-rowe** [comment]
Verified working. Closing.
