### ISSUE TITLE
Notes is getting lost for Trezor wallet on shutdown/ startup 

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#772]
If you plug in a Trezor and set a note for the wallet (in Manage wallet | Edit wallet) , then Exit and restart with the Trezor still plugged in the note has disappeared.

I checked that it was present in the wallet yaml at shutdown.

**Comment by jim618** [comment]
This bug was present in at least v0.1.4

**Comment by jim618** [comment]
This also affects a KeepKey wallet

**Comment by jim618** [comment]
The comment is correctly stored when you close down MBHD
When you open it up the note is present in the YAML file up until the user presses the 'unlock' screen.
Then the notes field disappears.

**Comment by jim618** [comment]
Fixed. Tested with KeepKey and Trezor.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
