### ISSUE TITLE
(German) On Trezor wallet creation completion screen, text is not fully shown and "finish" button is nearly invisible

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#773]
MultiBitHD 0.1.4 Linux
After setting up a new Trezor wallet, the last screen (Trezor report) says "Click Finish for PIN entry..."
One cannot see the complete tex of the German translation. Also, the "Finish" button is nearly invisible, because it does not fit into the screen. See screenshot (date/timestamp has been blacked by me).
![multibithd](https://cloud.githubusercontent.com/assets/8447873/10829044/249e08fc-7e78-11e5-8f00-02766beedc12.jpg)

**Comment by jim618** [comment]
Yes the top line needs putting in a scrolling component rather than 'everything on one line'.

**Comment by jim618** [comment]
Easiest way to fix this was to shorten the text slightly.

Screenshot:
![screen shot 2016-01-12 at 15 00 45](https://cloud.githubusercontent.com/assets/919427/12267026/103a93b6-b93e-11e5-9a4f-949384af592b.png)

Awaiting review by @gary-rowe and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
