### ISSUE TITLE
Update to bitcoinj 0.13.3

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#775]
Update an alice branch to use the canonical bitcoinj 0.13.3

**Comment by jim618** [comment]
There is now a release-0.13.3-alice-0.1.5 update to our bitcoinj fork available.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Just checked the staging repo and there are no checksums for the released artifact. Can you rebuild and redeploy with `mvn -DcreateChecksum=true clean install`. Given that it's only us using this repo I'll ensure I clean out my local release so you can upload a fresh copy with its checksums.

**Comment by gary-rowe** [comment]
Actually, scratch that. I've just rebuilt it locally and pushed it with checksums. That'll save you some bandwidth tomorrow. It seems to be working OK with my local build so I'll close this.
