### ISSUE TITLE
sent bitcoins to wrong address 

### ISSUE THREAD

**Issue by simions** [bitcoin-solutions/multibit-hd#778]
Hi hope you can help me guys. I bought some bitcoins recently a and as an address i've put address from request which i deleted earlier. I looked on blockchain and bitcoins are transferred to that address but they do not show up in my wallet. is there any way for me to get them in my wallet.

**Comment by jim618** [comment]
Bitcon transactions are irreversible so once they have been sent and they are confirmed you cannot undo them.

If you know who you sent it to then the best thing to do is contact them (by email or whatever) and simply explain that you sent them by mistake and ask for them back. 
Everyone using bitcoin has done this at least once so most people do the right thing and send them back.

Good luck
