### ISSUE TITLE
On wallet opening all transactions are sending/ receiving

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#779]
Opening a wallet using the '0.1.5' code I saw every transaction as sending and receiving and had to do a repair wallet.

This is most likely something to do with the mempool as that is where the transaction confidences are stored.

**Comment by jim618** [comment]
This turned out to be a new option in Context called 'EventHorizon'.
Transaction confidences over a certain depth have some details elided and this caused the tx to be seen as Sending/ receiving.

There is a Context constructor where you can set the event horizon. I've set it to Integer.MAX to effectively switch off this behaviour.

Awaiting review and closing
(Try doing a repair on a wallet with tx older than a couple of months).

**Comment by gary-rowe** [comment]
Verified working. Closing.
