### ISSUE TITLE
'Someone is watching' alert mentions History (which has disappeared)

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#782]
When MBHD is in debug mode the user gets a security warning.
The text of the warning mentions 'See history' but there is no history anymore.

**Comment by jim618** [comment]
I just retested this and there is no mention of History. Also no mention in the language files.
Nothing to do.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Well... doing a search for "history" across the codebase does reveal quite a few dead code entries that reference it. We could do a sweep through in the interests of code hygiene. Your call though - close if you don't want to.

**Comment by gary-rowe** [comment]
Marking as bounced back purely to encourage a code review of my changes.

Ready for review and close.

**Comment by jim618** [comment]
LGTM.
Closing
