### ISSUE TITLE
Dark theme error report dialog suffers from low contrast

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#789]
User feedback indicates that the colour contrast on the error reporting dialog in the Dark theme makes it very hard to read. Example screen shot:

<img width="578" alt="screen shot 2015-11-14 at 20 13 36" src="https://cloud.githubusercontent.com/assets/342133/11165625/4c216a5e-8b0c-11e5-8a29-8b155a3bfdd9.png">

**Comment by gary-rowe** [comment]
Turned out to be a missing `setOpaque(true)` for this use case. Here is the updated code in the main themes:

<img width="578" alt="screen shot 2015-11-14 at 20 23 35" src="https://cloud.githubusercontent.com/assets/342133/11165671/a4598c14-8b0d-11e5-8730-ce46b17b7cee.png">
<img width="578" alt="screen shot 2015-11-14 at 20 34 38" src="https://cloud.githubusercontent.com/assets/342133/11165713/2702fd2a-8b0f-11e5-82cd-b89ff8168d1a.png">

This also uncovered an issue with the shut down code where an NPE could cause a failure to stop.

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by jim618** [comment]
Verified CrashReporter in both light and dark theme - contrast is fine.

Closing.
