### ISSUE TITLE
BIP70 Payment protocol support

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#81]
[Payment protocol](https://bitcoinj.github.io/payment-protocol) support is essential and is part of the MVP. 

#### Receive payment request use case

User receives a (possibly delayed) "pink alert" after unlocking a wallet when any of the following happen:

* Command line passing of BIP21 and BIP72 URIs resulting in a pink alert after user unlocks a wallet
* Drag and drop of `*.bitcoinpaymentrequest` file onto app (any location within frame when lightbox is not showing)
* At runtime this should occur as part of a multiple-instance handover operation from a response to clicking a `bitcoin:` link or opening `*.bitcoinpaymentrequest` file (OS file registration)

Ongoing interaction by the user requires:

* Alert text should indicate confidence level of payment request (Trusted/Untrusted) and have button
* Clicking button activates the "send bitcoin" wizard with a summary of the payment request
* User clicks Next to accept/trust the payment request and arrives at the confirmation screen
* User clicks Send to finalise the payment in the normal manner

#### Create payment request use case
Requires further thought about implementation

**Comment by gary-rowe** [comment]
Ready for an interim review.

**Comment by gary-rowe** [comment]
Merged bip70 into develop based on latest bitcoinj-alice and multibit-hardware.
To verify try starting with the following command line arguments:
* `bitcoin:1AhN6rPdrMuKBGFDKR1k9A8SCLYaNgXhty?amount=0.01&label=Please%20donate%20to%20multibit.org&message=Thank%20you%20for%20your%20kind%20donation.%20%0DWe%20appreciate%20it!`
* `file:///path/to/the/project/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/localhost-signed.bitcoinpaymentrequest`
* `bitcoin:1AhN6rPdrMuKBGFDKR1k9A8SCLYaNgXhty?r=http://dblsha.com/payreq/NjhiYz&amp;amount=0.01`
* `bitcoin:?r=https%3A%2F%2Fbitcoinauthenticator.org%3A8335%2Fmultibit`

**Comment by jim618** [comment]
All 4 examples work correctly, except for the following two points:

In the third example there is no fiat equivalent shown, even though you can see the exchange is set ok in the background. I would expect it to be the rate at receipt, or close in time to that.
Screenshot:
![screen shot 2015-03-06 at 14 03 50](https://cloud.githubusercontent.com/assets/919427/6526438/d4217f0e-c409-11e4-9c4e-90e417bcb08e.png)

In example 3 the details on the alert is too long (even in English) when the screen is set to minimum. It's pushing the buttons off the screen. Screenshot
![screen shot 2015-03-06 at 14 08 07](https://cloud.githubusercontent.com/assets/919427/6526498/69d8016c-c40a-11e4-85f9-55dfadc18c49.png)

Overall it's working as sunny day code so relabeled as 'In progress'.

**Comment by gary-rowe** [comment]
A note of caution with showing local amounts: it opens problems with mismatched exchange rates. The user will either feel undercharged or overcharged depending on arbitrage between exchanges. 

That said, we don't allow them to enter a value and it is the bitcoin amount driving the process so it comes down to a UI issue. I'll add in the code to activate and handle it throughout.

The alert bar is a bit of a mess, I agree. It currently wraps two sets of localised message which needs correcting.

**Comment by jim618** [comment]
I recommend we add it in, even if we don't show it 'high in the mix'.
Otherwise the user will get in a situation where they have, say, 1000 transactions in a wallet, 990 have fiat equivalents that they can use as a tax basis and, say, 10 that don't (payment requests) and they have to work out manually. This would be a PITA.

You soon get used to there being varying rates in bitcoin land - we don't have it show it front and center but should record it.

**Comment by gary-rowe** [comment]
Given that this is quite a large issue Jim and I have decided to split it into smaller separate issues that are better targeted. These will be labelled as bip70.
