### ISSUE TITLE
Add Blockonomics to the list of block explorers

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#819]
Website is user friendly and HTTPS: https://www.blockonomics.co

API for exploring a TxID is straightforward: 

https://www.blockonomics.co/api/tx?txid=35380f12b38c7b47c47b66bdbf4a1ff2ec5f3fc48dc78c86fa24aae2617289ee

**Comment by gary-rowe** [comment]
Had a bit of spare time so I just went ahead and did it.

Ready for review and close.

**Comment by jim618** [comment]
Nice clean block explorer.
Works fine.

Closing.
