### ISSUE TITLE
Number of payments shown as 0 first time 'Wallet dashboard' is shown. Then correct

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#827]
If you start or switch to a wallet and immediately go to the wallet dashboard, the number of payments is zero even if there are payments in the wallet.

If you open it again the number if correct.

Looks like an initialisation problem or perhaps the wallet dashboard is not refreshing the wallet manager transaction adaption.

**Comment by jim618** [comment]
Improved initialisation of WalletService so that a call to getPaymentDataSetSize always has data.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
