### ISSUE TITLE
Add Buy/Sell wizard with support for Glidera

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#828]
Add in support for Buy/Sell bitcoin as per the use case in SpiderOak.

**Comment by gary-rowe** [comment]
First draft of sidebar UI. See SpiderOak use cases for rationale.

<img width="1012" alt="screen shot 2015-12-12 at 17 09 44" src="https://cloud.githubusercontent.com/assets/342133/11763063/cd21bde6-a0f3-11e5-8129-c4b8d79d9bb1.png">

**Comment by gary-rowe** [comment]
First draft of the buy/sell wizard (see `glidera` branch for implementation):

<img width="1012" alt="screen shot 2015-12-12 at 21 06 48" src="https://cloud.githubusercontent.com/assets/342133/11763881/5989c916-a114-11e5-8d08-14021a69a23d.png">

**Comment by gary-rowe** [comment]
Ready for review, merge and close. See `glidera` branch.

**Comment by jim618** [comment]
Looks good - I had a few comments (by email). 
Removed 'awaiting review' and popped back to 'bounced back'

**Comment by gary-rowe** [comment]
Made the changes, and here is a screen shot of the new "spacey" sidebar layout:

<img width="1012" alt="screen shot 2015-12-13 at 21 26 24" src="https://cloud.githubusercontent.com/assets/342133/11769480/581a58da-a1e0-11e5-99a2-6ef38acb22e1.png">

I've shrunk the Help icon (it was always a bit too large to my eye) and grouped Help and Contacts together since otherwise Contacts would be rather isolated while Help didn't fit naturally with the preferences group below.

Ready for review and close.

**Comment by jim618** [comment]
Agreed to group Contacts and Help.

I find the spacing not 'spacey' enough so have tried ThemeAwareTreeCell Rendering with a bigger gap.

Here it is at 25 pixels (rather than 15):
![25](https://cloud.githubusercontent.com/assets/919427/11783223/ef2a5c42-a26d-11e5-9633-a457ec8404ba.png)

And 35:
![35](https://cloud.githubusercontent.com/assets/919427/11783236/09d85fa8-a26e-11e5-9b45-b1f965cbafff.png)

I think 25 looks the best of the three so have committed that.

Other than that I think it works.
(The comments by email about sidebar persistence I think we can live with as the alternatives would be poorer.)

Changes made to glidera branch only.

Awaiting review (of updated spacing) and closing.

**Comment by jim618** [comment]
It is bikeshedding a bit I know, but on the Buy/sell lightbox there is a bit of visual interference between the 'Visit Glidera' button and the background credit card image. It is the oblongs where the credit card numbers go interfere with the button outline. 

As there is only one active element on that lightbox it's a shame it's not clearer. Not a biggie though as the credit card icon works quite well.

**Comment by jim618** [comment]
Going through all the FontAwesome icons the credit card one is definitely the best for this action.

**Comment by gary-rowe** [comment]
Looks fine to me. Closing.
