### ISSUE TITLE
Bitcoin address

### ISSUE THREAD

**Issue by kyerby** [bitcoin-solutions/multibit-hd#833]
Mining sites are not accepting my bitcoin address. I dont know if I am supposed to enter the dashes or not but neither way is working at any site. I cannot copy/paste the address which would make things a lot easier. Tried multiple times and sites rejected address every time. I cannot possibly use this wallet if no site accepts the address as a valid bitcoin address.

**Comment by jim618** [comment]
I think you are trying to use the wallet id (which is a directory name on your computer) rather than a bitcoin address.
Have a read of : https://multibit.org/en/help/hd0.1/request-bitcoin.html
which should explain how to create a bitcoin address in your wallet.

**Comment by jim618** [comment]
Clsoing as looks resolved
