### ISSUE TITLE
KeepKey localisation files needs updating

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#836]
in the most recent firmware for KeepKey the message for Transaction confirmation (on the KeepKey) has changed.
The MultiBit HD text needs changing accordingly

**Comment by jim618** [comment]
I have updated the English localisation files so that instead of saying:
```
TRANSACTION SUMMARY

Total of 3.34604 mBTC leaving your wallet, and a fee of 0.10000 mBTC
```

it now say:
```
TRANSACTION
Do you want to send 0.00334604 BTC from your wallet ? THis includes a transaction fee of 0.0001 BTC.
```

This matches what the KeepKey 1.03 firmware states.

The localisation files have been updated on crowdin.net for localisers to look at.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
