### ISSUE TITLE
Transactions Unconfirmed

### ISSUE THREAD

**Issue by x101x101x101x** [bitcoin-solutions/multibit-hd#839]
I started using MultibitHD a few weeks ago and everything was fine until the other day. I received a deposit of 500mBTC and sent out 300mBTC. Everything said "Unconfirmed Transaction". So I waited about 8 hours ad nothing happened. I clicked the repair utility and now my initial deposit says it is unconfirmed as well, which it was not before. 

Here is an example of one of the transactions: https://blockchain.info/tx/5d79d8d386bca01fefc431e826821d2086ecfbb1680b59544f46fa138a23c6fd

This is what now shows on my screen:
![capture](https://cloud.githubusercontent.com/assets/16826754/12496369/98cc04c4-c052-11e5-97b9-b9f6992f3327.PNG)

Transactions from Armory are working just fine and so are my payments through btc-e, so I am assuming it is multibitHD, any ideas on what I should do? In total now I am missing half a bitcoin.

**Comment by jim618** [comment]
You don't mention which version of MultiBit HD you are on - if it is before 0.1.4 then I would recommend you upgrade using https://multibit.org

You can try doing a 'Tools | Repair wallet' again - sometimes the peers you connect to can make a difference.

Failing that, try downloading Lighthouse (https://www.vinumeris.com/lighthouse) which uses the same wallet words and restore/create a wallet. Use your wallet words and Lighthouse will sync your wallet.

**Comment by jim618** [comment]
Also, there has been quite a large backlog of transactions recently so if your transaction have low fees there could be a delay in confirmation.

cointape.com is a good site to see what fee rate you need
Fee rate is shown in the Transaction details wizard (double click on the transaction).
https://tradeblock.com/bitcoin shows you the current state of the bitcoin network

**Comment by x101x101x101x** [comment]
I see the problem now. I did not even see where I can adjust the fees but I
found it. I set it a bit higher and it works perfect. I appreciate your
help.

**Comment by PedroD** [comment]
@x101x101x101x I have 3 stuck unconfirmed transactions. How can I adjust the fees in multibit hd?
