### ISSUE TITLE
Add Glidera referal URIs

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#840]
Add referral links for Glidera in format of:
```
The referral link that you will be using is

https://www.glidera.io/referral?client_id=[partner_api_key]&buydestinationaddress=[multibit_bitcoin_address]

partner_api_key: this is the Glidera assigned api key for Multibit. Your client_id is 700a89b3cf4ce97d08bb58ea4e550f38
multibit_bitcoin_address: this is the bitcoin address where purchased bitcoin will be sent
```

This will need separate Buy and Sell buttons as the Bitcoin address is only on the Buy button

**Comment by jim618** [comment]
I have added separate Buy and Sell buttons and the client_id to the referral URI.
The 'buydestinationaddress' is still to do as it is a bit more complex.

The credit card background icon caused some visual interference with the buttons so I have swopped it for a shopping basket. Have a look:

![screen shot 2016-01-22 at 13 45 26](https://cloud.githubusercontent.com/assets/919427/12512270/325019f2-c10f-11e5-932c-a85c4ff8e2b9.png)

![screen shot 2016-01-22 at 13 45 40](https://cloud.githubusercontent.com/assets/919427/12512273/39c3c03a-c10f-11e5-88a1-26637d05b1a3.png)

The credit card as background for comparison:
![screen shot 2016-01-22 at 13 40 27](https://cloud.githubusercontent.com/assets/919427/12512282/48c78274-c10f-11e5-82d4-d267eb58f241.png)

**Comment by jim618** [comment]
I have added in code so that when the user clicks on the 'Buy bitcoin at Glidera' button a new address is created and added to the Glidera URI.
Also a payment request is created and stored with the description 'Buy bitcoin at Glidera'. This then appears in the Payments screen and in Send/Receive.

(It can be deleted in the Payments screen).

The code needs a bit of tidying up (refactor similar code in this wizard and in the RequestBitcoinEnterDetailsPanelView class) and the workflow feels a bit clumsy but it is working.

Awaiting review.

**Comment by gary-rowe** [comment]
Looks good so far. Would it be worth leaving the credit card symbol in the sidebar and having a basket in the wizard? I know it breaks the continuity but the basket looks too feminine (see #828).

**Comment by jim618** [comment]
The icon should be the same in the sidebar and wizard - quite confusing otherwise.
There were some other payment-ey icons if you want to change it:

https://fortawesome.github.io/Font-Awesome/icons/

p.s. 50% of humanity is female !!

**Comment by jim618** [comment]
university/ bank might work:
http://fortawesome.github.io/Font-Awesome/icon/university/

**Comment by gary-rowe** [comment]
Fair point on the 50% of humanity, it's just that the shopping basket looks wrong in that position. It took me ages to settle on the credit card image last time. Perhaps change the position of the buttons on the wizard to be horizontally placed rather than vertical - that would mirror the existing Send/Request screen layout.

**Comment by jim618** [comment]
I've reverted it to credit card icon and adjusted the layout so that the two buttons are horizontal.
Pushed.

**Comment by gary-rowe** [comment]
Tested various combinations and it's all working fine. The new button layout with the consistent credit card iconography works for me:

<img width="1012" alt="screen shot 2016-01-22 at 21 21 53" src="https://cloud.githubusercontent.com/assets/342133/12523352/2ecd4efa-c14e-11e5-88ba-eb6afc797818.png">

Closing.
