### ISSUE TITLE
Sidebar spacing introduces ambiguous click zones

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#841]
Panning down the sidebar with the new spacing for 0.2.0 shows a continuous link cursor. In the spaces between icon groups this is maintained leading to an ambiguous click where the user is uncertain what their target is. There is a vertical asymmetry in sidebar cell boundaries that exacerbates this effect.

**Comment by gary-rowe** [comment]
I've slightly increased the spacing and the active area for clicking should now be more intuitive.

Here's a screen shot:

<img width="1012" alt="screen shot 2016-01-22 at 22 10 15" src="https://cloud.githubusercontent.com/assets/342133/12524436/f339387a-c154-11e5-8e2a-9d38126b3c77.png">

Ready for review and close.

**Comment by jim618** [comment]
LGTM - all clicks are unambiguous now. Closing.
