### ISSUE TITLE
Low spendable balance detected. some of your bitcoins are tied up with ongoing transactions.

### ISSUE THREAD

**Issue by wukken** [bitcoin-solutions/multibit-hd#844]
Hi, I have multibit HD and i want to empty my wallet to other account. But it allways says Low spendable balance detected. some of your bitcoins are tied up with ongoing transactions.

Its been from yesterday that i added money to the wallet. and all is confirmed with 163 blocks. 

Is this normal or is something wrong? when i sent a little money it doesnt work either. i dont know what to do anymore. i tried to search forums but didnt find my problem

**Comment by jim618** [comment]
Is the transaction propagated out to the bitcoin network ?
i.e. can you see it on somewhere like blockchain.info.

If so, then it should confirm normally.
That warning you can get if the transaction is slow to propagate (and then MultiBit HD won't let you spend the change until the transaction confirms)

**Comment by wukken** [comment]
Hi. I can see it on blockchain. What you mean with Slow to propagate?

Regards
Op 29-jan.-2016 6:17 PM schreef "Jim Burton" <notifications@github.com>:

**Comment by wukken** [comment]
and what does it mean. My balance is gone then but do i just need to w8 for few hours untill its fully gone or what?

**Comment by gary-rowe** [comment]
You may find this information useful: 

* https://multibit.org/en/help/hd0.1/send-bitcoin.html
* https://multibit.org/en/help/hd0.1/repair-wallet.html

Sometimes the Bitcoin network is slow to propagate a transaction and consequently MultiBit doesn't get the confidence it needs to treat the transaction as confirmed. Usually just waiting for 30 minutes or restarting MultiBit HD will be sufficient to clear it. If it is persisting then run Tools | Repair wallet to force a re-sync of all transactions you have done with the Bitcoin network.

**Comment by jim618** [comment]
Is this resolved now ?

**Comment by wukken** [comment]
Dear,


Thx for help. Its resolved. Maybe just say to people that it can take up to
24 hours before it has been sended. In my case that was the problem. And
cause of you guys I waited till it was ok. THX!!!

2016-02-03 16:34 GMT+01:00 Jim Burton <notifications@github.com>:

> Is this resolved now ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin-solutions/multibit-hd/issues/844#issuecomment-179295977>
> .
>



-- 
*Mvg Micha Vandenbroele*
*Torhoutsesteenweg 425 *
*8210 Veldegem*
(Mobile: 0032474735665
<https://www.facebook.com/micha.vandenbroele>
Email: vdbmicha@gmail.com
     Email werk: micha.vandenbroele@proximus.com

**Comment by jim618** [comment]
Ok great - yes sometimes especially when the network is busy - transactions don't confirm quickly.
Closing as resolved.

**Comment by gary-rowe** [comment]
I've added some content to the website help (`send-bitcoin.html`) to mention the 24 hour delay.
