### ISSUE TITLE
Can't send my bitcoins.

### ISSUE THREAD

**Issue by Schitak** [bitcoin-solutions/multibit-hd#845]
can someone help me plz

![1](https://cloud.githubusercontent.com/assets/17024136/12747605/26d9fa4a-c98c-11e5-8203-256f8d5128ec.png)

**Comment by jim618** [comment]
You need to send a little bit less as you aren't taking into account the miner's fee.

**Comment by Schitak** [comment]
but, i'm trying to send half of the btcs 
:/

**Comment by jim618** [comment]
You are trying to send a small amount of bitcoin: 0.000 05 BTC - about 2 cents.
Fees can typically be more than you have in your wallet currently

Have a look at: http://www.cointape.com for what typical fees are currently on the network.
Looking at a wallet I have open in MultiBit HD, the last two sends had fees 0f 0.0001 BTC, which is the TOTAL in your wallet.

You just need more bitcoin

**Comment by Schitak** [comment]
Thank you bro :+1:

**Comment by jim618** [comment]
You are welcome.
Closing
