### ISSUE TITLE
Reduce number of Glidera payment requests created

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#846]
Feedback from user testing:
```
> Would it possible to re-use unused requests on subsequent launches to the Glidera website? I think this would be cleaner
```
This would probably entail adding more state to the persisted payment requests as we currently don't track that it is for use by Glidera

**Comment by jim618** [comment]
I've added a boolean to the MultiBit HD payment request so that the 'created for Glidera' addresses are marked as such. This is persisted.

When a user presses the 'Buy bitcoin at Glidera' button the list of extant payment requests are subset by:
1) Created for Glidera ?
2) No transactions sent to this address ?

If an address is available it is reused (i.e. put on the Glidera URL but no new payment request created)

I have regression tested on older MBHD code, which loads the payment requests fine. It nukes any existing values when it writes out. Then a new version of MBHD will create ONE (only) new payment request. This is fine.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working and code review looks fine.

Closing.

**Comment by jim618** [comment]
I have reopened this as I have modified the code slightly and it needs re-review.

Change:
When a Glidera address is reused there is no need to save a payment request (you just checked that there was one free) so I have modified the code to honour this.

This will save time and IO.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
