### ISSUE TITLE
BIP70 payment requests not matched on wallet replay

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#850]
I just did a Tool | Repair wallet on a wallet with a BIP70 request in.

The send tx that paid this did not correctly match the payment request, leaving both visible.
Screenshot:

![screen shot 2016-02-08 at 15 14 08](https://cloud.githubusercontent.com/assets/919427/12889444/d55944b0-ce76-11e5-84ba-a37161ae142f.png)

See 12th Jan. The payment request should be matched with the send and disappear from the main payments screen.

**Comment by jim618** [comment]
Fix for this is in develop.
You can test it using the Donate button on eclipse.org and then paying the Payment Request and doing a Tools | Repair wallet. You should see the payment request and payment match (so you only see the transaction until you drill down into the Transaction Details Wizard).

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
