### ISSUE TITLE
Add ability to change payment descriptions

### ISSUE THREAD

**Issue by antanst** [bitcoin-solutions/multibit-hd#864]
Unless I've missed something, currently there's not a way to change a transaction's description from the Payments table. I believe such a feature would be useful.

**Comment by gary-rowe** [comment]
Thanks for the feedback. This feature has been hanging around for a while (see #694) and it should receive some attention.

I'll close this issue since it is essentially a duplicate, but I'll bump the other one into a release milestone so it gets done.

Closing.
