### ISSUE TITLE
change not spendable

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#869]
I just sent a tx using the develop code (0.2.1) and though the tx broadcast ok. the change was not spendable. It was marked as 'unconfirmed'. This change should be spendable if seen by enough peers (in this case it was - seen by 3 peers out of 10).

**Comment by jim618** [comment]
Screenshot:

![screen shot 2016-02-26 at 17 15 22](https://cloud.githubusercontent.com/assets/919427/13359508/8eae4cc4-dcac-11e5-9ee5-61a2161e0e55.png)

Could be the change to Transaction#getConfidence is too aggressive

**Comment by jim618** [comment]
Once the tx confirmed everything was as you'd expect.

**Comment by jim618** [comment]
I have modified the Transaction#getConfidence so it is not so aggressive in overwriting the Wallet TransactionConfidence.  This is an update to release-0.13.3-alice-0.2.1-SNAPSHOT

In testing this removes the 'send and change is not spendable' problem of the OP and all the rest of Send/Receive/Repair behaviour works as expected.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
