### ISSUE TITLE
Problems trying to compile, test fails, testParseSeedTimestamp(org.multibit.hd.core.utils.DatesTest)

### ISSUE THREAD

**Issue by Alex-Jaeger** [bitcoin-solutions/multibit-hd#872]
Hi Jim! Thanks for all the hard-work.
I'm not great at java, been trying to learn a bit by reading your source.

Trying to compile under Linux, using Netbeans 8.1, with JDK 1.7.0_79.
One of the tests fails, with this message:

```
testParseSeedTimestamp(org.multibit.hd.core.utils.DatesTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalArgumentException: The datetime zone id 'GMT-05:00' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:223)
	at org.multibit.hd.core.utils.DatesTest.tearDown(DatesTest.java:41)
```

Do you happen to know what might be going on? Tried searching for the error and couldn't find anything.
Alternatively, how do you compile? Which IDE do you use and which version?

Thanks!

**Comment by gary-rowe** [comment]
Hi @Alex-Jaeger It looks like you've uncovered a deprecated test. I've pushed a fix to the develop branch that should enable it to build correctly for you now.

**Comment by Alex-Jaeger** [comment]
Hi Gary! Thank you very much for the quick response.
The error from that test is gone, now I'm getting:
`
Results :

Tests in error: 
  LocalisedDateUtilsTest.tearDown:44 » IllegalArgument The datetime zone id 'GMT...
  LocalisedDateUtilsTest.tearDown:44 » IllegalArgument The datetime zone id 'GMT...
  LocalisedDateUtilsTest.tearDown:44 » IllegalArgument The datetime zone id 'GMT...`

Can that one be disabled too? Can I go ahead and disable that unit test completely?

**Comment by gary-rowe** [comment]
Rather than disable the test, I've corrected it. It turns out the code was assuming too much in regard to returning to the original time zone.

Let me know how you get on.

**Comment by Alex-Jaeger** [comment]
Thank you! That solved the issue.

**Comment by gary-rowe** [comment]
No worries. Closing.
