### ISSUE TITLE
FEST tests cleanup

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#876]
Various FEST tests are failing on the debrit branch.
I have taken out the 'licence accepted' screen and I don't think the FEST test failures are related to that.

![screen shot 2016-03-09 at 13 26 16](https://cloud.githubusercontent.com/assets/919427/13636631/c3e70b22-e5fa-11e5-8e11-af5abb38eba5.png)

**Comment by gary-rowe** [comment]
That is a significant number of failures - most likely it's an unexpected presentation of a screen.

**Comment by jim618** [comment]
now refering to develop branch as everything is merged.

**Comment by jim618** [comment]
I've got the standard tests all running - in part by commenting out some problematic tests/ sections. These seem to be caused by the Atom alert that there is a new news article - the 'Yes' button interferes with some scripting that expects a 'Yes' elsewhere. (There are then two and the FEST test fails at that point.)

**Comment by jim618** [comment]
I've got the KeepKey and Trezor FEST tests running. Again with the same proveiso that I have been switching the failing tests to @Ignore.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
