### ISSUE TITLE
mb

### ISSUE THREAD

**Issue by AlexGBL** [bitcoin-solutions/multibit-hd#877]
Bug report
  Operating System:
  MultiBit HD Version:
  Steps to replicate the problem:
  1. Provide steps to reproduce
  Screen shot:
  2. Provide a screen shot (use CMD+SHIFT+4+SPACE+Click on Mac then drag image into Issue editor, ALT+PrtScr on Windows then paste into Issue editor)
  I've removed personally identifying information:

**Comment by jim618** [comment]
Closed as not an actionable bug report
