### ISSUE TITLE
Improvements to sync with Trezor

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#878]
I have committed (on debrit branch) various updates so that:
+ The future returned by the recalculate of the BloomFilter is got, plus a second delay. This is to ensure the remote Peer has the bloom filter before download starts
+ A repair wallet of a hard wallet now always syncs back to the earliest HD wallet date (earliestKeyDate is hard wallets).

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
