### ISSUE TITLE
All money in the wallet got unconfirmed!

### ISSUE THREAD

**Issue by ezhik97** [bitcoin-solutions/multibit-hd#881]
All money in the wallet just got 'unconfirmed'. All transactions switched to 'receiving'. Additional info says 'Unknown transaction status'. But if I open this transaction on blockchain.info, it says something like '536 confirmation' and so on.
Is it a bug?

**Comment by gary-rowe** [comment]
You probably just need to repair your wallet with Manage Wallet | Repair Wallet.

See this article: https://multibit.org/en/help/hd0.1/request-bitcoin.html for details on why the "+Unconfirmed" message appears in the "Tracking your payment request's progress" section.

**Comment by ezhik97** [comment]
Great! Repair wallet fixed the problem. Another question - why is it happened? I have Mac client (0.3.0). May be it is a side-effect of reserving the wallet in dropbox or using sleep mode on mac. Anyway, the problem is solved, so I'm going to close it.
