### ISSUE TITLE
Confirmed Balance Showing As Unconfirmed. Please help

### ISSUE THREAD

**Issue by jingyansu** [bitcoin-solutions/multibit-hd#891]
Hello, 
I have been using multibit HD for a long time. Suddenly, when i logged into my wallet, it appears that all my balance are showing an uninformed balance. I have more then 8700$ as Unconfirmed. Please help urgently. 
Note: I restored the wallet. It doesn't help. 

Thanks in advance.

**Comment by jingyansu** [comment]
Hello, I followed this discussion https://github.com/bitcoin-solutions/multibit-hd/issues/862#issuecomment-185816284 and repaired my wallet. It worked. Thanks

**Comment by jim618** [comment]
Glad you got it sorted.

**Comment by jingyansu** [comment]
Hello Jim, Thanks for your response. I have sent you an email to your personal email address. asking for some advice. Could you please check your email. 

Thanks.

**Comment by nerijuslietuva85** [comment]
hi. i have same ishue with my walet. how do you got fixed yours?
