### ISSUE TITLE
Reset blockchain and BTC is now missing

### ISSUE THREAD

**Issue by cyberatt** [bitcoin-solutions/multibit-hd#897]
Hi,

On Friday I sent 0.318 BTC
I sent money to this wallet 1DqGrCgKkXM8Fks8eAcj3R8NkjfKwnnM7x
from my multibit wallet 1G93BmtiR3FYLDqyvzt522xuuGXuAtcRfD

Today the money had not gone to the new wallet, I had a square and one peer had seen the transaction so I reset the blockchain.

Now the money is no longer there. What can I do?

Help please,

John

**Comment by cyberatt** [comment]
Further, I have contacted the people [coinjar] today and they have not received the BTC

**Comment by jim618** [comment]
In your post you don't mention which version of MultiBit CLassic you are using.
If you are not on the most recent version (0.5.19) then most likely the fee being attached is too low.

Older versions of MultiBit set a fee which was ok at the time but it is far too low nowadays.

If this is the case then:
1) Update using the latest installer from //https://multibit.org/releases/multibit-classic/
2) Do a Tools | Reset blockchain and transactions to resync your wallet to what is on the blockchain.
3) Do the send again.

**Comment by cyberatt** [comment]
My god it actually worked. I installed MultiBit Classic, from 0.5.15 which I had been using and reset the block chain and there was the missing BTC. Thanks Jim, now I understand it was the fees that caused the delay.

**Comment by jim618** [comment]
Glad you sorted it out.

Fees in bitcoin are a bit problematic.
In Classic 0.5.19 we have put in a fee slider (in Preferences) so that users can tweak the fees they add too.
